### ISSUE TITLE
Add option for email_from_field and email_add_domain

### ISSUE THREAD

**Issue by KevSex** [johnsusek/praeco#119]
Would be good to see if this can be implemented into the GUI to make use of the data retrieved from the events.

```
email_from_field: "data.user"
email_add_domain: "@example.com"
```
Reference: https://elastalert.readthedocs.io/en/latest/ruletypes.html#email

As an alternative (or addition), it would be awesome if there was like an 'advanced' section for the rules that allowed you to write custom yml config, for instance, adding in the above.

**Comment by nsano-rururu** [comment]
The UI settings for email_from_field and email_add_domain will be enabled in 1.8.5.
