### ISSUE TITLE
Add Telegram support

### ISSUE THREAD

**Issue by johnsusek** [johnsusek/praeco#125]

**Comment by surfer190** [comment]
@johnsusek Can you give me any pointers on where to start with this enhancement?

**Comment by johnsusek** [comment]
@surfer190 Yes, I would take a look at the Slack alerter for a start. Definitely suggest Vue/Vuex experience though or you might have a tough time.

**Comment by johnsusek** [comment]
@surfer190 Just pushed a new release with Telegram support. I don't use it, so can you test it out and let me know how it goes? Thanks!

**Comment by surfer190** [comment]
@johnsusek It is working correctly, thank you.

Some potencial improvements:
1. Default the telegram bot url in `rules/BaseRule.config` to `api.telegram.org`
2. Improve the error message, tell the user to update the bot configuration in `rules/BaseRule.config`

<img width="1089" alt="Screen Shot 2019-07-10 at 08 27 46" src="https://user-images.githubusercontent.com/3285222/60946342-4086c100-a2ee-11e9-8733-4e4ef3e4ebcf.png">

**Comment by johnsusek** [comment]
Added in latest
