### ISSUE TITLE
Add option to use multiple query keys

### ISSUE THREAD

**Issue by adrienyhuel** [johnsusek/praeco#128]
Elastalert allow us to use multiple query keys, in order to make multiple grouping.

The syntax is : 
query_key: ["user","action"]

Please, can you add this in praeco UI. 

I modified manually the yml, and the rule executes correctly.
But in praeco UI it shows like that, and I can't modify it : 
![image](https://user-images.githubusercontent.com/14916484/57255814-4e516900-7055-11e9-9476-31f8588572b9.png)

**Comment by nsano-rururu** [comment]
@adrienyhuel 

It's currently under development, but is it okay to look like the following?

input
![1](https://user-images.githubusercontent.com/22293449/111882331-612a7800-89f8-11eb-82a3-44157b8837f0.PNG)

output
![2](https://user-images.githubusercontent.com/22293449/111882336-64bdff00-89f8-11eb-9395-200153e690e6.PNG)

**Comment by adrienyhuel** [comment]
@nsano-rururu looks great, can't wait to test it 😁

**Comment by nsano-rururu** [comment]
I am developing in the following branch.
https://github.com/johnsusek/praeco/tree/multiple_query_keys

**Comment by nsano-rururu** [comment]
1.8.3 released.(Add option to use multiple query keys)
https://hub.docker.com/r/praecoapp/praeco

**Comment by adrienyhuel** [comment]
@nsano-rururu 
I updated to 1.8.3, and when I open rules with only 1 query key (not an array in yml), I have an error :
![image](https://user-images.githubusercontent.com/14916484/112044441-1e78b500-8b4a-11eb-89e2-ae681b1e5b70.png)

YML : 
query_key: beat.hostname

**Comment by nsano-rururu** [comment]
Since I changed the data type, open yaml directly and delete the description of query_key.

**Comment by adrienyhuel** [comment]
@nsano-rururu it works if I edit manually the yaml, but that means all Praeco users must modify manually their yml when moving to 1.8.3

**Comment by nsano-rururu** [comment]
In the release notes, query_key was deleted before the version upgrade and added after the version upgrade. We do not manually announce changes to everyone. Because there will be people who fail to describe and give another error.

**Comment by adrienyhuel** [comment]
> 
> 
> In the release notes, query_key was deleted before the version upgrade and added after the version upgrade. We do not manually announce changes to everyone. Because there will be people who fail to describe and give another error.

I seen you just explained that in UPGRADING.md.
We have many rules, then we'll update manually the yaml in the docker volume before upgrading.

**Comment by nsano-rururu** [comment]
1.8.4 released.(fix multiple query keys)
https://hub.docker.com/r/praecoapp/praeco

**Comment by nsano-rururu** [comment]
Close once. Please reopen if there is a problem.
