### ISSUE TITLE
Split up ConfigCondition into multiple files

### ISSUE THREAD

**Issue by johnsusek** [johnsusek/praeco#135]
This component is getting rather large and should be split up into multiple components.

**Comment by nsano-rururu** [comment]
@johnsusek 

What unit were you thinking of splitting?

**Comment by nsano-rururu** [comment]
@johnsusek 

I have no plans to respond. Can I close it?

**Comment by johnsusek** [comment]
Go ahead and close it. Just a maintenance task for myself.
