### ISSUE TITLE
[elastalert-server] Stop all when elastalert crash

### ISSUE THREAD

**Issue by adrienyhuel** [johnsusek/praeco#136]
When elastalert stops or crash, node server still run, then docker container doesn't restart, and elastalert isn't restarted.

bitsensor added code to exit the server when elastalert stops : 
bitsensor/elastalert@ad03913a1faf07b36e36297d67bfd10211ec494e

Can you pull it to your repo ?

**Comment by johnsusek** [comment]
Will do, thanks for the heads up @adrienyhuel  :)
