### ISSUE TITLE
Accent in rules names

### ISSUE THREAD

**Issue by adrienyhuel** [johnsusek/praeco#137]
When I create a rule with an accent in the name, elastalert doesn't start (something with unicode...).

Can you either add a warning in Praeco when saving a rule, or remove all accents in rule name when saving it ?

**Comment by johnsusek** [comment]
Okay, I'll see what I can do. Ideally elastalert should support this upstream, so I might change it there and put in a PR with them. If that's too difficult I'll do as you suggest. Thanks for the report

**Comment by adrienyhuel** [comment]
@nsano-rururu 

I just tried latest praeco/elastalert-server docker images, and I'm able to create rules with accent and arobaz in name, without any problem in elastalert2.
