### ISSUE TITLE
Add MS Teams support 

### ISSUE THREAD

**Issue by surfer190** [johnsusek/praeco#143]
Add support for MS Teams.

MS Teams configuration info required for elastalert can be found [here](https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=telegram#ms-teams)

**Comment by StefanSa** [comment]
It would be good if MS teams are supported.

**Comment by mrwhoo** [comment]
thumbs up for teams, please!

**Comment by danielskowronski** [comment]
Something like that https://github.com/ServerCentral/praeco/pull/192? :)

**Comment by johnsusek** [comment]
Merged 192!
