### ISSUE TITLE
Add "limit_execution" parameter in rule config

### ISSUE THREAD

**Issue by adrienyhuel** [johnsusek/praeco#161]
Since you pulled elastalert from yelp/master, there is an useful feature included in elastalert : we can limit rule execution time with a cron expression (ie : by example, make a rule run only during working hours).

See : https://github.com/Yelp/elastalert/issues/492

Can you add a input box in preaco, where we can set this parameter in rule config ("limit_execution") ?

**Comment by kklemen** [comment]
Related: would be great to have a per rule configuration for run_every parameter.
Added to master elastalert just recently:

https://github.com/Yelp/elastalert/issues/497

**Comment by nsano-rururu** [comment]
@adrienyhuel  @kklemen

It is recognized that limit_execution has the following settings. Is there any?

```
limit_execution: "* 02-03 * * *"
```

Do you feel that the input fields and default values for Minute, Hour, Day, Month, and Week are all "*"?
If not, please tell us what kind of UI you want.

**Comment by adrienyhuel** [comment]
@nsano-rururu 

Yes, limit_execution seem to be a cron syntax.

The default value should be None, in order to not activate this function.
See : https://github.com/Yelp/elastalert/blob/1dc4f30f30d39a689f419ce19c7e2e4d67a50be3/elastalert/elastalert.py#L1253

For UI, basic string could be OK, as most of us understand crontab syntax.
For an enhancement, maybe you could use some graphical component, like https://github.com/karoletrych/vue-cron-editor.

**Comment by nsano-rururu** [comment]
@adrienyhuel

thank you for your answer. I didn't know vue-cron-editor. We are planning to add a setting screen using vue-cron-editor.

**Comment by nsano-rururu** [comment]
@adrienyhuel

Is there any problem with the following feeling? If there is no problem, it will be released at the time of 1.8.0 release.
https://github.com/johnsusek/praeco/tree/limit_execution
![1](https://user-images.githubusercontent.com/22293449/110239675-7e3c6100-7f8b-11eb-89e3-44d236df42d5.PNG)
![2](https://user-images.githubusercontent.com/22293449/110239680-809ebb00-7f8b-11eb-95a7-125cc9b70774.PNG)
![3](https://user-images.githubusercontent.com/22293449/110239681-82687e80-7f8b-11eb-86d0-63ef95f09756.PNG)
![4](https://user-images.githubusercontent.com/22293449/110239689-8eecd700-7f8b-11eb-8042-c5eda290ef7a.PNG)

**Comment by adrienyhuel** [comment]
@nsano-rururu that looks great !

**Comment by nsano-rururu** [comment]
Praeco has released a new docker image. 1.8.0
https://hub.docker.com/r/praecoapp/praeco

**Comment by adrienyhuel** [comment]
@nsano-rururu we're going to test it asap

**Comment by nsano-rururu** [comment]
Close once. Please reopen if there is a problem.
