### ISSUE TITLE
praeco supports SNS?

### ISSUE THREAD

**Issue by nirmit8** [johnsusek/praeco#167]
We are thinking to implement praeco on AWS. Wanted to know if SNS is supported as a Destination for an alert because elastalert supports it.

**Comment by johnsusek** [comment]
Don't have SNS in praeco yet, adding as a feature suggestion. 

You can check out this PR for an example of adding an alert destination if you know some Vue and wanted to try it yourself: 
https://github.com/ServerCentral/praeco/pull/163/files

**Comment by nsano-rururu** [comment]
Share the precautions when responding.

First, the information in the document is outdated.

sns_topic_arn, aws_access_key, aws_secret_key, aws_region, profile are written,
Currently, sns_topic_arn, aws_access_key_id, aws_secret_access_key, aws_profile.
I think I forgot to update the documentation.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#sns
>sns_topic_arn: The SNS topic’s ARN. For example, arn:aws:sns:us-east-1:123456789:somesnstopic
>
>Optional:
>
>aws_access_key: An access key to connect to SNS with.
>
>aws_secret_key: The secret key associated with the access key.
>
>aws_region: The AWS region in which the SNS resource is located. Default is us-east-1
>
>profile: The AWS profile to use. If none specified, the default will be used.

I confirmed by looking at the line 931-942 of the source code
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L931

```
class SnsAlerter(Alerter):
    """ Send alert using AWS SNS service """
    required_options = frozenset(['sns_topic_arn'])

    def __init__(self, *args):
        super(SnsAlerter, self).__init__(*args)
        self.sns_topic_arn = self.rule.get('sns_topic_arn', '')
        self.aws_access_key_id = self.rule.get('aws_access_key_id')
        self.aws_secret_access_key = self.rule.get('aws_secret_access_key')
        self.aws_region = self.rule.get('aws_region', 'us-east-1')
        self.profile = self.rule.get('boto_profile', None)  # Deprecated
        self.profile = self.rule.get('aws_profile', None)
````

Second

An error will occur if the rule file is output as shown below.

```
alert:
- "sns"
sns_topic_arn: "arn:aws:sns:~aws region name~:~id~:~topic name~"
aws_region: "~aws region name~"
aws_access_key_id: "~my access key~"
aws_secret_access_key: "~my secret key~"
```

You need to output to a rules file as follows.

```
alert:
  - sns:
      sns_topic_arn: "arn:aws:sns:~aws region name~:~id~:~topic name~"
      aws_region: "~aws region name~"
      aws_access_key_id: "~my access key~"
      aws_secret_access_key: "~my secret key~"
```

**Comment by nsano-rururu** [comment]
@nirmit8 

I'm submitting a pull request to review ElastAlert's settings and modify the document. 
Once merged, we plan to launch additional support for Praeco.
[Fix SNS Program & Docs #2793](https://github.com/Yelp/elastalert/pull/2793)

**Comment by nsano-rururu** [comment]
@johnsusek 

It seems that it will take some time for my pull request to be merged into ElastAlert, so is it OK to add it to [ElastAlert Server](https://github.com/johnsusek/elastalert-server) as a patch?
If so, you can start immediately.

**Comment by johnsusek** [comment]
Sure, go ahead and put a PR into that repo with the patch. It should be similar to this https://github.com/johnsusek/elastalert-server/commit/cb8a68b7687f56b4e50fa90cf6ecee14597bb24d

**Comment by nsano-rururu** [comment]
Thank you for your reply. We plan to make a pull request based on the link information.
This time we plan to support SNS and Zabbix. By the way, Zabbix does not work properly without applying the patch.
If you are happy with the implementation, I think you can issue a pull request later this month.
[Bugfix and better error handling on zabbix alerter #2640](https://github.com/Yelp/elastalert/pull/2640)

**Comment by johnsusek** [comment]
@nsano-rururu Just a reminder, once https://github.com/Yelp/elastalert/pull/2640 and https://github.com/Yelp/elastalert/pull/2783 are merged, then we need to remove these patches.

**Comment by nsano-rururu** [comment]
@johnsusek 

I have made a pull request for Zabbix / SNS support.

added Zabbix / SNS patch #2 
https://github.com/johnsusek/elastalert-server/pull/2
added Zabbix / SNS support #215
https://github.com/johnsusek/praeco/pull/215

**Comment by nsano-rururu** [comment]
@nirmit8

SNS supported
[added Zabbix / SNS support & Library Update #215](https://github.com/johnsusek/praeco/pull/215)
