### ISSUE TITLE
Add Support for mattermost alerter

### ISSUE THREAD

**Issue by C2L2C** [johnsusek/praeco#168]

**Comment by C2L2C** [comment]
Tried using it with slack alerter, which works with elastalert though. Would be great if we can add Mattermost support.

**Comment by johnsusek** [comment]
Thanks for the suggestion!

If you want to try adding it yourself you can see how the JIRA alerter was added in this PR: https://github.com/ServerCentral/praeco/pull/163/files

**Comment by nsano-rururu** [comment]
I submitted a PR
[added Mattermost support #198](https://github.com/ServerCentral/praeco/pull/198)

**Comment by nsano-rururu** [comment]
@C2L2C 

Mattermost supported
[added Mattermost / Command / Line Notify / Gitter support #211](https://github.com/johnsusek/praeco/pull/211)
