### ISSUE TITLE
issue with false alerts

### ISSUE THREAD

**Issue by kklemen** [johnsusek/praeco#170]
I've got a rule set up like so that keeps sending false alerts.

`WHEN count OVER all documents WITH FILTER nos.msg_type.keyword:"PostSearchReminderNotification"IS BELOW 6 FOR THE LAST 1 hour WITH OPTIONS`

visualization in praeco looks like this:
notice the entry at 3PM.
https://i.imgur.com/oYKLZnZ.png

Now I update the rule to check the 8 hour time window.
`WHEN count OVER all documents WITH FILTER nos.msg_type.keyword:"PostSearchReminderNotification"IS BELOW 6 FOR THE LAST 8 hour WITH OPTIONS`

visualization in praeco looks like this:
notice the last entry on the very right, it comes back as empty (no entries).  https://i.imgur.com/zAMaIDu.png

Double checked kibana and it properly shows the entry.
https://i.imgur.com/7KCoAqV.png (each block represents one hour, gray on the right is the NOW).

The 8 hour time window should contain the entry for 3 pm shown previously but it does not and sends out a false alert.

Because of this issue I'm getting a ton of false alerts every day. 
What may be the cause?

It's happening for other alerts as well.

**Comment by johnsusek** [comment]
So I'm not entirely clear what's going on here, but I should mention that the last entry represent partial data and it's a "complete" bucket/entry yet.

https://github.com/ServerCentral/praeco/issues/84

The generation of the chart is separate from when the alerts decide to fire, so those issues probably aren't linked directly. 

But it still sounds like you have alerts firing when you don't want them to. Can you post your rule yaml here?
