### ISSUE TITLE
ERROR Rule not found, it may have been moved or deleted.

### ISSUE THREAD

**Issue by franviera92** [johnsusek/praeco#176]
Hi, I need a help.

I am trying to save a rule but I get the following error

>       Routes: Request for '/ rules /: id' failed with error:
> 
>       [Error: EACCES: permission denied, open '/opt/elastalert/rules/webfilter.yaml'] {
>        errno: -13,
>         code: 'EACCES',
>        syscall: 'open',
>         path: '/opt/elastalert/rules/webfilter.yaml'
>       }

---------------
I try to correct with the following steps:

1. docker-compose exec elastalert sh
2. chmod -R 777 / opt / elastalert / rules / opt / elastalert / rule_templates

But it fails and I get:

chmod: /opt/elastalert/rules: Operation not permitted
chmod: /opt/elastalert/rules: Operation not permitted
chmod: /opt/elastalert/rule_templates: Operation not permitted
chmod: /opt/elastalert/rule_templates: Operation not permitted

**Comment by daichi703n** [comment]
Hi, @franviera92 
Are you using this `docker-compose.yml`?
https://github.com/franviera92/Cluster_Elastic_Docker/blob/master/docker-compose.yml

You have to add `servercentral/elastalert` container and setup config files that volume mounted.
https://github.com/ServerCentral/praeco/blob/a601eb3b1637791e96a04dd593d4c46340b3b1ef/docker-compose.yml#L4-L18

Please refer to the praeco architecture.
https://github.com/ServerCentral/praeco/tree/a601eb3b1637791e96a04dd593d4c46340b3b1ef#architecture-details

**Comment by karimelc** [comment]
HI, I'm getting the same error and I use the docker-compose.yml above. @franviera92 did you find a solution?

**Comment by daichi703n** [comment]
Hi, @karimelc 
Please show me your `docker-compose.yml` and directory tree.

**Comment by karimelc** [comment]
Hi @daichi703n,

docker-compose.yml:

version: '3'

services:
  elastalert:
    image: 'servercentral/elastalert:latest'
    ports:
      - '3030:3030'
      - '3333:3333'
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
     - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'servercentral/praeco:latest'
    ports:
      - '80:8080'
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf

Directory tree:

.
├── config
│   ├── api.config.json
│   └── elastalert.yaml
├── docker-compose.yml
├── nginx_config
│   ├── default.conf
│   └── nginx.conf
├── public
│   ├── index.html
│   ├── js
│   │   └── cron-ui.min.js
│   └── praeco.config.json
├── rules
│   └── BaseRule.config
└── rule_templates

**Comment by daichi703n** [comment]
@karimelc Thanks.
What is the permission of `rules` directory on the host? `root root 755`?
In `elastalert` container, `node(1000):node(1000)` tries to write rules into `rules`. You have to adjust permission of `rules` directory to `1000 1000 755` or `root root 777` before deploy it.

This is a little hacky, but it works at a moment. I think this issue should be fixed in the next release.

**Comment by karimelc** [comment]
Hi @daichi703n, thank you! What I have done temporarily is to chown the directory once the container is up, but your solution is much better!
