### ISSUE TITLE
Help with timestamp 

### ISSUE THREAD

**Issue by franviera92** [johnsusek/praeco#178]
I need the timestamp field to be with the time of Santigo Chile but I can't match it, how can I do it?
 
Attempts are made to access the website at webwhatsapp.com from source IP 10.20.21.112, blocked action is taken to a site with Phishing category dated: **2019-11-22T15: 01: 27Z.**

User: CUSER

At least 1 events occurred between 2019-11-22 11:56 -03 and 2019-11-22 12:01 -03

> My docker-compose.yml
> 
> version: '3'
> 
> services:
>   elastalert:
>     build:
>       context: elastalert/
>     container_name: elastalert
> 
>     ports:
>       - '3030:3030'
>       - '3333:3333'
> 
>     volumes:
>       - ./config/elastalert.yaml:/opt/elastalert/config.yaml
>       - ./config/api.config.json:/opt/elastalert-server/config/config.json
>       - ./rules:/opt/elastalert/rules
>       - ./rule_templates:/opt/elastalert/rule_templates
> 
>     extra_hosts:
>       - 'elasticsearch:${PRAECO_ELASTICSEARCH}'
> 
>   webapp:
>     build:
>       context: webapp/
>     container_name: webapp
> 
>     ports:
>       - '8080:8080'
> 
>     volumes:
>       - ./public/praeco.config.json:/var/www/html/praeco.config.json
>       - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
>       - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf

> Dockerfile webapp
> 
> # https://github.com/elastic/elasticsearch-docker
> FROM servercentral/praeco
> 
> RUN apt-get update -y
> RUN apt-get install nano -y
> RUN unlink /etc/localtime 
> RUN ln -s /usr/share/zoneinfo/America/Santiago /etc/localtime
> 
> # Add your elasticsearch plugins setup here
> # Example: RUN elasticsearch-plugin install analysis-icu

Dockerfile elastalert

> # https://github.com/elastic/elasticsearch-docker
> FROM servercentral/elastalert
> 
> ENV TZ=America/Santiago

**Comment by daichi703n** [comment]
Hi, @franviera92 
Would you please check your Elasticsearch's document (record)? I don't know your log type (apache? nginx? fw?), but miss handling of original log's timezone often happens.

Regards,
Daichi

**Comment by johnsusek** [comment]
The timestamp field is not controlled by praeco, it is set by the records in elasticsearch.
