### ISSUE TITLE
Can't configure "smtp_auth_file" in BaseRule.config

### ISSUE THREAD

**Issue by iamk-karthik** [johnsusek/praeco#185]
Hi John,

   Thank you very much for creating such a nice GUI tool for elastalert.  

How to add "smtp_auth_file" parameter with praeco? [For me telegram is working like breeze]

For adding smtp authentication credentials i did the following... But not working

I am trying to include the "smtp_auth_file:" option in BaseRule.config.  
As per the elastalert docs the smtp_auth_file must contain only "username & password" and ends with ".yaml" extension.  If i try to add such a file inside "rules" directory then getting error like - "<smtp_auth_file>.yaml" is not valid rule file.  

If i try to keep the file in parent directory of "rules" then BaseRule.config adds "rules/../<parent_directory>/<smtp_auth_file>.yaml" in all rules which throws - no such file or directory error

Could you please show some light in this issue...

Thanks..

**Comment by daichi703n** [comment]
Hi, @iamk-karthik 
Workaround for this issue is specifying absolute path for `smtp_auth_file.yaml`.

This issue is occured by testing method of ElastAlert Server. When ElastAlert Server runs test, the rule is temporary copied to `/opt/elastalert/server_data/tests/`. Therefore, relative path from `BaseRule.config` and other rules will be broken.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
...
  File "/home/node/.local/lib/python3.6/site-packages/staticconf/loader.py", line 167, in yaml_loader
    with open(filename) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/elastalert/server_data/tests/../config/smtp_auth_file.yml'
```

**Comment by sentieoraushan** [comment]
@daichi703n  
I resolved it by copying BaseRule.config from praeco folder in my ~/elastalert/rules folder and it worked. It is fine to do that ?

**Comment by daichi703n** [comment]
@sentieoraushan 
Great!! That's right.

Sorry, I misread your plobrem at first time and linked this issue... Please update on #190.

**Comment by iamk-karthik** [comment]
> @daichi703n
> I resolved it by copying BaseRule.config from praeco folder in my ~/elastalert/rules folder and it worked. It is fine to do that ?

It worked fine for me too... Thank you..
