### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by sentieoraushan** [johnsusek/praeco#190]
![image](https://user-images.githubusercontent.com/50829965/75761882-d67cc980-5d5f-11ea-9dab-37b623fd690b.png)
I am getting above error. 
In config.json, the absolute path for elastalert is set to be /home/raushan/elastalert

**Comment by daichi703n** [comment]
Please refer to this issue.
https://github.com/ServerCentral/praeco/issues/185#issuecomment-584975233

It seems to be same situation.

**Comment by sentieoraushan** [comment]
@daichi703n
I resolved it by copying BaseRule.config from praeco folder in my ~/elastalert/rules folder and it worked. is it fine to do that?

**Comment by daichi703n** [comment]
@sentieoraushan
Great!! That's right.
