### ISSUE TITLE
Alerts not triggring all the time. 

### ISSUE THREAD

**Issue by karmine08** [johnsusek/praeco#197]
I am having issues understanding  why few alerts are not triggering on a timely manner. It is randome and the alerts don't trigger all the time. From what it seems like the same alert doesn't trigger  after triggering ones. 
FYI : i am not using aggregate.

**Comment by johnsusek** [comment]
You said "From what it seems like the same alert doesn't trigger after triggering ones.".

Try to reduce your Re-alert time. 


Also, please see this part of the readme:

**I'm not receiving alerts even though I expect them**
First of all, try to test your alert with varying time frames and see if that is returning any results.

If the test is returning results, but you are not receiving any alerts, check the error log. There may be a problem with your alerter settings. Make sure you edited rules/BaseRule.config and have correct values in there.

If the test is not returning results, even though you think it should, try reading the elastalert docs for your rule type. Compare the yaml from praeco with the options from the docs to make sure the rule is being created as expected. If praeco is generating the wrong yaml, please file an issue.
