### ISSUE TITLE
Alert log shows empty data 

### ISSUE THREAD

**Issue by talcoh2x** [johnsusek/praeco#209]
![image](https://user-images.githubusercontent.com/34831587/83546373-36bf0b00-a509-11ea-805f-a1090336c79f.png)

**Comment by talcoh2x** [comment]
ELK 7.x

**Comment by nsano-rururu** [comment]
https://github.com/ServerCentral/elastalert-server/pull/3

**Comment by nsano-rururu** [comment]
@johnsusek 

I have a pull request, but when will it be taken in? It is already confirmed that the operation has been confirmed and the problem is solved, so I would like you to import it, but is it feeling busy with another work? .. If there is anything I can do, I would like to help.

**Comment by johnsusek** [comment]
Will try to take a look at this, sorry I haven't had much time to spend on praeco lately

**Comment by johnsusek** [comment]
@talcoh2x This should be fixed in the latest release
