### ISSUE TITLE
Alert reports on an issue when does not reflect on view.

### ISSUE THREAD

**Issue by talcoh2x** [johnsusek/praeco#216]
Hi, I want to say thanks for your great job! the plugin very good and useful.

need your help with an issue that I can't figure out what's the problem.

I fixed the "date" on both docker images and now I can see the data shown in the right timezone and time. 
for some reason, I get a notification but as you can see in the picture the Node count is lower than 10.

Elastic 7.x
plugin: 1.1.0
![image](https://user-images.githubusercontent.com/34831587/85952505-6f200080-b972-11ea-8542-ff09c930a3f9.png)

**Comment by nsano-rururu** [comment]
@johnsusek

What do you think about this issue? Is it a bug?

**Comment by nsano-rururu** [comment]
@talcoh2x

We will lower the priority of the survey as there are other high priority tasks. Please understand.
