### ISSUE TITLE
Future Support for Elastalert API?

### ISSUE THREAD

**Issue by AddChickpeas** [johnsusek/praeco#218]
[From this comment](https://github.com/bitsensor/elastalert/pull/157#issuecomment-651797444), it looks like Bitsensor went under and is no longer going to be maintaining Elastalert API. 

Have you heard anything about how it will continue to be updated going down the line? I want to spend some more time trying to get this up and running in our kubernetes cluster, but the uncertainty of future support for the API is concerning.

**Comment by nsano-rururu** [comment]
About OSS

Manuals may not be organized
The developer is not responsible for fixing the bug
In many cases, the support of the developer cannot be received

**Comment by nsano-rururu** [comment]
Praeco uses ElastAlert Server, which is a fork of Bitsensor. Customization, bug fixes, ElastAlert 0.2.4 support, library updates, etc. Although there are some issues that require replacement of deprecated libraries (request and request-promise-native)

johnsusek/elastalert-server (DockerHub)
https://hub.docker.com/r/johnsusek/elastalert-server
johnsusek/elastalert-server (GitHub)
https://github.com/johnsusek/elastalert-server

**Comment by nsano-rururu** [comment]
I'm not an admin so I can't answer about Future Support. I answered only what I can answer.

**Comment by AddChickpeas** [comment]
Thanks. That's pretty much what I already figured. I probably should have posted this in the Elastalert Server fork since it's more related to the future of that build. 

Figured there wouldn't be any concrete answers, but wanted to double check if there had been any talk about how that will be handled. There's always some uncertainty with OSS software, but with Bitsensor gone the future of Elastalert Server is especially uncertain. Guess we'll just have to weigh our options and hope for the best if we do end up using Praeco. 

Thanks.

**Comment by nsano-rururu** [comment]
I haven't used ElastAlert or anything around it at work, so I didn't ask any questions so I don't have any problems in the future. Because I can maintain it myself

Issues cannot be posted on the ElastAlert Server fork site. If you fork, it's probably because you haven't enabled it on the GitHub settings screen. So, if you have any questions, requests, or bugs related to the ElastAlert Server fork, I think it's okay to post on Praeco's issues.

And maybe I know that,
You should consider not only ElastAlert but also log collection-alert notification by other methods such as Grafana, prometheus, Alertmanager, Grafana Loki.

**Comment by nsano-rururu** [comment]
Future support? .. I got the answer. It's over when I'm out of focus or dead. That's it.

**Comment by nsano-rururu** [comment]
Changed node.js to typescript based on Bitsensor's elastalert-server. 
I got an elastalert2-server that changed from elastalert to [elastalert2](https://github.com/jertel/elastalert2).
Also consider using [elastalert2-server](https://github.com/Karql/elastalert2-server).

If you want to use the full functionality of elastalert2, consider using elastalert2 directly.
Unlike the original elastalert, we also officially publish a docker image and a Kubernetes Help Chart.
