### ISSUE TITLE
Error when trying to use filter builder since updating to 1.2

### ISSUE THREAD

**Issue by AddChickpeas** [johnsusek/praeco#226]
We just updated to 1.2 and the filter builder is no longer functional. Manual filters can still be applied.

When you first try to use it, it throws the three errors below. After that, clicking "filter" doesn't have any noticeable effect. The normal menu that pops up never appears. Issue went away when I rolled back to 1.1.

![image](https://user-images.githubusercontent.com/32724595/90298169-b9900a80-de56-11ea-9747-310a66e0a15f.png)
<img width="299" alt="VirtualBoxVM_2020-08-14_17-47-04" src="https://user-images.githubusercontent.com/32724595/90298078-628a3580-de56-11ea-8706-be85bf9049e9.png">
<img width="306" alt="VirtualBoxVM_2020-08-14_17-47-13" src="https://user-images.githubusercontent.com/32724595/90298080-6453f900-de56-11ea-9d6a-0e44ca67fff9.png">
<img width="301" alt="VirtualBoxVM_2020-08-14_17-47-28" src="https://user-images.githubusercontent.com/32724595/90298082-65852600-de56-11ea-91c4-00f78782e68c.png">

**Comment by nsano-rururu** [comment]
@AddChickpeas 

Fixed version released
https://hub.docker.com/r/praecoapp/praeco/tags

**Comment by nsano-rururu** [comment]
@AddChickpeas

Thanks

**Comment by nsano-rururu** [comment]
@AddChickpeas 

We have released a fixed version of the Docker image because we found a bug that prevented us from creating a rules file.
https://hub.docker.com/r/praecoapp/elastalert-server
