### ISSUE TITLE
Index's with multiple dashes are truncated at first dash. 

### ISSUE THREAD

**Issue by joshbasho** [johnsusek/praeco#230]
Our index naming schema often ends up with indexes with multiple dashes in them. e.g: 
`app.event.aws-ec2-*`

Praeco ends up truncating these at the first dash when creating an alert causing a bunch of indexes to get lumped together. 

![image](https://user-images.githubusercontent.com/32724595/90443958-af624c00-e0a2-11ea-81f9-3509d71cc0f2.png)

**Comment by nsano-rururu** [comment]
@AddChickpeas

Do you agree with the recognition of bug reports?
