### ISSUE TITLE
[elastalert-server]Code refactoring & error handling

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#233]
**memo**

* loud-rejection
https://www.npmjs.com/package/loud-rejection
https://github.com/sindresorhus/loud-rejection

* Node.js Error Handling
https://www.joyent.com/node-js/production/design/errors
https://strongloop.com/strongblog/robust-node-applications-error-handling/
https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/
https://strongloop.com/strongblog/promises-in-node-js-with-q-an-alternative-to-callbacks/

**Comment by vtdat** [comment]
![image](https://user-images.githubusercontent.com/14995336/91154999-6f2b4b00-e6ec-11ea-83d1-e3984d2b6eee.png)

I encountered this error while creating new rule. Don't know if it's related.

**Comment by nsano-rururu** [comment]
We are not investigating when to respond because we are investigating the response. Because I spend my private time instead of working

**Comment by nsano-rururu** [comment]
We released a new Docker image by fixing the code in ESLint where the error occurred.
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by vtdat** [comment]
> We released a new Docker image by fixing the code in ESLint where the error occurred.
> https://hub.docker.com/r/praecoapp/elastalert-server

Sure, thanks. I'll check it out.

**Comment by nsano-rururu** [comment]
@vtdat 

We have released a fixed version of the Docker image because we found a bug that prevented us from creating a rules file.
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by vtdat** [comment]
> @vtdat
> 
> We have released a fixed version of the Docker image because we found a bug that prevented us from creating a rules file.
> https://hub.docker.com/r/praecoapp/elastalert-server

Thank you for your brilliant work. It'd be neat if you can include issue references in your commit or, at least, somewhere so ppl can keep track of.
