### ISSUE TITLE
Add a new Destination

### ISSUE THREAD

**Issue by talcoh2x** [johnsusek/praeco#234]
Hi, I have an idea to create Alertmanager in Kibana for that I thought to create a new Alerter as elasealert suggest. 
my ques is:
1) if there is some way to do it even if for now ill do it by modifying the YAML file after the rule is created ?? I mean by adding new Alerter as mentioned here: https://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html
2) there is some way to expose that  into the GUI for example if I have some params that I expect for them like: Team webhook
 and color in MS Teams?? 

thanks!

**Comment by nsano-rururu** [comment]
I'm not sure how it will happen. Please make a pull request if possible.

**Comment by talcoh2x** [comment]
@nsano-rururu  can I edit the Yaml file somehow to use with my "Alerter" as shown below 
https://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html

**Comment by nsano-rururu** [comment]
not interested

**Comment by nsano-rururu** [comment]
Now I want to prioritize how to deal with bug fixes and library changes

**Comment by talcoh2x** [comment]
@nsano-rururu  ok, I'll try to play with it later and make a pull request.
if there is some documentation on how to add a new Destination please share with me

**Comment by nsano-rururu** [comment]
■Document

ElastAlertでカスタムルールを作成する
https://qiita.com/perceptron01/items/994e01b1fc0ad121c27b

ElastAlertの監視ルールを拡張してすこしだけ幸せになる
https://qiita.com/ihsiek/items/e8e89b274e99e48067a2

■What is published

Nclose-ZA/elastalert_hive_alerter
https://github.com/Nclose-ZA/elastalert_hive_alerter

anjia0532/elastalert-wechat-plugin
https://github.com/anjia0532/elastalert-wechat-plugin

Hello-Linux/elastalert_wechat_plugin
https://github.com/Hello-Linux/elastalert_wechat_plugin

xuyaoqiang/elastalert-dingtalk-plugin
https://github.com/xuyaoqiang/elastalert-dingtalk-plugin

**Comment by nsano-rururu** [comment]
Can I close it?

**Comment by talcoh2x** [comment]
@nsano-rururu  yes 
thanks
