### ISSUE TITLE
WHEN field changes

### ISSUE THREAD

**Issue by talcoh2x** [johnsusek/praeco#235]
Hi, ques regarding "WHEN field changes" we can't see the data? as we can see for "count" for example.
![image](https://user-images.githubusercontent.com/34831587/90986233-e4323f80-e589-11ea-8297-14b4b20d64bd.png)

**Comment by nsano-rururu** [comment]
https://medium.com/@john_8166/praeco-walkthrough-5aada7e078a9

**Comment by talcoh2x** [comment]
@nsano-rururu  can you explain please how the link help?

**Comment by nsano-rururu** [comment]
I'm not using ElastAlert or Praeco at all, so I can't explain how to use it. I'm sorry.

**Comment by nsano-rururu** [comment]
From the feeling of seeing the following issues, it seems that you can also specify the average and maximum value
https://github.com/johnsusek/praeco/issues/193
