### ISSUE TITLE
Error while saving Rule, Rule not found, it may have been moved or deleted.

### ISSUE THREAD

**Issue by bhanupraveeng** [johnsusek/praeco#241]
Hello,

I have set-up praeco using docker as per installation manual. Started fine and when trying to create new rule and save, facing rule not found issues. Below errors in container log. Kindly let me know what could be the issue? Thanks

``18:49:46.652Z` ERROR elastalert-server: RulesController:  Failed to _findRule(Test) error: undefined
18:49:46.801Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
18:49:46.803Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
16:44:41.184Z ERROR elastalert-server: RulesController:  Failed to _findRule(asdasdasd) error: undefined
16:44:41.244Z ERROR elastalert-server: RulesController:  Failed to _findRule(asdasdasd) error: undefined
16:44:41.245Z ERROR elastalert-server:

    Routes:  Request for '/rules/:id' failed with error: 

     TypeError: Cannot read property 'write' of undefined
        at Object.edit (/opt/elastalert-server/src/controllers/rules/index.js:91:26)
        at /opt/elastalert-server/src/handlers/rules/id/post.js:16:12

16:44:41.933Z ERROR elastalert-server: RulesController:  Failed to _findRule(asdasdasd) error: undefined
16:44:41.971Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
16:44:41.987Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.''

Docker-compose.yml

`version: '3'
services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf`

api.config.json below:

`{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "192.168.1.144",
  "es_port": 9200,
  "es_username": "elastic",
  "es_password": "paseqweqweqewsda",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
`

**Comment by nsano-rururu** [comment]
We released a modified version of Docker image. We apologize for any inconvenience.
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by nsano-rururu** [comment]
* docker pull praecoapp/praeco
* docker pull praecoapp/elastalert-server
* docker-compose up --force-recreate --build

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/issues/239

**Comment by bhanupraveeng** [comment]
Thanks will try this upgrade and let you know
