### ISSUE TITLE
Can't manage to upgrade to 1.3.1

### ISSUE THREAD

**Issue by katerius** [johnsusek/praeco#242]
I don't know why i can't manage to upgrade praeco to 1.3.1 (Can't create rules with 1.3.0)

I am executing theses commands : 

docker pull praecoapp/praeco
docker pull praecoapp/elastalert-server
docker-compose up --force-recreate --build

I am doing something wrong ?

**Comment by nsano-rururu** [comment]
@katerius 

I don't know how to get the same error as you. Could not be reproduced.
Could you try the following command?
If you don’t like it, I can’t help you anymore

```
docker rm -f [elastalert-server container name]
docker rm -f [praeco container name]
docker rmi praecoapp/praeco:latest
docker rmi praecoapp/elastalert-server:latest
docker pull praecoapp/praeco
docker pull praecoapp/elastalert-server
docker-compose up --force-recreate --build
```

**Comment by nsano-rururu** [comment]
By the way, what is the structure of docker-compose.yml etc.?

**Comment by nsano-rururu** [comment]
@katerius

Do you mean the version display?
Praeco has not been modified at all, so the version display does not change. Only ElastAlertServer was fixed. .. ..
Is it okay to ask the question after confirming the operation after executing the command?

![キャプチャ](https://user-images.githubusercontent.com/22293449/91883181-09782980-ecbf-11ea-8d9e-58dddb194741.PNG)

**Comment by katerius** [comment]
So yeah it is just the version display my bad.
I got a permission denied when creating rules but i suppose i should set /rules to 777 ?

**Comment by katerius** [comment]
```
elastalert_1  |     Routes:  Request for '/rules/:id' failed with error: 
elastalert_1  |     
elastalert_1  |      [Error: EACCES: permission denied, open '/opt/elastalert/rules/test.yaml'] {
elastalert_1  |       errno: -13,
elastalert_1  |       code: 'EACCES',
elastalert_1  |       syscall: 'open',
elastalert_1  |       path: '/opt/elastalert/rules/test.yaml'
elastalert_1  |     }


```

**Comment by nsano-rururu** [comment]
look

https://github.com/johnsusek/praeco
>mkdir rules rule_templates
>chmod -R 777 rules rule_templates

**Comment by nsano-rururu** [comment]
> So yeah it is just the version display my bad.
> I got a permission denied when creating rules but i suppose i should set /rules to 777 ?

What is a bad display version? I do not get it.

**Comment by nsano-rururu** [comment]
New to Praeco and ElastAlert Server? I am confused because I do not know what kind of knowledge I have.

**Comment by katerius** [comment]
Yeah i'm new with praeco and ElastAlert Server, and with docker too.
Sorry for taking your time, i was confuse with the version number displayed in praeco

**Comment by vtdat** [comment]
praeco 1.3.1 isn't available in dockerhub yet, btw

**Comment by nsano-rururu** [comment]
I haven't changed praeco at all. So, actually, Praeco is the latest 1.3.0.
