### ISSUE TITLE
praeco not recieving emails

### ISSUE THREAD

**Issue by shettypriy** [johnsusek/praeco#243]
I am using praeco version 1.3 however, I am unable to receive the emails for an alert. We are using postfix email server. I checked the email logs but could not find any issues. Is there any way we can check why the emails are not triggered

**Comment by vtdat** [comment]
* Double check your email credentials, email config in BaseRule.config, etc. Plus, any errors will be pushed to elasticsearch with default elastalert_status_error index.

* Your problem seems related to ElastAlert/Elastalert-server, not Praeco.

**Comment by shettypriy** [comment]
issue has been fixed .. closing the thread
