### ISSUE TITLE
Support for match_enhancements

### ISSUE THREAD

**Issue by jtavan** [johnsusek/praeco#247]
It would be very nice to have a user interface for configuring match enhancements, which could be stored in a directory alongside rules and rule_templates and then referenced. There wouldn't need to be a lot of support for code editing - just the ability to paste in Python code, run some simple analysis on it to validate that contains a class that extends BaseEnhancement, and make it available to add to alerts.

**Comment by nsano-rururu** [comment]
Please make a pull request.

**Comment by jtavan** [comment]
> Please make a pull request.

I've started work on this. I have elastalert-server extended to support get/post/delete of python modules from the elastalerts_modules directory, and will next work on stitching it in to the UI. I'm not familiar with the code nor in front-end coding, so this could take some time, but I'll make a pull request once it's working.

**Comment by nsano-rururu** [comment]
Can I close it?
Or are you working on it?

**Comment by jtavan** [comment]
I started work on this but got pulled into other efforts and I'm not likely to have the time to complete this. I guess you can close it.
