### ISSUE TITLE
email and teams html format support 

### ISSUE THREAD

**Issue by mareban** [johnsusek/praeco#248]
Hello,

Is it possible to have an html table for "aggregation_summary_only" that generated an ascii bad formated table that is difficult to read please ?

Thanks for your heap and for this great project :-)

**Comment by nsano-rururu** [comment]
Related issue

[Alerts email format - support for HTML #127](https://github.com/johnsusek/praeco/issues/127)

**Comment by nsano-rururu** [comment]
Does "teams" match for "MS Teams"?

**Comment by nsano-rururu** [comment]
Is MS Teams HTML-supported in the ElastAlert settings? I saw the documentation but didn't understand
https://elastalert.readthedocs.io/en/latest/ruletypes.html#ms-teams

**Comment by vtdat** [comment]
> Is MS Teams html format supported in the ElastAlert settings? I saw the documentation but didn't understand
> https://elastalert.readthedocs.io/en/latest/ruletypes.html#ms-teams

I haven't tried but alerts will be interpreted to Markdown, and yes, you can use html tags in markdown.

**Comment by nsano-rururu** [comment]
Is Email a request to add an html editor and MS Teams a request to add a Markdown editor?

Vue2Editor
https://www.npmjs.com/package/vue2-editor

Vue Markdown Editor component for Vue.js
https://www.npmjs.com/package/v-markdown-editor

**Comment by vtdat** [comment]
> Is Email a request to add an html editor and MS Teams a request to add a Markdown editor?
> 
> Vue2Editor
> https://www.npmjs.com/package/vue2-editor
> 
> Vue Markdown Editor component for Vue.js
> https://www.npmjs.com/package/v-markdown-editor

That'd be great! However, to use html format in email you need to set `email_format` to `html`, which is not enabled by default 

https://elastalert.readthedocs.io/en/latest/ruletypes.html?highlight=email_format#email

**Comment by nsano-rururu** [comment]
I can't imagine how it can be implemented, so I can't handle it.

**Comment by nsano-rururu** [comment]
Will not be supported
