### ISSUE TITLE
TypeError: Cannot read property 'query_string' of undefined

### ISSUE THREAD

**Issue by vtdat** [johnsusek/praeco#251]
will be triggered when rules does not contain `query` at first index

https://github.com/johnsusek/praeco/blob/master/src/store/config/index.js#L100

**Comment by nsano-rururu** [comment]
I've returned the source code so I'll reopen it

**Comment by nsano-rururu** [comment]
praecoapp/praeco:latest praecoapp/praeco:1.5.1

**Comment by nsano-rururu** [comment]
@vtdat 

Please tell me the screen operation to reproduce this problem.
