### ISSUE TITLE
when using command destination with praeco, the quotes around my parameters get stripped out.

### ISSUE THREAD

**Issue by cvdjv** [johnsusek/praeco#263]
when using the command destination praeco strips out the single quotes.
which makes editing the rules tedious because you go to go back in and reapply the single quotes it strips out along with whatever edits you were making.

example:
/opt/praeco/scripts/sample.sh,--param1 '%(hive_variable)s', --param2 '%(hive_variable)s'
becomes after editing 
/opt/praeco/scripts/sample.sh,--param1 %(hive_variable)s, --param2 %(hive_variable)s which throws errors with parameters that have characters like : and -.

**Comment by nsano-rururu** [comment]
Current specifications

**Comment by nsano-rururu** [comment]
It does not correspond to its usage

**Comment by nsano-rururu** [comment]
It is not an implementation that does not support single quote input. Currently not supported, so it is not supported

**Comment by nsano-rururu** [comment]
May be supported in the future

**Comment by nsano-rururu** [comment]
The other thing about command alerts is that they are difficult to use, so we will prevent them from being used in the next version. We will revive the easy-to-use UI when it comes to it.

**Comment by nsano-rururu** [comment]
We will close this issue as we will respond to your request when it is time to reimplement command alerts.
