### ISSUE TITLE
slack_title_link is mapped with localhost:8080 by default if we create rules from GUI

### ISSUE THREAD

**Issue by parivallalradhakrishnan-ms** [johnsusek/praeco#265]
### ISSUE/PAIN Experiencing:
1. If rules are created from GUI then values for **slack_title_link**  is assigned by default with **'http://localhost:8080/rules/<rule_name>'** so we need to go backend to update rule file with actual praeco host name.
2. Even after updating rule file in backend if we edit rule from GUI then its again mapped to localhost:8080 so every time expecting us to update **slack_title_link**

is there easy way to handle this issue?

**Comment by nsano-rururu** [comment]
look
https://github.com/johnsusek/praeco#configuration

**Comment by nsano-rururu** [comment]
That's all for the answer.

**Comment by nsano-rururu** [comment]
Try changing the value of appUrl in praeco.config.json

**Comment by nsano-rururu** [comment]
What happened after that?
