### ISSUE TITLE
Add PagerDuty support

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#268]
It may be better to show / hide the input field by selecting v1 v2.

https://elastalert2.readthedocs.io/en/latest/ruletypes.html#pagerduty

PagerDuty
Send an Alert Event
https://developer.pagerduty.com/docs/events-api-v2/trigger-events/

|config| v1|v2|default value |input|remark|
|------|----|---|--------------|------|--------|
|pagerduty_service_key|〇|〇||el-input|Required|
|pagerduty_client_name|〇|〇||el-input|Required|
|pagerduty_event_type|〇|〇|trigger|el-radio<br>trigger, resolve, or acknowledge|Required|
|pagerduty_incident_key|〇|〇|''|el-input|Optional|
|pagerduty_incident_key_args|〇|〇|None|UI to add / update / delete key|Optional|
|pagerduty_proxy|〇|〇|None|el-input|Optional|
|pagerduty_api_version|〇|〇|'v1'|el-radio<br>'v1', 'v2'|Optional|
|pagerduty_v2_payload_class|ー|〇|''|el-input|Optional|
|pagerduty_v2_payload_class_args|ー|〇|None|UI to add / update / delete key|Optional|
|pagerduty_v2_payload_component|ー|〇|''|el-input|Optional|
|pagerduty_v2_payload_component_args|ー|〇|None|UI to add / update / delete key|Optional|
|pagerduty_v2_payload_group|ー|〇|''|el-input|Optional|
|pagerduty_v2_payload_group_args|ー|〇|None|UI to add / update / delete key|Optional|
|pagerduty_v2_payload_severity|ー|〇|'critical'|el-radio<br>'critical', 'error', 'warning', 'info'|Optional|
|pagerduty_v2_payload_source|ー|〇|'ElastAlert'|el-input|Optional|
|pagerduty_v2_payload_source_args|ー|〇|None|UI to add / update / delete key|Optional|
|pagerduty_v2_payload_custom_details|ー|〇|{}||Optional|
|pagerduty_v2_payload_include_all_info|ー|〇|False|el-switch|Optional|

---

- [x] pagerduty_service_key
- [x] pagerduty_client_name
- [x] pagerduty_event_type
- [x] pagerduty_incident_key
- [x] pagerduty_incident_key_args
- [x] pagerduty_proxy
- [x] pagerduty_api_version
- [x] pagerduty_v2_payload_class
- [x] pagerduty_v2_payload_class_args
- [x] pagerduty_v2_payload_component
- [x] pagerduty_v2_payload_component_args
- [x] pagerduty_v2_payload_group
- [x] pagerduty_v2_payload_group_args
- [x] pagerduty_v2_payload_severity
- [x] pagerduty_v2_payload_source
- [x] pagerduty_v2_payload_source_args
- [ ] pagerduty_v2_payload_custom_details
- [x] pagerduty_v2_payload_include_all_info

**Comment by nsano-rururu** [comment]
I plan to search the documentation and issues for yaml configuration examples

**Comment by arsalan993** [comment]
When it will be available btw. I need to integrate my Alerts with pagerduty

**Comment by nsano-rururu** [comment]
@arsalan993

Are you using pagerduty with elastaert?
I don't know if there are pagerduty users, so I was wondering what to do.

**Comment by arsalan993** [comment]
Well my company is using pagerduty

**Comment by nsano-rururu** [comment]
Praeco 1.8.10
