### ISSUE TITLE
Praeco supports Blacklist/Whitelist rule types, while elastalert seems to not support them?

### ISSUE THREAD

**Issue by lalebarde** [johnsusek/praeco#273]
Hi,

I am a newbie. I am reviewing OpenDistro features and I have been wondering about white and black lists. From what I could find, elastalert does not support them, but Praeco does. 

So either my elastalert review is wrong, either Preaco offers more than elastalert. Could you please fix my mind?

Regards,

Laurent

**Comment by nsano-rururu** [comment]
The whitelist and blacklist are on ElastAlert
https://elastalert.readthedocs.io/en/latest/ruletypes.html#blacklist
https://elastalert.readthedocs.io/en/latest/ruletypes.html#whitelist

**Comment by lalebarde** [comment]
Thanks Mr Naoyuki. Could you tell me please if it applies for `OpenDistro` ? I have searched without success in their documentation. What I could find is that `elastalert` [is licensed under the Apache License Version 2.0](https://github.com/Yelp/elastalert) and that this link points to the same documentation as your links. So I assume it is used also by `OpenDistro`.

**Comment by nsano-rururu** [comment]
elastalert is currently not actively maintained. Not recommended. There is no problem if you use it while fixing the bug.

**Comment by nsano-rururu** [comment]
I have no knowledge of opendistro, so I can't provide any information.

**Comment by lalebarde** [comment]
Is there a replacement for elastalert?

**Comment by nsano-rururu** [comment]
I also want to know

**Comment by nsano-rururu** [comment]
The following are notifications for alerts based on Elasticsearch data.

**Watcher**

https://www.elastic.co/guide/en/kibana/current/watcher-ui.html

**Alerting and action settings in Kibana**

[Alerts and Actions](https://www.elastic.co/guide/en/kibana/current/managing-alerts-and-actions.html)
[Managing Alerts](https://www.elastic.co/guide/en/kibana/current/alert-management.html)
[Alert details](https://www.elastic.co/guide/en/kibana/current/alert-details.html)
[Managing Connectors](https://www.elastic.co/guide/en/kibana/current/connector-management.html)

**Open Distro for Elasticsearch**

[Alerting](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/)

**Grafana**

Perform alerting on data in Elasticsearch with Grafana
https://grafana.com/docs/grafana/latest/alerting/
https://grafana.com/docs/grafana/latest/alerting/notifications/

**Comment by nsano-rururu** [comment]
I searched on Google. I've never used it all

**Comment by nsano-rururu** [comment]
I haven't seen any cases of Open Distro, Elast Alert, and Praeco, so if you have a problem, you will have to solve it yourself. Please use it if you can.

**Comment by lalebarde** [comment]
[Sentinl ](https://github.com/lmangani/sentinl)looks nice also.

**Comment by nsano-rururu** [comment]
Is it a prerequisite to use "Watcher"? I don't think it's free

**Comment by nsano-rururu** [comment]
I think it's nice to have a choice

**Comment by nsano-rururu** [comment]
Sentinl is a kibana plugin

**Comment by nsano-rururu** [comment]
ElastAlert Kibana Plugin
https://github.com/nsano-rururu/elastalert-kibana-plugin

**Comment by nsano-rururu** [comment]
Both Sentinl and Elast Alert Kibana Plugin are out of the options if you use them with the latest Elasticsearch / Kibana. Sentinl is kibana 7.6.1. ElastAlert Kibana Plugin supports up to Kibana 7.9.3

**Comment by nsano-rururu** [comment]
Projects considering migration to Open Distro for Elasticsearch
https://github.com/idaholab/Malcolm

**Comment by nsano-rururu** [comment]
The first question has been resolved and will be closed. Please do your best to select the tool.
