### ISSUE TITLE
Alert command 

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#275]
Hello there

When I write my command alert command with elastalert with preaco, it changes in the yaml file.

elastalert 
command: curl -k https://1.1.1.1/webconsole/APIController? -d "reqxml=<Request>xxxxxxxxxx

preaco
command: >-
  curl -k https://1.1.1.1/webconsole/APIController? -d
  "reqxml=<Request>xxxxxxxxxx"

it doesn't work in that way

**Comment by nsano-rururu** [comment]
So what? .. Are you free

**Comment by ozgursuder** [comment]
command does not work like this

**Comment by nsano-rururu** [comment]
Command alerts will be deprecated in the next version

**Comment by nsano-rururu** [comment]
Thank you for the field back

**Comment by nsano-rururu** [comment]
There are no plans to add features in the near future

**Comment by nsano-rururu** [comment]
Is it possible to erase the target code in the minor version? Will do so

**Comment by nsano-rururu** [comment]
I can't say anything because I feel that it is a specification of js-yaml

**Comment by nsano-rururu** [comment]
Anyone can complain. Make a pull request
