### ISSUE TITLE
Email Alert Error

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#278]
Hello, I get an error like the following in the system installed on ubuntu 20

Error while running alert email: Error connecting to SMTP host: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c: 1123)

My BaseRule.config settings
smtp_host: "mail.domain.com"
smtp_port: 587
smtp_auth_file: '/opt/praeco/smtp_auth_user.yaml'

**Comment by nsano-rururu** [comment]
Do you have a mail server installed and set up on ubuntu?

**Comment by nsano-rururu** [comment]
https://www.server-world.info/query?os=Ubuntu_20.04&p=mail&f=5

**Comment by nsano-rururu** [comment]
It seems that the mail server is set not to allow sending on port 587.

**Comment by ozgursuder** [comment]
We have a service provider outside and we receive mail service from there.

**Comment by ozgursuder** [comment]
no postfix

**Comment by nsano-rururu** [comment]
It seems that an error is returned from the mail server during the mail sending process of elastalert. Check with your provider to see if you can use the port you specify. Modification of elastalert is not supported.

**Comment by nsano-rururu** [comment]
> We have a service provider outside and we receive mail service from there.

There is no more information I can provide.

**Comment by nsano-rururu** [comment]
There is no particular support for praeco and elastalert server.

**Comment by nsano-rururu** [comment]
This information seems to be relevant
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1888101

**Comment by nsano-rururu** [comment]
There was information in the ElastAlert issue that a similar issue occurred on ubuntu 20 and the issue was resolved on ubuntu 18.

**Comment by nsano-rururu** [comment]
Perhaps it would be nice to modify ElastAlert as follows: The operation is unconfirmed, but ...

https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L467

before

```
        try:
            if self.smtp_ssl:
                if self.smtp_port:
                    self.smtp = SMTP_SSL(self.smtp_host, self.smtp_port, keyfile=self.smtp_key_file, certfile=self.smtp_cert_file)
                else:
                    self.smtp = SMTP_SSL(self.smtp_host, keyfile=self.smtp_key_file, certfile=self.smtp_cert_file)
            else:
                if self.smtp_port:
                    self.smtp = SMTP(self.smtp_host, self.smtp_port)
                else:
                    self.smtp = SMTP(self.smtp_host)
                self.smtp.ehlo()
                if self.smtp.has_extn('STARTTLS'):
                    self.smtp.starttls(keyfile=self.smtp_key_file, certfile=self.smtp_cert_file)
```

after

```
import ssl


        # Create a secure SSL context
        ssl_context = ssl.create_default_context()

        try:
            if self.smtp_ssl:
                if self.smtp_port:
                    self.smtp = SMTP_SSL(self.smtp_host, self.smtp_port, keyfile=self.smtp_key_file, certfile=self.smtp_cert_file, context=ssl_context)
                else:
                    self.smtp = SMTP_SSL(self.smtp_host, keyfile=self.smtp_key_file, certfile=self.smtp_cert_file, context=ssl_context)
            else:
                if self.smtp_port:
                    self.smtp = SMTP(self.smtp_host, self.smtp_port)
                else:
                    self.smtp = SMTP(self.smtp_host)
                self.smtp.ehlo()
                if self.smtp.has_extn('STARTTLS'):
                    self.smtp.starttls(keyfile=self.smtp_key_file, certfile=self.smtp_cert_file, context=ssl_context)
```

**Comment by ozgursuder** [comment]
What you said did not work with you

**Comment by nsano-rururu** [comment]
> What you said did not work with you

I'm not saying it will work.

**Comment by nsano-rururu** [comment]
I suspect it's an elastalert problem, but I don't have a solution

**Comment by nsano-rururu** [comment]
I think you should ask in the elastalert issue

**Comment by nsano-rururu** [comment]
I think you should look for a commercial product

**Comment by nsano-rururu** [comment]
You may not know if you haven't built a mail server, but there is a setting as to which version of ssl / tls is allowed or not.
In this case, it turns out that not only the mail server side but also the mail client side has a setting to allow or disallow the ssl / tls version. I learned a lot.
