### ISSUE TITLE
command help

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#284]
Hello there
I know that you will remove command support in version 1.6.0.

I have a small question for you as I need your command section for now.

As far as I can see, it reduces it to the next line after 76 characters.

command:
   -> -
     123456789 123456789 123456789 123456789 123456789 123456789 123456789
     123456789

   -> - I wonder if you have a limit number of words anywhere to avoid throwing this character. it beats this in 76 words as far as I have tested it.

thank you for your attention and help

**Comment by nsano-rururu** [comment]
The command will be erased this week. I will not implement the command function again. There is a possibility that it will be revived if there is a pull request. I don't know the question. When the command function was implemented, such processing was not included. Maybe it's a js-yaml specification or something I'm doing in practice

**Comment by nsano-rururu** [comment]
Do not use praeco when using the command function

**Comment by ozgursuder** [comment]
If you can tell which file it is in, I try to check it.

This feature is a feature that we use very actively. I'm very sorry that it wasn't in the next version.

I hope another alternative is found instead

**Comment by nsano-rururu** [comment]
If so, please remake the command function. Until then, leave the command function. We are waiting for a pull request

**Comment by nsano-rururu** [comment]
This is the history when I made a pull request for the command function. So I think you can follow which file the process is written in.
https://github.com/johnsusek/praeco/commit/7acf115408b7ec5d8c47dc475decb71cd720e1c3

**Comment by ozgursuder** [comment]
I wonder if there is a method that I can run a command like the following in praeco

curl -k "https://fw.xxx.com/webconsole/APIController?reqxml= <Request> <Login> <Username> user </Username> <Password> pass </Password> </Login> <Set>

**Comment by ozgursuder** [comment]
thanks for your time

**Comment by nsano-rururu** [comment]
look
https://github.com/Yelp/elastalert/issues/592

**Comment by ozgursuder** [comment]
I run this command on elastalert without any problem.

Frankly, my aim was to be able to use the praeco.

I guess I cannot use it actively.

you were already uninstalling it in version 1.6.

I hope the 76 characters problem is solved in future versions and it will be used again and I can start using it.

Or a webbook alternative comes up that I can use the curl command. :)

Thank you for your support.

I will wait for the version you will release after version 1.6.

Good luck with

**Comment by nsano-rururu** [comment]
all right. I will erase the command at 1.6 as planned

**Comment by nsano-rururu** [comment]
Do not use praeco

**Comment by nsano-rururu** [comment]
goodbye

**Comment by nsano-rururu** [comment]
Probably the command function is unlikely to be restored. Very few people make pull requests to Praeco

**Comment by nsano-rururu** [comment]
It is a specification of js-yaml of the library

>lineWidth (default: 80) - set max line width.
https://www.npmjs.com/package/js-yaml

**Comment by nsano-rururu** [comment]
It seems that you have misunderstood, but there are various output formats as yaml specifications. So I'm not wrong. It is only self-satisfaction that imposes on self-satisfaction that everything that you think is right is correct.

**Comment by nsano-rururu** [comment]
I can't say for sure without investigating js-yaml, but since yaml seems to have different types, there may be an option to output in the same format as ElastAlert.
