### ISSUE TITLE
[Question] - Is there a way to have a different webhook per rule created for slack?

### ISSUE THREAD

**Issue by pachev** [johnsusek/praeco#286]
Unfortunately, Slack does not allow one webhook to post to multiple channels. I want the alerts for my Staging/Production environments to go to different channels. As it stands, the only place I can put `slack_webhook_url` option is in the `BaseRule.config`. Even If I edit the rule manually, and look at the yaml from the UI, it does not display the `slack_webhook_url` option as part of the rule.

**Comment by pachev** [comment]
I created a Bot and added an Incoming Webhook instead of adding the `incoming-webhook` integration. This was an error on my part.

**Comment by nsano-rururu** [comment]
Originally a sponsor company? Since it was implemented for, it seems that the implementation of slack is like that so far at the request at that time.
