### ISSUE TITLE
How to do any filter, can i add black list  txt

### ISSUE THREAD

**Issue by shakomako-hibo** [johnsusek/praeco#295]
is there an any filter in praeco

can we put black list txt file in elast rule folder and will it work

**Comment by nsano-rururu** [comment]
Isn't it a good idea to give it a try? Why are you asking a question before trying? I do not understand the meaning.

**Comment by nsano-rururu** [comment]
It is not supported, so please support it. First of all, please tell me the result of trying.

**Comment by shakomako-hibo** [comment]
black list didn't work with a .txt file, it does not give any errors, it just doesn't work
i think it considers the '!file absolutepath/blacklist1' as a text to be recognized

**Comment by nsano-rururu** [comment]
Currently, there is no choice but to directly enter the value described in the file.

**Comment by nsano-rururu** [comment]
@shakomako-hibo

I found that the default setting for js-yaml was single quotes. We will change the yaml output settings in the next release, 1.6.0. Single to double quotes.

**Comment by nsano-rururu** [comment]
@shakomako-hibo

Changed to an option setting that forces enclosing with double coating. The elastalert server has also changed a lot, so please use new ones for both.
https://hub.docker.com/r/praecoapp/praeco
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by nsano-rururu** [comment]
It does not respond, so close it.
