### ISSUE TITLE
question about rule_templates

### ISSUE THREAD

**Issue by priamai** [johnsusek/praeco#299]
Hi there,
this is not issue but just a question to help me understand.
The folder rule_templates is both present in /opt/elastalert and /opt/elastalert-server (depending on the path configuration of course) and I noticed that the template files should be duplicated in both folders to be able to work from the praeco web interface.

I would like to understand how the templates are created in both folders, right know I just copy my templates on both but not sure whether this is the right approach.

Cheers.

**Comment by nsano-rururu** [comment]
I'm eating supper, so wait a minute

**Comment by nsano-rururu** [comment]
Do you understand the directory on the container side and the physical directory on the Docker host side?
/ opt / elastalert and / opt / elastlaert-server are directories on the Docker container side.
You created and mounted a template folder with docker-compose (./praeco/rule_templates:/opt/elastalert/rule_templates). I should put the template file there (./praeco/rule_templates).
In the config.json directory, specify "/ opt / elastalert" by default.

**Comment by priamai** [comment]
Thanks yes makes sense.
