### ISSUE TITLE
correlate with praeco.

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#300]
Hello there

I wonder if we have a chance to correlate with praeco.

**Comment by nsano-rururu** [comment]
what?

**Comment by nsano-rururu** [comment]
Function addition?

**Comment by nsano-rururu** [comment]
Currently, Praeco doesn't support all the features of ElastAlert, so I think it's normal to not use Praeco in some situations.
I used ElastAlert Server, ElastAlsert Kibana Plugin in a real case

**Comment by nsano-rururu** [comment]
I don't want you to use Praeco absolutely. At all

**Comment by nsano-rururu** [comment]
ElastAlert is not currently maintained and is not recommended.

**Comment by nsano-rururu** [comment]
OSS is not obliged to make requests or fix bugs. Taking ElastAlert as an example, I made 30 pull requests, but they are closed without being captured.

**Comment by nsano-rururu** [comment]
Will you rampage if you don't do what you want? It's different. Some people use it by forking and modifying it. Normally. This is especially true for Praeco and ElastAlertServer. Function addition, bug fix
Even if the library is updated. You can't force it to use the formula.

**Comment by nsano-rururu** [comment]
https://www.npmjs.com/package/js-yaml

**Comment by nsano-rururu** [comment]
Isn't it faster to make a new tool?

**Comment by nsano-rururu** [comment]
Basically, I don't intend to respond only to requests. Please correct and make a pull request.

**Comment by nsano-rururu** [comment]
If you can develop it, please participate in the development, and if it is impossible, you are free to make suggestions. However, I have never used the programming languages ​​used by praeco, elastalertserver, and elastalert at work, so it takes time to find out how to implement them.
