### ISSUE TITLE
praeco ignore smtp_host setting in rule, and lost when rule will saved

### ISSUE THREAD

**Issue by tantra35** [johnsusek/praeco#302]
When in rule definde `smtp_host`, praeco ignore this and lost if we save rule

**Comment by nsano-rururu** [comment]
Currently, smtp_host cannot be set on the screen, so write it in BaseRule.config.
Did you directly edit the file that was set and output on the screen? .. It does not support. We do not recommend using Praeco for such purposes.
https://github.com/johnsusek/praeco#how-to-setup-email

**Comment by nsano-rururu** [comment]
If you want a tool to edit on the web screen, use elastalert-kibana-plugin.

**Comment by nsano-rururu** [comment]
Currently, it does not support both editing on the web screen and file output after output.
The rules file is overwritten with the contents set at the time of initial display and saving by reading the settings supported at the time of screen display. Therefore, the setting may have disappeared.
This is the current specification.

**Comment by tantra35** [comment]
@nsano-rururu We use both tools: kibana plugin + for turning and visualize control praeco. And we doesn't need editing `smt_host` in praeco, but want to correct rules from praeco, and found such strange behavior

**Comment by nsano-rururu** [comment]
@tantra35

It is a specification.

**Comment by nsano-rururu** [comment]
I found that I couldn't understand each other even if I explained it. Please do it yourself.

**Comment by tantra35** [comment]
@nsano-rururu i think that a best solution is left all fields in yaml, despite praeco allow edit them throw GUI or not. Ok it can't edit, but fields must not disappear from yaml, its unexpected

I think that this simple patch can solve problem
```patch
 src/store/config/index.js    | 5 +++++
 src/store/config/settings.js | 4 ++++
 2 files changed, 9 insertions(+)

diff --git a/src/store/config/index.js b/src/store/config/index.js
index 86668f2..471a81a 100644
--- a/src/store/config/index.js
+++ b/src/store/config/index.js
@@ -85,6 +85,7 @@ export default {
         commit('settings/UPDATE_NAME', config.name);
         commit('settings/UPDATE_DESCRIPTION', config.description);
         commit('settings/UPDATE_INDEX', config.index);
+        commit('settings/UPDATE_SMTP_HOST', config.smtp_host);
 
         // If is_enabled is not in the config, the rule is in fact enabled
         if (config.is_enabled === undefined || config.is_enabled) {
@@ -1145,6 +1146,10 @@ export default {
         config.index = state.settings.index;
       }
 
+      if (state.settings.smtp_host) {
+        config.smtp_host = state.settings.smtp_host
+      }
+
       if (state.settings.timeField) {
         config.timestamp_field = state.settings.timeField;
       }
diff --git a/src/store/config/settings.js b/src/store/config/settings.js
index 0785b93..b16465e 100644
--- a/src/store/config/settings.js
+++ b/src/store/config/settings.js
@@ -52,6 +52,10 @@ export default {
       state.index = index;
     },
 
+    UPDATE_SMTP_HOST(state, smtp_host) {
+      state.smtp_host = smtp_host;
+    },
+
     UPDATE_TIME_FIELD(state, timeField) {
       state.timeField = timeField;
     },
```

**Comment by nsano-rururu** [comment]
It's not just there. that's enough. all right. I should be able to set it on the screen.

**Comment by nsano-rururu** [comment]
I understand that I didn't read my comment.

**Comment by tantra35** [comment]
Hm i thinked that praeco GUI load full yaml, then edit fields that it allow, but not construct yaml from zero every time when rule editing

**Comment by nsano-rururu** [comment]
@tantra35

Insistent. I know.

**Comment by nsano-rururu** [comment]
@tantra35

You don't have to comment anymore. Let's stop.

**Comment by nsano-rururu** [comment]
@tantra35

goodbye. Praeco will not be changed in this matter.

**Comment by nsano-rururu** [comment]
@tantra35 

If you are editing only the target part, will the additional part disappear directly?

**Comment by nsano-rururu** [comment]
It is different from the content of the question. Don't comment. ask

**Comment by nsano-rururu** [comment]
Praeco will not be changed

**Comment by nsano-rururu** [comment]
Do not use elastalert-kibana-plugin and praeco at the same time

**Comment by nsano-rururu** [comment]
Items that cannot be set on the screen are shared by all rules even if they are set in BaseRule.config, so write them there.

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/blob/master/src/store/config/index.js#L1290

```
      Object.keys(config)
        .sort()
        .forEach(v => {
          conf[v] = config[v];
        });

      return conf;
    },

    yaml: (state, getters) => forTest => yaml.safeDump(getters.config(forTest))
  }
};
```

**Comment by nsano-rururu** [comment]
I know that when editing, the set contents are read and initially displayed.

**Comment by nsano-rururu** [comment]
This proposal does not correspond. I know if you make a pull request to be able to set it on the screen.
