### ISSUE TITLE
Unsupported URL Type: npm:@elastic/elasticsearch@^5.6.22

### ISSUE THREAD

**Issue by ghlilou97** [johnsusek/praeco#303]
Hello i got this error when i  execute npm install : 

npm ERR! Linux 3.10.0-1160.11.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: npm:@elastic/elasticsearch@^5.6.22
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/elastalert-server/config/npm-debug.log 

Can someone help please !
 King regards

**Comment by nsano-rururu** [comment]
I have confirmed the operation with npm install with the following versions. Will I get an error even with the same version? We can't support very old ones. I want to isolate the problem, so I would like to know if the following versions will not improve.
Also, does this work to start ElastAlert Server directly instead of docker? Basically, it is supposed to be run by docker.

Node.js 14.15.0
npm 7.2.0

**Comment by nsano-rururu** [comment]
What Linux is Linux 3.10.0-1160.11.1.el7.x86_64? CentOS 7?

**Comment by ghlilou97** [comment]
> What Linux is Linux 3.10.0-1160.11.1.el7.x86_64? CentOS 7?

Yes is Centos 7 , it's manually installed without docker.

**Comment by ghlilou97** [comment]
What Linux is Linux 3.10.0-1160.11.1.el7.x86_64? CentOS 7?

Yes is Centos 7 , it's manually installed without docker.

**Comment by nsano-rururu** [comment]
What version of Elasticsearch?
Is Elasticsearch running?
If you don't want to upgrade the version of Node.js and npm, please use it with docker. I don't think it works fine with old npm and Node.js.
What are the settings for ElastAlert and ElastAlertServer?

As expected, it cannot be understood only by an error. I'm not Esper

**Comment by nsano-rururu** [comment]
I also answered the issue of bitsensor, but I have never done direct installation, so I can only think about the cause together.

**Comment by ghlilou97** [comment]
I've done the update, i think it will work i just need to know wich file need to  be modified to put the Elastalert-server Ip  on it.

Thanks for helping.
Best Regards

**Comment by nsano-rururu** [comment]
If you get an error, please feel free to ask. Let's think about the cause and countermeasures together.

**Comment by ghlilou97** [comment]
How to change ip of elastalert-server from localhost to x.x.x.x on manually installation
Thanks for helping

**Comment by nsano-rururu** [comment]
look

https://github.com/johnsusek/praeco#architecture-details

Because ElastAlertAPI = ElastAlertServer (ports use 3030 and 3333). Well, that's right. ElastAlert and ElastAlertServer should be in the same environment. Elasticsearch can be on another server. For that reason, there are settings in the config file that start with es_host or es_xxx etc.
https://github.com/johnsusek/elastalert-server#configuration

api.config.json is the ElastAlertServer configuration file. elastalert.yaml will be the ElastAlert configuration file.
https://github.com/johnsusek/praeco/tree/master/config
api.config.json
elastalert.yaml

**Comment by ghlilou97** [comment]
Thanks for your help i got other error when i try to "npm start" 

ERROR elastalert-server:
    Config:  The config in 'config/config.json' is not a valid config configuration. Error:  SyntaxError: Unexpected string in JSON at position 533
        at JSON.parse (<anonymous>)
        at ServerConfig._validate (/home/elastalert-server/src/common/config/server_config.js:158:47)
---------------------------------------------------------------------------------------------------------------------------------------------
 ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/lib/python3.6/site-packages/elastalert/create_index.py", line 268, in <module>
        main()
      File "/usr/local/lib/python3.6/site-packages/elastalert/create_index.py", line 215, in main
        host = args.host if args.host else input('Enter Elasticsearch host: ')
    EOFError: EOF when reading a line
--------------------------------------------------------------------------------------------------------------------------------------------
 ERROR elastalert-server: ProcessController:  Index create exited with code 1
--------------------------------------------------------------------------------------------------------------------------------------------ERROR elastalert-server:
    Server:  Starting server failed with error: TypeError: Cannot read property 'relative' of undefined
        at RulesController._getRulesFolder (/home/elastalert-server/src/controllers/rules/index.js:171:28)
        at new RulesController (/home/elastalert-server/src/controllers/rules/index.js:19:29)
        at callback (/home/elastalert-server/src/elastalert_server.js:95:33)
        at forEach (/home/elastalert-server/src/common/config/server_config.js:59:9)
        at Array.forEach (<anonymous>)
        at /home/elastalert-server/src/common/config/server_config.js:58:22
----------------------------------------------------------------------------------------------------------
config.json : 

  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/home/admin/elastalert",
  "verbose": true,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": false,
    "path": "/home/admin/elastalert/my_rules"

  },
  "templatesPath": {
    "relative": false,
    "path": "/home/elastalert-server/rule_templates"
  },
  "es_host": "node1",
  "es_port": 9200,
  "es_username": "xxxxxxxxxx",
  "es_password": "xxxxxx",
  "es_ca_certs": "/home/elastalert-server/xx/ca.crt"
  "es_ssl": true,
  "writeback_index": "elastalert_status"
}
-------------------------------------------------------------------------------------------------------------------------------------------
es_host: node1
es_port: 9200
rules_folder: rules
run_every:
  seconds: 5
buffer_time:
  minutes: 1
verify_certs: True
ca_certs: /home/elastalert-server/xxxx/ca.crt
es_username: xxxxx
es_password: xxxxxxxxxxxxxxx
writeback_index: elastalert_status
alert_time_limit:
  days: 2

skip_invalid: True



Thanks for your help 
Best Regards

**Comment by nsano-rururu** [comment]
You can see that something is wrong with the description in the configuration file. I haven't seen it so I don't know. Is elasticsearch another host? .. Did you change the IP address of the specified value? I don't know if I can take care of it

**Comment by nsano-rururu** [comment]
I've never seen a straight-line installation working properly before

**Comment by nsano-rururu** [comment]
At the time of json parsing, something is strange. Because it is a syntax error. json

**Comment by nsano-rururu** [comment]
The exact same environment may be unpleasant, but we plan to create an environment and investigate the case of direct installation. However, since I work differently during the day, I can't promise how long it will take because I'll cut down on my private time and deal with it little by little. I want you to understand only that

**Comment by ghlilou97** [comment]
Hello, thanks but i think i resolved the problem it was just comma "," missing after es_ca_certs line !

Best Regards

**Comment by harsxv** [comment]
Hi @ghlilou97 could you please provide some details about the missing comma? 
Where is the syntax error on this? Thanks.

**Comment by nsano-rururu** [comment]
@harsxv 

"es_ca_certs": I just forgot to write the comma after "/home/elastalert-server/xx/ca.crt"

```
# NG
"es_ca_certs": "/home/elastalert-server/xx/ca.crt"

# OK
"es_ca_certs": "/home/elastalert-server/xx/ca.crt",
```
