### ISSUE TITLE
Error creating rule 

### ISSUE THREAD

**Issue by ghlilou97** [johnsusek/praeco#304]
Hello i got this error when i try to create rules : 

TypeError: _lib_logger_js__WEBPACK_IMPORTED_MODULE_27__.logger.error is not a function

How can we use hivealerter on praeco i tried with field command but i'm not sure.

Thanks for helping 
Best regards.

**Comment by nsano-rururu** [comment]
praeco does not yet support hivealerter. Sometimes I don't know how to create a hivealerter environment ...
Although unofficial, there is information on running hivealerter on Praeco at the following site.
https://medium.com/@ibrahim.ayadhi/hello-and-welcome-to-our-new-article-which-will-be-covering-the-alerting-part-in-our-socaas-136cf6258c49

**Comment by nsano-rururu** [comment]
I want to know where the error occurred, so how to reproduce it and where did I see it (browser developer tools?)

>TypeError: lib_logger_js__WEBPACK_IMPORTED_MODULE_27_.logger.error is not a function

**Comment by ghlilou97** [comment]
The error happen when we  click on Save button, after filling all fields, we see it directly on browser i will take a screenshot ASAP 

Thanks for helping 
Best Regards

**Comment by nsano-rururu** [comment]
Are you running "chmod -R 777" in the rules directory and the rule template directory? .. If you don't run it, you will certainly get an error.

example

```
mkdir -p rules rule_templates
chmod -R 777 rules rule_templates
```

**Comment by nsano-rururu** [comment]
@ghlilou97
What happened after that?
