### ISSUE TITLE
Configured rule retrieves 0 hits from elastic search[7.9.x] in Praeco WEB UI

### ISSUE THREAD

**Issue by SRAM85** [johnsusek/praeco#307]
Praeco server and webUI are setup.

Rule creation displays the time series data based on the filter over the index and the threshold that were setup

![Screen Shot 2021-02-01 at 8 08 41 PM](https://user-images.githubusercontent.com/26207701/106551123-6293f580-64c9-11eb-9353-31c9e28a4a0b.png)
![Screen Shot 2021-02-01 at 8 07 48 PM](https://user-images.githubusercontent.com/26207701/106551393-febdfc80-64c9-11eb-8fe5-dcb76d7f31c6.png)

The rule ends up with 0 hits. 

My ES cluster version is 7.9.X.

Any insight as to what could be the problem will be of great help

**Comment by nsano-rururu** [comment]
I will ask a question on the assumption that it is running on docker.

- Is there anything in the elastalert-server docker container log?
- Do you see javascript errors in the console of your web browser developer tools?

**Comment by nsano-rururu** [comment]
Please re-open this issue with your yaml file if you suspect this is a praeco issue, not an elastalert issue. Praeco simply creates elastalert rules, so if alerting isn't working, we need to at least see the yaml file and figure out if this is a bug with elastalert or praeco.

Please see this section of the README:

I'm not receiving alerts even though I expect them
First of all, try to test your alert with varying time frames and see if that is returning any results.

If the test is returning results, but you are not receiving any alerts, check the error log. There may be a problem with your alerter settings. Make sure you edited rules/BaseRule.config and have correct values in there.

If the test is not returning results, even though you think it should, try reading the elastalert docs for your rule type. Compare the yaml from praeco with the options from the docs to make sure the rule is being created as expected. If praeco is generating the wrong yaml, please file an issue.
