### ISSUE TITLE
Rules does not work

### ISSUE THREAD

**Issue by Makss39** [johnsusek/praeco#309]
Hi,

I tried to configure a rule based on windows event code (2013) but i can't make it work...
![image](https://user-images.githubusercontent.com/61969235/106919882-d40eb680-670a-11eb-8dd0-f58e361e4d78.png)

Here is the gnerated code:
![image](https://user-images.githubusercontent.com/61969235/106920140-146e3480-670b-11eb-9d1f-80f3f6a4a632.png)

When i run a test, it found nothing:
![image](https://user-images.githubusercontent.com/61969235/106919710-acb7e980-670a-11eb-8c96-15909a7fcdd8.png)

But events are in Elastic
![image](https://user-images.githubusercontent.com/61969235/106919406-695d7b00-670a-11eb-904d-a74bd06db2ee.png)

Any idea about what i've done wrong ?

Thanks again for helping !

**Comment by nsano-rururu** [comment]
I have never used blacklist.
I will ask a question on the assumption that it is running on docker.

- Is there anything in the elastalert-server docker container log?
- Do you see javascript errors in the console of your web browser developer tools?

**Comment by nsano-rururu** [comment]
What is the version of Elasticsearch and kibana?

**Comment by nsano-rururu** [comment]
What is the "sbl" specified in command? Is it something that can be run from the docker container of elastalert-server?

**Comment by nsano-rururu** [comment]
Is there any error when you click "Errors" in the red frame?
![キャプチャ](https://user-images.githubusercontent.com/22293449/106966775-5473fc80-6789-11eb-8286-8ff4265e4310.PNG)

**Comment by nsano-rururu** [comment]
Is the display in the red frame the same?
![キャプチャ](https://user-images.githubusercontent.com/22293449/106966936-99982e80-6789-11eb-8883-2e4886b05601.PNG)

**Comment by nsano-rururu** [comment]
What happens to the screen capture in the red frame on the "Overview" tab?
![キャプチャ](https://user-images.githubusercontent.com/22293449/106967127-f3005d80-6789-11eb-8156-fa252580dc43.PNG)

**Comment by nsano-rururu** [comment]
What happens to the screen capture at the red frame on the "Alert log" tab?
![キャプチャ](https://user-images.githubusercontent.com/22293449/106967249-33f87200-678a-11eb-93c5-bb8cf5de5b34.PNG)

**Comment by nsano-rururu** [comment]
What happens to the screen capture in the red frame on the "Query log" tab?
![キャプチャ](https://user-images.githubusercontent.com/22293449/106967411-77eb7700-678a-11eb-9739-c1ca2de2d32d.PNG)

**Comment by nsano-rururu** [comment]
If you don't get an error, I think the rule settings you specified in praeco can't detect the data you're expecting. In that case, you should try a setting other than blacklist.

**Comment by Makss39** [comment]
Nothing special on the Overview tab:
![image](https://user-images.githubusercontent.com/61969235/107002881-2c39cd00-678c-11eb-817c-8e81108b4e7e.png)
"sbl" is just a fake command, the first goal is to make praeco trigerring event first...

And you, you are right, praeco doesn't detect the data, but it should !!! The term is present on my data, so that is the point...
Notice that if I try a rule with an event count, it works:
![image](https://user-images.githubusercontent.com/61969235/107003266-c863d400-678c-11eb-96f3-e543a6e22f7c.png)

My ELK stack is 7.10, and everything is fine on praeco side:
![image](https://user-images.githubusercontent.com/61969235/107004016-f1d12f80-678d-11eb-971f-89559577eea1.png)

**Comment by nsano-rururu** [comment]
Ummm. I'm not free. Are you angry? .. Don't use fake commands. really. Please set slack, telegram, ms teams, email, etc. as notification destinations.

**Comment by Makss39** [comment]
Of course i'm not !!! I just want to make it works, and help others if they are facing the same situation :-)
OK, i'll set up email and then come back !

**Comment by nsano-rururu** [comment]
If you use email, please see past issues.
https://github.com/johnsusek/praeco/issues/245

Please note that setting smtp.gmail.com in gmail to smtp_host does not work well with elastalert implementation issues, and setting smtp.office365.com in office365 to smtp_host does not work at all.
It's out of my control as I need to review the python elastalert email alert implementation.

**Comment by Makss39** [comment]
Thanks for the info, it's planned to use an internal Exchange server... Hopefully I'll have time to do it today.
I keep you posted.

**Comment by Makss39** [comment]
Here is the error when I try to connect my exchange server:
![image](https://user-images.githubusercontent.com/61969235/107023434-ee966d80-67a6-11eb-8b4e-faba5a73482f.png)


I know nothing from python, but if it can help, the SSL version installed:
![image](https://user-images.githubusercontent.com/61969235/107023387-d7578000-67a6-11eb-9497-27d9333be8aa.png)

My server support SSL3
![image](https://user-images.githubusercontent.com/61969235/107024290-26ea7b80-67a8-11eb-87f4-0085d0e4591f.png)

**Comment by nsano-rururu** [comment]
What? .. Isn't it docker?

**Comment by nsano-rururu** [comment]
elastalert doesn't work in python2. python3.6, 3.7, 3.8.3.9 does not work properly.

**Comment by nsano-rururu** [comment]
- Packages on Ubuntu 18.x: build-essential python3-pip python3.6 python3.6-dev libffi-dev libssl-dev
- Packages on Ubuntu 20.x: build-essential python3-pip python3.6 python3.6-dev libffi-dev libssl-dev
- Packages on CentOS 7.x: 'Development Tools' python3-pip python36 python3-devel python3-libs python3-setuptools libffi-devel openssl-devel
- Packages on CentOS 8.x: 'Development Tools' python3-pip python36 python3-devel python3-setuptools python3-libs libffi-devel openssl-devel

**Comment by nsano-rururu** [comment]
Using python3 and virtalenv

**Comment by Makss39** [comment]
Sorry, same error in the elastalert docker:
![image](https://user-images.githubusercontent.com/61969235/107026483-0e2f9500-67ab-11eb-9226-deb2a7beee8a.png)

**Comment by nsano-rururu** [comment]
Isn't it necessary to install something additionally based on the docker image of praecoapp / elastalert-server: latest?
The following is a sample when the snmp-trap software is installed.


example Dockerfile

```
FROM praecoapp/elastalert-server:latest

USER root

# add net-snmp net-snmp-tools
RUN apk add --update --no-cache net-snmp net-snmp-tools

USER node
```

**Comment by nsano-rururu** [comment]
If you ask google about the creation of docker image, various information should come out.

**Comment by nsano-rururu** [comment]
Maybe add this. I don't know

```
RUN apk upgrade --update-cache --available && \
    apk add openssl && \
    rm -rf /var/cache/apk/*
```

**Comment by nsano-rururu** [comment]
@Makss39 

not python. python3 command

**Comment by nsano-rururu** [comment]
Python 2.7 is called for Python commands. python3.8 should work when I run the python3 command

**Comment by nsano-rururu** [comment]
There is a serious vulnerability in the SSLv3.0 protocol. I don't know if information leaks

**Comment by nsano-rururu** [comment]
I should have been able to set which ssl / tls version is supported in the mail server settings. I've done it with postfix, so other mail servers should have such settings.

**Comment by nsano-rururu** [comment]
look
https://qiita.com/oooooo1693/items/ee825fb664fb6f18e202

**Comment by nsano-rururu** [comment]
You need to create a docker image based on the docker image of elastalert-server. There is no other solution.

**Comment by nsano-rururu** [comment]
I'm also an experience, so I'm not sure if it will work.

**Comment by nsano-rururu** [comment]
I'm not an infrastructure engineer

**Comment by Makss39** [comment]
Sorry, pretty busy... Just misunderstood the rresult of the tst command. SSL3 is not enabled on the server side, si it means that it's openSSL which is trying to connect using it instead of TLS... I'll dig...

**Comment by nsano-rururu** [comment]
openssl コマンドで SSL/TLS バージョンを指定した HTTPS 接続テストを実施する
https://sig9.hatenablog.com/entry/2016/07/03/230000

**Comment by Makss39** [comment]
Well after testing it works by specifying "-starttls smtp"

![image](https://user-images.githubusercontent.com/61969235/107050766-e7ce2180-67cb-11eb-942e-b62c67ff17ba.png)

**Comment by Makss39** [comment]
But still not working in Praeco. Is there any way to force  it ?

**Comment by nsano-rururu** [comment]
https://elastalert.readthedocs.io/en/latest/ruletypes.html#email
>smtp_ssl: Connect the SMTP host using TLS, defaults to false. If smtp_ssl is not used, ElastAlert will still attempt STARTTLS.

**Comment by nsano-rururu** [comment]
I don't know what kind of settings each docker is running, so I can't comment. I'm not Esper

**Comment by Makss39** [comment]
I've other errors due to authentication... I'll fix it, and then try to find why "blacklist" is not working.
BTW, thanks for your support

**Comment by nsano-rururu** [comment]
Isn't it better to use it because it's not a blacklist?

**Comment by nsano-rururu** [comment]
If you want to specify "smtp_ssl: true", write it in BaseRule.config.

example
#245

**Comment by nsano-rururu** [comment]
>why "blacklist" is not working.

Praeco simply creates [elastalert](https://github.com/Yelp/elastalert) rules, so if alerting isn't working, we need to at least see the yaml file and figure out if this is a bug with [elastalert](https://github.com/Yelp/elastalert) or praeco or elastalert-server.

Please see this section of the README:

I'm not receiving alerts even though I expect them
First of all, try to test your alert with varying time frames and see if that is returning any results.

If the test is returning results, but you are not receiving any alerts, check the error log. There may be a problem with your alerter settings. Make sure you edited rules/BaseRule.config and have correct values in there.

If the test is not returning results, even though you think it should, try reading the [elastalert docs](https://elastalert.readthedocs.io/en/latest/) for your rule type. Compare the yaml from praeco with the options from the docs to make sure the rule is being created as expected. If praeco is generating the wrong yaml, please file an issue.

**Comment by nsano-rururu** [comment]
https://elastalert.readthedocs.io/en/latest/ruletypes.html#blacklist

**Comment by Makss39** [comment]
Hi, it's not an error about receiving or not the alert. It's just not detected. Here is the YAML generated by praeco:
![image](https://user-images.githubusercontent.com/61969235/107193917-afa72880-69ef-11eb-8a6c-5b492d7ff78d.png)

I don't know if there is an impact, but all the example tha i've found on the www, there are double quote around the blacklist term, and in the generatel yaml it's simple quote... If i've time today, i'll run more tests.

**Comment by nsano-rururu** [comment]
>I don't know if there is an impact, but all the example tha i've found on the www, there are double quote around the blacklist term, and in the generatel yaml it's simple quote... If i've time today, i'll run more tests.

It has the same meaning in both cases.

**Comment by nsano-rururu** [comment]
>Hi, it's not an error about receiving or not the alert. It's just not detected. Here is the YAML generated by praeco:

If there are no errors, it is a problem on the Elast Alert side. There is nothing Praeco can do for you.

**Comment by Makss39** [comment]
Well, i gave a try on a text field, here is the generated YAML (no quotes), and it works.
![image](https://user-images.githubusercontent.com/61969235/107196273-b6836a80-69f2-11eb-959c-a9ecc32577c8.png)

**Comment by nsano-rururu** [comment]
>Well, i gave a try on a text field, here is the generated YAML (no quotes), and it works.

text field? .. I don't know what it is. I used to say that I had never used blacklist. At first. Why are you trying to do such a rough exchange?

**Comment by Makss39** [comment]
Sorry, but I just think that the YAML file is not generated correctly by "Praeco".

When I test a blacklist with a non numeric string (eg: error) it's detected by elastalert and it works. But when I try with a numeric (eg: 2013) it's not detected by elastalert.
Also in the first case, it doesn't add quotes in the config file, and it does for the second.

No quotes:
![image](https://user-images.githubusercontent.com/61969235/107197275-fac33a80-69f3-11eb-9948-3b4b33ab1b08.png)

Quotes:
![image](https://user-images.githubusercontent.com/61969235/107197322-07e02980-69f4-11eb-998e-14b9793cca3f.png)

**Comment by nsano-rururu** [comment]
>When I test a blacklist with a non numeric string (eg: error) it's detected by elastalert and it works. But when I try with a numeric (eg: 2013) it's not detected by elastalert.
Also in the first case, it doesn't add quotes in the config file, and it does for the second.

In that case, the blacklist is modified so that it is output so that it is not enclosed in single quotes? .. I think whitelist has the same problem, but ...

By the way, in ElastAlert's schema.yaml, the data type is a character.
https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml#L57

```
  - title: Blacklist
    required: [blacklist, compare_key]
    properties:
      type: {enum: [blacklist]}
      compare_key: {'items': {'type': 'string'},'type': ['string', 'array']}
      blacklist: {type: array, items: {type: string}}
```

**Comment by nsano-rururu** [comment]
I think it is better not to use blacklist and whitelist in praeco. What is the current situation? I don't know if the bug can be fixed soon ..

**Comment by nsano-rururu** [comment]
Or stop adopting Praeco. ElastAlertServer only. Edit yaml with an editor.

**Comment by Makss39** [comment]
I will run more tests later in the day to figure out what can be done or not.
If I modify directly the yaml file in elastalert docker, does praeco will use it ?

**Comment by nsano-rururu** [comment]
>I will run more tests later in the day to figure out what can be done or not.
If I modify directly the yaml file in elastalert docker, does praeco will use it ?

To use. However, if you press the "Save" button, it will be overwritten and restored, so you will need to open the file again and edit it. The same applies when you make changes to any rule (for example, invalidate the rule).

**Comment by Makss39** [comment]
I was not able to find any way to make "blacklist" works with a numeric comparsion.

I finally used a workaroud: filtering on the event code and then detect a new term in another field (winlog.record_id). That is doing the job.
![image](https://user-images.githubusercontent.com/61969235/107223192-29eaa380-6a16-11eb-9523-3b527f29b3a7.png)

Thks again @nsano-rururu for helping !
