### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tarekkilani** [johnsusek/praeco#310]
Hello, 

Please i'm using Elastalert and i found out that i can have a GUI for managing elasticsearch alerts if i use Praeco.
So i followed this tutorial to install all the dependencies (Elastalert-server and Praeco) : 

https://medium.com/@ibrahim.ayadhi/hello-and-welcome-to-our-new-article-which-will-be-covering-the-alerting-part-in-our-socaas-136cf6258c49

But when i try to run elastaslert-server i get this : 

`10:10:16.209Z  INFO elastalert-server: Server:  Server started
14:53:04.907Z ERROR elastalert-server:
    ProcessController:  /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
      RequestsDependencyWarning)
    WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_pending_alerts (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:45.361848
    WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_config_change (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:46.195447
    
14:53:19.335Z ERROR elastalert-server:
    ProcessController:  WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_pending_alerts (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:02.342854
    
14:53:19.335Z ERROR elastalert-server:
    ProcessController:  WARNING:apscheduler.executors.default:Run time of job "ElastAlerter.handle_config_change (trigger: interval[0:01:00], next run at: 2021-02-04 15:53:16 CET)" was missed by 0:00:02.343774
`

I don't know if these errors are critical or not! is elastalert working or not?
Also, When i isntall Praeco using npm i get this (Please note that i'm using node 13 and npm 6) :  

`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> nodent-runtime@3.2.1 install /opt/praeco/node_modules/nodent-runtime
> node build.js

internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/praeco/node_modules/nodent-runtime/dist/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1375:35)
    at Object.<anonymous> (/opt/praeco/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/praeco/node_modules/nodent-runtime/dist/index.js'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/mochapack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodent-runtime@3.2.1 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodent-runtime@3.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/elk/.npm/_logs/2021-02-05T07_44_09_596Z-debug.log
`

Please find attached the debug.log file
[debug.txt](https://github.com/johnsusek/praeco/files/5930888/debug.txt)

**Comment by nsano-rururu** [comment]
Direct installation is not supported.

**Comment by tarekkilani** [comment]
Please how can i install it without getting these errors?

**Comment by nsano-rururu** [comment]
I have confirmed the operation with npm install with the following versions. Will I get an error even with the same version? We can't support very old ones. I want to isolate the problem, so I would like to know if the following versions will not improve.


Node.js 14.15.0
npm 7.2.0

**Comment by nsano-rururu** [comment]
Upgrade npm and node.js versions

**Comment by nsano-rururu** [comment]
```
# nvm install
# https://github.com/nvm-sh/nvm#install--update-script
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
$ vi ~/.bash_profile

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

$ source ~/.bash_profile

$ npm install -g npm@7.2.0
$ nvm install 14.15.0
$ nvm use 14.15.0
```

**Comment by nsano-rururu** [comment]
Also, the information on the following sites is not official information. Because i don't know
https://medium.com/@ibrahim.ayadhi/hello-and-welcome-to-our-new-article-which-will-be-covering-the-alerting-part-in-our-socaas-136cf6258c49

**Comment by tarekkilani** [comment]
If i'm going to use the docker container for praeco, will i need to install elastalert and elastalert first?

**Comment by nsano-rururu** [comment]
Please refer to the docker-compose description I wrote in the comment of the issue I answered in the past.
https://github.com/johnsusek/praeco/issues/254#issuecomment-703104530

**Comment by tarekkilani** [comment]
> I have confirmed the operation with npm install with the following versions. Will I get an error even with the same version? We can't support very old ones. I want to isolate the problem, so I would like to know if the following versions will not improve.
> 
> Node.js 14.15.0
> npm 7.2.0

This resolved the problem. Thank you so much

**Comment by nsano-rururu** [comment]
@tarekkilani

I had forgotten to say it.
When using with direct installation, zabbix, stomp, line, pagertree alert notifications do not work properly due to a bug in yelp / elastalert. The docker image of elastalert-server has been modified independently so that zabbix, stomp, line and pagertree alert notifications will work properly.
