### ISSUE TITLE
Praeco TheHive intagration problem

### ISSUE THREAD

**Issue by tarekkilani** [johnsusek/praeco#312]
Hello, 
Please i'm trying to send alerts from elasalert to the hive.
I'm following this tutorial (check part : 2.2- Sending Alerts from ElastAlert to TheHive) :  

- https://medium.com/@ibrahim.ayadhi/hello-and-welcome-to-our-new-article-which-will-be-covering-the-alerting-part-in-our-socaas-136cf6258c49

After editing the yaml file and returning to praeco web interface, i get this message : Rule not found, it may have been moved or deleted.

I even followed the syntax of the hive alerts in the official documentation of elastalert : 

- https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

And i still have the same issue.

**Comment by nsano-rururu** [comment]
The existence of that document is not an official document. Ask the person who wrote the document. Praeco does not support The Hive.
