### ISSUE TITLE
Telegram Bot token field

### ISSUE THREAD

**Issue by doludizgin** [johnsusek/praeco#313]
At the the telegram alert the bot_token_field for the alert is missing.

I had to manualy add this to de rule.yml

Example
telegram_bot_token: 23432423442423:sdjfoisfjsfSDS

Can you add this field to the telegram alert GUI.

**Comment by nsano-rururu** [comment]
look
https://github.com/johnsusek/praeco/wiki/docker-compose-sample(telegram)
