### ISSUE TITLE
Change Timezone praco docker from UTC to GMT +1

### ISSUE THREAD

**Issue by doludizgin** [johnsusek/praeco#314]
if i execute:
docker exec -it praeco_elastalert_1 date 

i get an UTC Timezone withtin the docker.

I tried to add TZ: "Europe/Amsterdam" to the envirment of docker-compose didnt work.

Also tried to mount the - '/etc/localtime:/etc/localtime:ro' no luck.

How can i change the timezone of the docker  #container ?

**Comment by nsano-rururu** [comment]
Did you do the following but it didn't work?

docker-compose.yml

Only the target part

```
    environment:
      TZ: Europe/Amsterdam
    ports:
```

https://github.com/johnsusek/elastalert-server/blob/master/Dockerfile#L55
```
ENV TZ Etc/UTC
```

If so, I don't support it.
Please refer to the following and modify the Dockerfile by yourself to create a docker image.

Reference URL

docker alpineイメージでtimezoneをAsia/Tokyoに設定する
https://blog.pinkumohikan.com/entry/set-timezone-to-asia-tokyo-on-docker-alpine-linux
