### ISSUE TITLE
❓ Brute force alert

### ISSUE THREAD

**Issue by doludizgin** [johnsusek/praeco#315]
Hi,

I know that this isnt really the right place to ask but i am stuck, searched everywhere.

I am trying to create a rule that does the following:

I want to alert when multiple wrong logins come from 1 and the same computer within a timeframe.

The rule below works somewhat, but this counts up all the records from all machines, i  want to know if 1 machine makes that kind of request. So the query needs to see computername.value=10 same and wrong username/password 10 times within 10 min, without hardcoding computername because we're having about 900 VDI machines.

Hope this makes sense.

![image](https://user-images.githubusercontent.com/1220219/107424820-67d2ef00-6b1e-11eb-88c9-b33c7dafd8d1.png)

**Comment by nsano-rururu** [comment]
Then why not ask a question in the right place? It makes me feel uncomfortable when I say so. Close.
