### ISSUE TITLE
Overwriting yaml files (with rules). Another directives gets removed.

### ISSUE THREAD

**Issue by altuhovsu** [johnsusek/praeco#317]
Hello! 

Part of a my rule file:
```
alert:
  - slack
alert_subject: Large not shop errors in logging_fe
alert_subject_args: []
alert_text: '<{0}|Kibana link>'
alert_text_args: [ kibana_discover_url ]
alert_text_type: alert_text_only
generate_kibana_discover_url: true
kibana_discover_version: '7.3'
kibana_discover_app_url: https://kb5.zipy.co.il:8134/app/discover#/
kibana_discover_index_pattern_id: 8c0aaf60-02ec-11eb-b572-471f188d28d8 # specific to my instance
kibana_discover_columns: [ event.action, exception.message, request.ip, request.url.path, request.url.query, search.shop ]
filter:
```
The whole rule works fine (I receive alert in the Slack with linkl to the Kibana discover).

But, if I change someting in the Praeco, then I lost all of the kibana_discover options.
yaml file rewrites without this options.

In the Praeco I do not see this options on Elastalert YAML page (Praeco ignores it?)

```
alert:
  - slack
alert_subject: Large not shop errors in logging_fe
alert_subject_args: []
alert_text: <{0}|Kibana link>
alert_text_args:
  - kibana_discover_url
alert_text_type: alert_text_only
filter:
```

It is possbile to fix this? Or, may be exists any workaround?

**Comment by altuhovsu** [comment]
And I see it in a response from Praeco/Elastalert-server API (/api/rules/fe_notshops_errors)

![image](https://user-images.githubusercontent.com/59618193/107678586-43088400-6ca4-11eb-85ae-59bb6b908a27.png)

**Comment by nsano-rururu** [comment]
It means that you add it manually every time. Currently not. Because it does not support kibana_discover.

**Comment by nsano-rururu** [comment]
Praeco should not be used if you want to modify the rules manually.

**Comment by altuhovsu** [comment]
> Praeco should not be used if you want to modify the rules manually.
Naoyuki, ok, thank you very much! It is no so hard problem.
