### ISSUE TITLE
kibana_discover

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#318]
https://github.com/johnsusek/praeco/issues/317

Do you also support kibana 7.4-7.10?

```
  generate_kibana_discover_url: {type: boolean}
  kibana_discover_app_url: {type: string, format: uri}
  kibana_discover_version: {type: string, enum: ['7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}
  kibana_discover_index_pattern_id: {type: string, minLength: 1}
  kibana_discover_columns: {type: array, items: {type: string, minLength: 1}, minItems: 1}
  kibana_discover_from_timedelta: *timedelta
  kibana_discover_to_timedelta: *timedelta

  slack_attach_kibana_discover_url {type: boolean}
  slack_kibana_discover_color {type: string}
  slack_kibana_discover_title {type: string}
```

- [x] **elastalert/kibana_discover.py**

before

````
kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3'])
````

after

````
kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8', '7.9', '7.10', '7.11'])
````

- [x] **elastalert/schema.yaml**

before

````
  kibana_discover_version: {type: string, enum: ['7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}
````

after

````
kibana_discover_version: {type: string, enum: ['7.11', '7.10', '7.9', '7.8', '7.7', '7.6', '7.5', '7.4', '7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}
````

- [x] **Dockerfile**

edit 
add kibana_discover.py

```
# kibana_discover 7.4 - 7.11 support
# Fix until Fix Remove Duplicate Key in Schema YAML #2343(https://github.com/Yelp/elastalert/pull/2343) is merged
# Fix until Fix Fix Zabbix(Docs & schema.yaml) #2794(https://github.com/Yelp/elastalert/pull/2794) is merged
COPY patches/schema.yaml /opt/elastalert/elastalert/schema.yaml

# kibana_discover 7.4 - 7.11 support
COPY patches/kibana_discover.py /opt/elastalert/elastalert/kibana_discover.py
```

- [x] **Praeco**

We are considering how to make the screen UI

- src/components/config/alert/ConfigAlert.vue
- src/components/config/ConfigKibanaDiscover.vue
- src/registration.js
- src/store/config/alert.js
- src/store/config/index.js
- src/registration.js
- package.json
- package-lock.json

**Comment by altuhovsu** [comment]
@nsano-rururu 
kibana_discover works fine for me with an ElasticSearch 7.9.2 (and Kibana 7.9.2). 
Right now I'm using kibana_discover_version: 7.3
I'm planning to upgrade to 7.10 and test it.

And thanks for the info on these options!

> slack_attach_kibana_discover_url {type: boolean}
>   slack_kibana_discover_color {type: string}
>   slack_kibana_discover_title {type: string}

**Comment by nsano-rururu** [comment]
- [ ] **elastalert/kibana_discover.py**

before

````
kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3'])
````

after

````
kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8', '7.9', '7.10'])
````

- [ ] **elastalert/schema.yaml**

before

````
  kibana_discover_version: {type: string, enum: ['7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}
````

after

````
kibana_discover_version: {type: string, enum: ['7.10', '7.9', '7.8', '7.7', '7.6', '7.5', '7.4', '7.3', '7.2', '7.1', '7.0', '6.8', '6.7', '6.6', '6.5', '6.4', '6.3', '6.2', '6.1', '6.0', '5.6']}
````

- [ ] **Praeco**

We are considering how to make the screen UI

**Comment by nsano-rururu** [comment]
@altuhovsu

Since maintenance of elastalert is currently suspended, we will patch the docker image by applying our own patches.

Regarding Praeco's UI, I would like to add functions while creating and checking screen images, so please cooperate at that time.

**Comment by altuhovsu** [comment]
Yes! I want to help.

Maybe add Elastic version 7.11 too?

Current docker image with elastalert (praecoapp/elastalert-server) works fine with Elastic 7.9.2

**Comment by nsano-rururu** [comment]
> Maybe add Elastic version 7.11 too?

Thank you for pointing out. Also add 7.11

**Comment by nsano-rururu** [comment]
elastalert / kibana_discover.py and elastalert / schema.yaml with support for kibana 7.4-7.11 have been added to the docker image of elastalert-server.
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by altuhovsu** [comment]
@nsano-rururu sorry, '7.11', '7.10', '7.9' is not working.
I updated (pulled) new docker image, recreated container.

If I specify kibana_discover_version: '7.9', than I don't receive Kibana link in the Slack, with 7.3 all works fine.

I checked inside my container kibana_discover.py and I see 
`kibana5_kibana6_versions = frozenset(['5.6', '6.0', '6.1', '6.2', '6.3', '6.4', '6.5', '6.6', '6.7', '6.8'])
kibana7_versions = frozenset(['7.0', '7.1', '7.2', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8', '7.9', '7.10', '7.11'])
`

Can't understand, why 7.9 is not working :(

**Comment by altuhovsu** [comment]
@nsano-rururu 7.9 works fine!

**Comment by nsano-rururu** [comment]
@altuhovsu

The screen is still in the process of being made.

![0](https://user-images.githubusercontent.com/22293449/108085845-19db5f80-70b9-11eb-9be4-bb8317e31885.PNG)

![1](https://user-images.githubusercontent.com/22293449/108085256-7a1dd180-70b8-11eb-9f8b-82105564313b.PNG)
![2](https://user-images.githubusercontent.com/22293449/108085304-886bed80-70b8-11eb-8923-e58cd37db21d.PNG)

kibana_discover_from_timedelta and kibana_discover_to_timedelta will have the same UI as the Re-alert below.

![3](https://user-images.githubusercontent.com/22293449/108085346-9457af80-70b8-11eb-9f56-0baa9b16cd02.PNG)

kibana_discover_columns will be a UI that allows you to add / remove items as shown below.

![4](https://user-images.githubusercontent.com/22293449/108085362-991c6380-70b8-11eb-83e9-d606a95b31e0.PNG)

**Comment by nsano-rururu** [comment]
@altuhovsu

Is it okay to release with the following settings? Please let me know if you have any opinions.

![1](https://user-images.githubusercontent.com/22293449/108860629-b9589f00-7631-11eb-8c78-98834a0ab0f3.PNG)
![1-1](https://user-images.githubusercontent.com/22293449/108860639-bcec2600-7631-11eb-9d0a-1137591ac567.PNG)
![2](https://user-images.githubusercontent.com/22293449/108860647-bfe71680-7631-11eb-91df-439c45ebce85.PNG)
![3](https://user-images.githubusercontent.com/22293449/108860654-c2497080-7631-11eb-8536-1d5ea09507bc.PNG)

Added two settings to the slack settings screen
![4](https://user-images.githubusercontent.com/22293449/108860663-c4133400-7631-11eb-86a6-e15008e4298f.PNG)
![5](https://user-images.githubusercontent.com/22293449/108860677-c6758e00-7631-11eb-80d2-dcd285607b43.PNG)

**Comment by altuhovsu** [comment]
@nsano-rururu very good! Amazing! Is there option for switching true/falsen/off slack_attach_kibana_discover_url  ? Or its true if KIbana discover is on (true)?

**Comment by nsano-rururu** [comment]
I don't know if it can be implemented as requested. Because there are some things that don't work. Release postponed.

**Comment by nsano-rururu** [comment]
@altuhovsu

>very good! Amazing! Is there option for switching true/falsen/off slack_attach_kibana_discover_url ? Or its true if KIbana discover is on (true)?

Set "generate_kibana_discover_url" to true / false on / off. Also, if "slack_attach_kibana_discover_url" is true when turned off, set it to false.
Also, once set, the settings will not disappear by switching on / off. It remains in yaml.

generate_kibana_discover_url : Defaults to `false`
kibana_discover_from_timedelta: Defaults to `10 minutes`
kibana_discover_to_timedelta: Defaults to `10 minutes`
slack_attach_kibana_discover_url: Defaults to `false`
slack_kibana_discover_color: Defaults to `#ec4b98`
slack_kibana_discover_title: Defaults to `Discover in Kibana`

![キャプチャ](https://user-images.githubusercontent.com/22293449/109374376-4896d880-78f8-11eb-8030-fce697cc4efe.PNG)


Actually, I wanted to do not output the target setting to yaml when generate_kibana_discover_url is false, but I gave up this time because it seems impossible unless I have the setting information in the DB.

**Comment by nsano-rururu** [comment]
Note: Will not release until there is a reply

**Comment by altuhovsu** [comment]
I have cleared all settings related to kibana_discover and created them trought Praeco. This is a diff from my (working) config and config created by Praeco. Testing now.
 ```
 ~/backup/elastalert/rules/3/rules # diff fe_shops_errors.yaml /opt/elastalert/rules/fe_shops_errors.yaml
9c9
< alert_text: '{0}'
---
> alert_text: "{0}"
13,18c13
< generate_kibana_discover_url: true
< kibana_discover_version: '7.9'
< kibana_discover_app_url: https://kb.abc:1234/app/discover#/
< kibana_discover_index_pattern_id: 8c0aaf60-02ec-11eb-b572-471f188d28d8 # specific to my instance
< kibana_discover_columns: [ event.action, exception.message, request.ip, request.url.path, request.url.query, search.shop ]
< slack_attach_kibana_discover_url: true
---
> doc_type: _doc
22c17,18
<         query: 'search.shop:* AND user.agent.robot:false AND log.level_code:>200'
---
>         query: search.shop:* AND user.agent.robot:false AND log.level_code:>200
> generate_kibana_discover_url: true
25a22,35
> kibana_discover_app_url: https://kb5.zipy.co.il:8134/app/discover#/
> kibana_discover_columns:
>   - event.action
>   - exception.message
>   - request.ip
>   - request.url.path
>   - request.url.query
>   - search.shop
> kibana_discover_from_timedelta:
>   minutes: 10
> kibana_discover_index_pattern_id: 8c0aaf60-02ec-11eb-b572-471f188d28d8
> kibana_discover_to_timedelta:
>   minutes: 10
> kibana_discover_version: "7.9"
31c41,44
< slack_channel_override: '#alerts'
---
> slack_attach_kibana_discover_url: true
> slack_channel_override: "#alerts"
> slack_kibana_discover_color: "#ec4b98"
> slack_kibana_discover_title: Discover in Kibana
33c46
< slack_title_link: 'http://kb.abc:1234/rules/fe_shops_errors'
---
> slack_title_link: http://kb.abc:1234/rules/fe_shops_errors
38c51
< timestamp_field: '@timestamp'
---
> timestamp_field: "@timestamp"
42d54
< doc_type: _doc
```

**Comment by altuhovsu** [comment]
@nsano-rururu Thanks! For me it works as expected! Maybe someone else want to test it!?

**Comment by nsano-rururu** [comment]
@altuhovsu 

Thank you for your confirmation. We will contact you again after merging into the master branch and updating the release information and Docker image.

**Comment by nsano-rururu** [comment]
@altuhovsu

We have published a new Praco docker image, so this issue will be closed. Thank you for everything.
https://hub.docker.com/r/praecoapp/praeco

**Comment by nsano-rururu** [comment]
@altuhovsu

praeco 1.8.5 has been released. Kibana_discover is compatible with kibana 7.12.
https://hub.docker.com/r/praecoapp/praeco
