### ISSUE TITLE
TypeError: Cannot read property 'replace' of null - ELK-Version 7.10.1

### ISSUE THREAD

**Issue by ck-7** [johnsusek/praeco#319]
Please help me to setup elastalert am getting below while starting docker-compose up.

elastalert_1  | 10:52:43.631Z  INFO elastalert-server: Server:  Server started
elastalert_1  | TypeError: Cannot read property 'replace' of null
elastalert_1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:109:74)
elastalert_1  |     at new Promise (<anonymous>)
elastalert_1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:46:10)
elastalert_1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:52:10)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:76:7)
elastalert_1  |     at metadataElastalertHandler (/opt/elastalert-server/src/handlers/metadata/get.js:101:24)
elastalert_1  | TypeError: Cannot read property 'replace' of null
elastalert_1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:109:74)
elastalert_1  |     at new Promise (<anonymous>)
elastalert_1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:46:10)
elastalert_1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:52:10)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:76:7)
elastalert_1  |     at getClient (/opt/elastalert-server/src/common/elasticsearch_client.js:133:24)
elastalert_1  |     at metadataElastalertHandler (/opt/elastalert-server/src/handlers/metadata/get.js:102:20)
elastalert_1  | TypeError: Cannot read property 'search' of undefined
elastalert_1  |     at metadataElastalertHandler (/opt/elastalert-server/src/handlers/metadata/get.js:122:12)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  | 10:53:08.810Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 10:53:08.821Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 10:53:08.822Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | TypeError: Cannot read property 'replace' of null
elastalert_1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:109:74)
elastalert_1  |     at new Promise (<anonymous>)
elastalert_1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:46:10)
elastalert_1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:52:10)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:76:7)
elastalert_1  |     at getClient (/opt/elastalert-server/src/common/elasticsearch_client.js:133:24)
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:9:20)
elastalert_1  | TypeError: Cannot read property 'cat' of undefined
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:11:12)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Elastalert dashboard side getting 504 Error.
ELK configured with SSL 

API error

Error: Request failed with status code 504

Below config 
 api.config.json
 -----------------

[root@elk1 config]# cat api.config.json
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elktest-logging.example.net",
  "es_port": 9200,
  "es_username": "elastic",
  "es_password": "XXXDSDSDSD",
  "es_ssl": true,
  "es_ca_certs": "/opt/praeco-1.5.4/certs/ca.crt",
  "es_client_cert": "/opt/praeco-1.5.4/certs/certs.crt",
  "es_client_key": "/opt/praeco-1.5.4/certs/key1.key",
  "writeback_index": "praeco_elastalert_status"
}

elastalert.config
------------------
es_host: elktest-logging.example.net
es_port: 9200
use_ssl: True
client_cert: /opt/praeco-1.5.4/crts.crt
client_key: /opt/praeco-1.5.4/certs/key1.key
ca_certs: /opt/praeco-1.5.4/certs/ca.crt

es_username: "elastic"
es_password: "XXDDSDSDSD"

export PRAECO_ELASTICSEARCH=10.100.112.11

docker-compose.yml
================

version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elktest-logging.example.net:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
#    environment:
#      VUE_APP_BASE_URL: /my-path/
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf

**Comment by nsano-rururu** [comment]
I do not understand

**Comment by ck-7** [comment]
While running the elastalert its getting 504 RTO .   ELK index is not loading

![image](https://user-images.githubusercontent.com/8079914/107762852-a7cee780-6d53-11eb-9b7a-a8942f3b1032.png)

**Comment by nsano-rururu** [comment]
@ck-7

Did you mount the following certificate when you start it with docker-compose? .. You can't read it unless it's mounted.

/opt/praeco-1.5.4/crts.crt
/opt/praeco-1.5.4/certs/key1.key
opt/praeco-1.5.4/certs/ca.crt

**Comment by nsano-rururu** [comment]
@ck-7

I'm not free

**Comment by ck-7** [comment]
apologies Yes, i know how busy your another project. 
manually copied  crt,CA,key into above path when the container is up then restarted the elast-alert container its picked the certificate is vailed then elastalert is successfully started. When i navigate into praeco dashboard its getting loading with index, then its get API Error 504. 

elastalert_1  | 11:27:35.723Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
webapp_1      | 2021/02/12 11:28:35 [error] 7#7: *24 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.101.10.15, server: , request: "GET /api/indices HTTP/1.1", upstream: "http://172.18.0.2:3030/indices", host: "10.101.16.10:8080", referrer: "http://10.101.16.10:8080/rule/add"
elastalert_1  | TypeError: Cannot read property 'replace' of null
elastalert_1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:109:74)
elastalert_1  |     at new Promise (<anonymous>)
elastalert_1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:46:10)
elastalert_1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:52:10)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:76:7)
elastalert_1  |     at getClient (/opt/elastalert-server/src/common/elasticsearch_client.js:133:24)
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:9:20)
elastalert_1  | TypeError: Cannot read property 'cat' of undefined
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:11:12)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  | 11:34:45.313Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 11:34:45.318Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:34:45.319Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.

**Comment by ck-7** [comment]
Let me walk through with these issues.
Thanks for the Time and for responding back

**Comment by nsano-rururu** [comment]
Encrypting communications in an Elasticsearch Docker Container
https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html
Encrypting communications in an {es} Docker Container
https://github.com/elastic/elasticsearch/blob/master/x-pack/docs/en/security/securing-communications/configuring-tls-docker.asciidoc

**Comment by nsano-rururu** [comment]
Settings to connect to an Elastic serach with TLS encryption and HTTPS communication enabled. Do you set it that way in your Elasticsearch?

**Comment by ck-7** [comment]
Yes its enabled with TLS.. its working as expected i can see index management praeco as healthy only point getting request time out in API connection. ELK index not visible in Praeco GUI mode.

THE same TLS certificate is used for connecting from API.

ELK does not implement the container model.  

![image](https://user-images.githubusercontent.com/8079914/107769017-53306a00-6d5d-11eb-9193-032543e8a1cb.png)

**Comment by nsano-rururu** [comment]
```
volumes:
  - ./config/elastalert.yaml:/opt/elastalert/config.yaml
  - ./config/api.config.json:/opt/elastalert-server/config/config.json
  - ./rules:/opt/elastalert/rules
  - ./rule_templates:/opt/elastalert/rule_templates
```

↓

```
volumes:
  - ./config/elastalert.yaml:/opt/elastalert/config.yaml
  - ./config/api.config.json:/opt/elastalert-server/config/config.json
  - ./rules:/opt/elastalert/rules
  - ./rule_templates:/opt/elastalert/rule_templates
  - ./certs/crts.crt:/opt/praeco-1.5.4/crts.crt
  - ./certs/key1.key:/opt/praeco-1.5.4/certs/key1.key
  - ./certs/ca.crt:/opt/praeco-1.5.4/certs/ca.crt
```

**Comment by ck-7** [comment]
Same Error getting API Request time out 504

Here the full logs
============

[root@elk1-logging praeco-1.5.4]# docker-compose up --force-recreate --build
Recreating praeco154_webapp_1 ...
Recreating praeco154_webapp_1 ... done
Attaching to praeco154_elastalert_1, praeco154_webapp_1
webapp_1      | Starting Nginx
elastalert_1  |
elastalert_1  | > @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
elastalert_1  | > sh ./scripts/start.sh
elastalert_1  |
elastalert_1  | 13:33:27.179Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
elastalert_1  | 13:33:27.181Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
elastalert_1  | 13:33:27.181Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
elastalert_1  | 13:33:27.190Z  INFO elastalert-server: Router:  Listening for GET request on /.
elastalert_1  | 13:33:27.190Z  INFO elastalert-server: Router:  Listening for GET request on /status.
elastalert_1  | 13:33:27.190Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
elastalert_1  | 13:33:27.190Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
elastalert_1  | 13:33:27.192Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
elastalert_1  | 13:33:27.193Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
elastalert_1  | 13:33:27.193Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
elastalert_1  | 13:33:27.193Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
elastalert_1  | 13:33:27.193Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
elastalert_1  | 13:33:27.193Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
elastalert_1  | 13:33:27.194Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
elastalert_1  | 13:33:27.194Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
elastalert_1  | 13:33:27.194Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
elastalert_1  | 13:33:27.194Z  INFO elastalert-server: Router:  Listening for POST request on /test.
elastalert_1  | 13:33:27.194Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for POST request on /config.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for POST request on /download.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
elastalert_1  | 13:33:27.195Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
elastalert_1  | 13:33:27.196Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 13:33:27.200Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
elastalert_1  | 13:33:27.200Z  INFO elastalert-server: ProcessController:  Creating index
elastalert_1  | 13:33:27.745Z  INFO elastalert-server:
elastalert_1  |     ProcessController:  Elastic Version: 7.10.1
elastalert_1  |     Reading Elastic 6 index mappings:
elastalert_1  |     Reading index mapping 'es_mappings/6/silence.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_status.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/past_elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_error.json'
elastalert_1  |     Index praeco_elastalert_status already exists. Skipping index creation.
elastalert_1  |
elastalert_1  | 13:33:27.746Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
elastalert_1  | 13:33:27.746Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
elastalert_1  | 13:33:27.755Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
elastalert_1  | 13:33:27.757Z  INFO elastalert-server: Server:  Server listening on port 3030
elastalert_1  | 13:33:27.758Z  INFO elastalert-server: Server:  Websocket listening on port 3333
elastalert_1  | 13:33:27.758Z  INFO elastalert-server: Server:  Server started
elastalert_1  | TypeError: Cannot read property 'replace' of null
elastalert_1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:109:74)
elastalert_1  |     at new Promise (<anonymous>)
elastalert_1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:46:10)
elastalert_1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:52:10)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:76:7)
elastalert_1  |     at getClient (/opt/elastalert-server/src/common/elasticsearch_client.js:133:24)
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:9:20)
elastalert_1  | TypeError: Cannot read property 'cat' of undefined
elastalert_1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:11:12)
elastalert_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
elastalert_1  | 13:33:37.259Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 13:33:37.269Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 13:33:37.270Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.

**Comment by nsano-rururu** [comment]
No further support is possible. I gave up the solution.

**Comment by nsano-rururu** [comment]
We recommend that you do not use praeco and elastalert-server.

**Comment by nsano-rururu** [comment]
```
chmod 777 rules rule_templates
```

```sh
/home/user/dkwork2/es2
|--.env
|--config
|  |--api.config.json
|  |--elastalert.yaml
|--create-certs.yml
|--docker-compose-praeco.yml
|--docker-compose.yml
|--instances.yml
|--nginx_config
|  |--default.conf
|  |--nginx.conf
|--public
|  |--praeco.config.json
|--rule_templates
|--rules
```

.env

```sh
COMPOSE_PROJECT_NAME=es 
CERTS_DIR=/usr/share/elasticsearch/config/certificates 
ELASTIC_PASSWORD=PleaseChangeMe
```

config/api.config.json

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "es01",
  "es_port": 9200,
  "es_username": "elastic",
  "es_password": "xxxxxxxxx
  ",
  "es_ca_certs": "/usr/share/elasticsearch/config/certificates/ca/ca.crt", 
  "es_client_cert": "/usr/share/elasticsearch/config/certificates/es01/es01.crt", 
  "es_client_key": "/usr/share/elasticsearch/config/certificates/es01/es01.key", 
  "es_ssl": true,
  "writeback_index": "praeco_elastalert_status"
}

```

config/-elastalert.yaml

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: es01

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: elastic
es_password: xxxxxxxxx

# ssl
ca_certs: /usr/share/elasticsearch/config/certificates/ca/ca.crt
client_cert: /usr/share/elasticsearch/config/certificates/es01/es01.crt
client_key: /usr/share/elasticsearch/config/certificates/es01/es01.key

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```

create-certs.yml

```yaml
version: '2.2'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    command: >
      bash -c '
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs; 
        fi;
        chown -R 1000:0 /certs
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/certs', '.:/usr/share/elasticsearch/config/certificates']

volumes: {"certs"}
```

instances.yml


```yaml
instances:
  - name: es01
    dns:
      - es01 
      - localhost
    ip:
      - 127.0.0.1

  #- name: es02
  #  dns:
  #    - es02
  #    - localhost
  #  ip:
  #    - 127.0.0.1
```

docker-compose.yml

```yaml
version: '2.2'

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - cluster.name=es01
      #- node.name=es01
      #- discovery.seed_hosts=es01,es02
      #- cluster.initial_master_nodes=es01,es02
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD 
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.license.self_generated.type=trial 
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
    volumes: ['data01:/usr/share/elasticsearch/data', 'certs:$CERTS_DIR']
    ports:
      - 9200:9200
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes: {"data01", "certs"}
```

docker-compose-praeco.yml

```yaml
version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
      - certs:/usr/share/elasticsearch/config/certificates
    #extra_hosts:
    #  - 'elasticsearch:${PRAECO_ELASTICSEARCH}'
    tty: true
    networks:
      - default
      - es_default

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
      - certs:/usr/share/elasticsearch/config/certificates
    tty: true
    networks:
      - default
      - es_default

volumes: { "certs" }

networks:
  es_default:
    external: true
```

```
$ docker-compose -f create-certs.yml run --rm create_certs

Creating network "es_default" with the default driver
Creating volume "es_certs" with default driver
Archive:  /certs/bundle.zip
   creating: /certs/ca/
  inflating: /certs/ca/ca.crt        
   creating: /certs/es01/
  inflating: /certs/es01/es01.crt    
  inflating: /certs/es01/es01.key   

$ docker-compose up -d

Creating volume "es_data01" with default driver
Creating es01 ... done

$ docker run --rm -v es_certs:/certs --network=es_default docker.elastic.co/elasticsearch/elasticsearch:7.10.0 curl --cacert /certs/ca/ca.crt -u elastic:PleaseChangeMe https://es01:9200

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to es01 port 9200: Connection refused

$ docker exec es01 /bin/bash -c "bin/elasticsearch-setup-passwords \
auto --batch \
--url https://localhost:9200"

# Should be output with a different value each time

Changed password for user apm_system
PASSWORD apm_system = aaaaaaaaaaaa

Changed password for user kibana_system
PASSWORD kibana_system = bbbbbbbbb

Changed password for user kibana
PASSWORD kibana = ddddddddddd

Changed password for user logstash_system
PASSWORD logstash_system = eeeeeeeeee

Changed password for user beats_system
PASSWORD beats_system = fffffffffff

Changed password for user remote_monitoring_user
PASSWORD remote_monitoring_user = gffffffff

Changed password for user elastic
PASSWORD elastic = xxxxxxxxx


$ curl -u elastic:xxxxxxxxx https://localhost:9200/_cat/indices?v

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

$ curl -u elastic:xxxxxxxxx localhost:9200?pretty

curl: (52) Empty reply from server

$ docker run --rm -v es_certs:/certs --network=es_default docker.elastic.co/elasticsearch/elasticsearch:7.10.0 curl --cacert /certs/ca/ca.crt -u elastic:xxxxxxxxx https://es01:9200/_cat/indices?v

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   214  100   214    0     0    697      0 --:--:-- --:--:-- --:--:--   697
health status index       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .security-7 HVZs78GJTV6A1EbjTG_2Fg   1   0          7            0     25.1kb         25.1kb

$ docker ps

CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                   PORTS                              NAMES
65263085b175        docker.elastic.co/elasticsearch/elasticsearch:7.10.0   "/tini -- /usr/local…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:9200->9200/tcp, 9300/tcp   es01

$ docker-compose -f docker-compose-praeco.yml up -d

$ docker logs -f es_elastalert_1

> @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
> sh ./scripts/start.sh

15:42:37.418Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
15:42:37.421Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
15:42:37.443Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
15:42:37.506Z  INFO elastalert-server: Router:  Listening for GET request on /.
15:42:37.507Z  INFO elastalert-server: Router:  Listening for GET request on /status.
15:42:37.507Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
15:42:37.508Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
15:42:37.511Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
15:42:37.512Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
15:42:37.513Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
15:42:37.513Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
15:42:37.513Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
15:42:37.513Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
15:42:37.514Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
15:42:37.514Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
15:42:37.515Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
15:42:37.515Z  INFO elastalert-server: Router:  Listening for POST request on /test.
15:42:37.515Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
15:42:37.515Z  INFO elastalert-server: Router:  Listening for GET request on /config.
15:42:37.516Z  INFO elastalert-server: Router:  Listening for POST request on /config.
15:42:37.516Z  INFO elastalert-server: Router:  Listening for POST request on /download.
15:42:37.516Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
15:42:37.516Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
15:42:37.516Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
15:42:37.524Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
15:42:37.525Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
15:42:37.525Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
15:42:37.525Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
15:42:37.527Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
15:42:37.528Z  INFO elastalert-server: Router:  Listening for GET request on /config.
15:42:37.535Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
15:42:37.535Z  INFO elastalert-server: ProcessController:  Creating index
15:42:42.772Z  INFO elastalert-server:
    ProcessController:  Elastic Version: 7.10.0
    Reading Elastic 6 index mappings:
    Reading index mapping 'es_mappings/6/silence.json'
    Reading index mapping 'es_mappings/6/elastalert_status.json'
    Reading index mapping 'es_mappings/6/elastalert.json'
    Reading index mapping 'es_mappings/6/past_elastalert.json'
    Reading index mapping 'es_mappings/6/elastalert_error.json'
    New index praeco_elastalert_status created
    Done!
    
15:42:42.772Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Camel case format name dateOptionalTime is deprecated and will be removed in a future version. Use snake case name date_optional_time instead.
      warnings.warn(message, category=ElasticsearchDeprecationWarning)
    /home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: [types removal] Using include_type_name in put mapping requests is deprecated. The parameter will be removed in the next major version.
      warnings.warn(message, category=ElasticsearchDeprecationWarning)
    
15:42:42.772Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
15:42:42.773Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
15:42:42.827Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
15:42:42.831Z  INFO elastalert-server: Server:  Server listening on port 3030
15:42:42.833Z  INFO elastalert-server: Server:  Websocket listening on port 3333
15:42:42.835Z  INFO elastalert-server: Server:  Server started
```
![キャプチャ](https://user-images.githubusercontent.com/22293449/107791725-9dced800-6d97-11eb-93b5-330463829519.PNG)

**Comment by ck-7** [comment]
@nsano-rururu Thank you for the response back again .. I changed the permission for the folder rules and rules_templates. I will review the setting and let you know once it fixed the reported issues..  By the Way am New with docker and ELK..
