### ISSUE TITLE
"Insert fields by typing '%' followed by the field name" does not populate

### ISSUE THREAD

**Issue by ashishkaransingh** [johnsusek/praeco#320]
Thank you for the superb UI!

I am facing one issue.

"Insert fields by typing '%' followed by the field name" is not working.

See the following snippet with blank/empty sub window when i typed
%fields.XXXX

![image](https://user-images.githubusercontent.com/29729110/107952420-be797680-6fbf-11eb-92a0-590caaa2885d.png)

**Comment by nsano-rururu** [comment]
I don't think it is supported in the current production.

**Comment by nsano-rururu** [comment]
This may be due to using the js-yaml settings by default.
https://www.npmjs.com/package/js-yaml
>quotingType (' or ", default: ') - strings will be quoted using this quoting style. If you specify single quotes, double quotes will still be used for non-printable characters.

**Comment by nsano-rururu** [comment]
**src/store/config.s.js**

before
```
      try {
        let res = await axios.post(`/api/${type}/${path}`, {
          yaml: yaml.dump(conf)
        });
```
after
```
      try {
        let res = await axios.post(`/api/${type}/${path}`, {
          yaml: yaml.dump(conf, { quotingType: '"' })
        });
```

before
```
      try {
        let res = await axios.post(`/api/rules/${conf.__praeco_full_path}`, {
          yaml: yaml.dump(conf)
        });
```
after
```
      try {
        let res = await axios.post(`/api/rules/${conf.__praeco_full_path}`, {
          yaml: yaml.dump(conf, { quotingType: '"' })
        });
```

before
```
      try {
        let res = await axios.post(`/api/rules/${conf.__praeco_full_path}`, {
          yaml: yaml.dump(conf)
        });
```
after
```
      try {
        let res = await axios.post(`/api/rules/${conf.__praeco_full_path}`, {
          yaml: yaml.dump(conf, { quotingType: '"' })
        });
```

**src/store/config/index.js**

before
```
yaml: (state, getters) => forTest => yaml.dump(getters.config(forTest))
```
after
```
yaml: (state, getters) => forTest => yaml.dump(getters.config(forTest), { quotingType: '"' })
```

**Comment by nsano-rururu** [comment]
@ashishkaransingh

We plan to support it, but we will not release a supported version immediately as we need to check for any affected processing.

**Comment by ashishkaransingh** [comment]
> @ashishkaransingh
> 
> We plan to support it, but we will not release a supported version immediately as we need to check for any affected processing.



> @ashishkaransingh
> 
> We plan to support it, but we will not release a supported version immediately as we need to check for any affected processing.

Sure, thanks @nsano-rururu

**Comment by nsano-rururu** [comment]
It will be supported in the next release, 1.6.0.
