### ISSUE TITLE
Credentials/Login for Praeco

### ISSUE THREAD

**Issue by btvmunoz** [johnsusek/praeco#322]
Hello @nsano-rururu,

Thank you for your help last time regarding reading from multiple ES Instances.

Another question has come to mind through the implementation, all looks good and we have made it work but we were wondering if Praeco has a login page and credential verification as multiple users are intended to use this but we want to verify who is performing which action, this would obviously mean that the platform should be auditable.

Any chance this could be something to add in the future or maybe it's an idea that could be proposed?

**Comment by nsano-rururu** [comment]
I wasn't really thinking about it. I didn't make Praeo, so I don't understand the design concept.
I became a co-maintainer last August, but Praeco hasn't touched Elast Alert at work either.

Currently Praeco doesn't use a database, so I think you need a database such as MariaDB. Currently, we cannot afford to respond at all.

**Comment by nsano-rururu** [comment]
I don't use vue, node.js, python, and git at all at work, so even if I support them, I think it will take time because I will support them while checking.

**Comment by btvmunoz** [comment]
@nsano-rururu noted and understandable.

While I do not have a good understanding of vue or node.js I have some knowledge in Python, I was wondering if maybe I could help with this while studying the code and figuring this out as it moves along.

**Comment by nsano-rururu** [comment]
Login information, authority information (for example, add / reference / change / delete rules / templates, authority for each setting, etc.), operation log, etc. are retained in the database. Add functions such as user addition / change / deletion, authority setting, operation log reference, etc.

**Comment by nsano-rururu** [comment]
The explanation was missing. Praeco is vue, element-ui. ElastAlertServer is Node.js. ElastAlert is Python. Since ElastAlert is currently dormant and unmaintained, the documentation is old and buggy, so you need to read the Python source code as you need to look at the implementation. Python is readable to some extent because of the bug fixes in ElastAlert and the inclusion in the Docker image of ElastAlertServer.

**Comment by nsano-rururu** [comment]
Since Praeco is implemented only in the front-end language, it is also necessary to select the DB and back-end languages.

**Comment by nsano-rururu** [comment]
We cannot promise that we will respond lightly, and we cannot promise forever.

**Comment by nsano-rururu** [comment]
If you really don't have the login function, look for another one.

**Comment by nsano-rururu** [comment]
Even if I respond, I'm afraid that it will be different even if I do not have a more concrete image of correspondence.

**Comment by nsano-rururu** [comment]
I will close it because I can not respond in the latest. It will reopen when the time comes.

**Comment by nsano-rururu** [comment]
It's not that I don't do it. Do it after preparing

**Comment by nsano-rururu** [comment]
@btvmunoz

I want to make it possible to modify the screen of BaseRule.config of common settings and add a screen that allows you to add settings directly for each rule, so at that time it will be necessary to create a DB. At that time, I would like to consider the login screen, log output, permissions, etc.

**Comment by johnsusek** [comment]
@nsano-rururu @btvmunoz 

Hi, I have handed over maintenance to rururu, so I am not checking issues regularly, but I can hopefully help a little for this:

The praeco frontend is served by an nginx docker container. 

Authentication can be added the same way you add authentication to any nginx instance. 

Just edit the files in https://github.com/johnsusek/praeco/tree/master/nginx_config to configure nginx auth settings.

https://docs.nginx.com/nginx/admin-guide/security-controls/

Hope this helps!

**Comment by nsano-rururu** [comment]
@johnsusek 

Even just commenting may help solve the problem. Please comment from time to time

**Comment by nsano-rururu** [comment]
@btvmunoz

In elastalert2, the main maintainer is actively capturing pull requests, and various people are responding to user inquiries and problems, so there is no particular problem. It's a situation where I don't seem to have to work hard. The concern is that it looks like I'm capturing a pull request without checking its behavior. You trust too much of what you made the pull request. Bugs may occur after release. Test code coverage is not very high. 66%. So far, all I'm thinking about is increasing the pattern of test code.
