### ISSUE TITLE
Don't get alerts sometimes

### ISSUE THREAD

**Issue by ValentinPifu** [johnsusek/praeco#323]
Hello,

I have a problem with some alerts. 
I want to get alerts when a new **"NullPointerException"** appear on es but sometimes works sometimes don't.
I need to use another filter to get all new errors?

Below I attached two screenshots: one with one of the new NullPointerException and second with the alert that doesn't mail me.
![main](https://user-images.githubusercontent.com/18114871/108975387-1b93bd00-768f-11eb-82fd-96f329fa01d8.png)
![email](https://user-images.githubusercontent.com/18114871/108975395-1df61700-768f-11eb-81a3-28df07d36159.png)

**Comment by nsano-rururu** [comment]
Can't you read the characters?
![キャプチャ](https://user-images.githubusercontent.com/22293449/109004068-97235780-76eb-11eb-9e28-721ab4112844.PNG)

**Comment by nsano-rururu** [comment]
Isn't it better to use contens?
I don't need "*" before and after
![2](https://user-images.githubusercontent.com/22293449/109005225-0e0d2000-76ed-11eb-9175-8277cb22743a.PNG)

**Comment by ValentinPifu** [comment]
I get that 

> Can't you read the characters?
> ![キャプチャ](https://user-images.githubusercontent.com/22293449/109004068-97235780-76eb-11eb-9e28-721ab4112844.PNG)

I get that but isn't my problem right there.

I get some (more than 1) Nulls at 11:16 and 11:21. I get 2 notifications and everything it's fine.
I get only one Nulls at 14:00 but I don't get a notification from that.
If you can see in the UI, it shows the Null at 14:00 but I don't get a notification.

![Screenshot from 2021-02-24 15-18-05](https://user-images.githubusercontent.com/18114871/109006296-9a025600-76b3-11eb-90c6-2662c0137aba.png)
![Screenshot from 2021-02-24 15-18-21](https://user-images.githubusercontent.com/18114871/109006687-01b8a100-76b4-11eb-8dde-4edea11ea014.png)

**Comment by nsano-rururu** [comment]
Isn't it bad for me? Then I'll close it

**Comment by ValentinPifu** [comment]
> Isn't it bad for me? Then I'll close it

But the problem isn't fixed.

**Comment by nsano-rururu** [comment]
I don't know anymore

**Comment by nsano-rururu** [comment]
Please do something yourself.

**Comment by nsano-rururu** [comment]
**filed in list**

Notifies when the specified field matches the specified value.

**filed not in list**

Notifies when the specified field does not match the specified value.

**field changes**

Notifies you when the value of the specified field changes.

**count**

Notifies when the number of documents of the specified query exceeds the specified value within the specified period. You can detect system abnormalities.

**new term**

Notifies when the value of the specified field does not have the same value within the specified period. You can discover unknown log output.

**cardinality**

Notifies you when the number of fields in the index increases. You can discover changes in the format of your data source.
