### ISSUE TITLE
Addition of settings that can be set on the supported alerts screen

### ISSUE THREAD

**Issue by nsano-rururu** [johnsusek/praeco#325]
Working branch
https://github.com/johnsusek/praeco/tree/add_ui_item

- [x] **Command**

pipe_match_json and pipe_match_json are true / false

| name | UI | Remark |
|:-----|:--:|--------|
|command|〇|change UI to add / update / delete key|
|pipe_match_json|✖→el-switch|BaseRule.config|
|pipe_alert_text|✖→el-switch|BaseRule.config|

---

- [x] **Email**

Default value. smtp_host is "localhost", 
smtp_ssl is false, 
and email_format should be set to "html" when enabled on the screen.

| name | UI | Remark |
|:-----|:--:|--------|
|email|〇||
|smtp_host|✖→el-input|BaseRule.config|
|smtp_ssl|✖→el-switch|BaseRule.config|
|from_addr|〇||
|smtp_auth_file|✖→el-input|BaseRule.config|
|smtp_key_file|✖→el-input|BaseRule.config|
|smtp_cert_file|✖→el-input|BaseRule.config|
|cc|〇||
|bcc|〇||
|email_from_field|✖→el-input|BaseRule.config|
|email_add_domain|✖→el-input|BaseRule.config|
|email_format|✖|BaseRule.config|
|email_reply_to|〇||

---

- [x] **MS Teams**

Default value. 
ms_teams_alert_fixed_width is false, 
ms_teams_alert_summary is "ElastAlert Message"

| name | UI | Remark |
|:-----|:--:|--------|
|ms_teams_webhook_url|〇||
|ms_teams_proxy|✖→el-input|BaseRule.config|
|ms_teams_alert_summary|✖→el-input||
|ms_teams_alert_fixed_width|✖→el-switch|BaseRule.config|
|ms_teams_theme_color|〇→el-color-picker||

---

- [x] **Slack**

Default value. slack_username_override is "elastalert", 
slack_emoji_override is ": ghost:", 
slack_msg_color is "danger", 
slack_ignore_ssl_errors is false, 
slack_timeout is 10, 
slack_attach_kibana_discover_url is false, 
slack_kibana_discover_url is false, 
slack_kibana_discover_color "

example
```yaml
slack_alert_fields:
- title: Host
  value: monitor.host
  short: true
- title: Status
  value: monitor.status
  short: true
- title: Zone
  value: beat.name
  short: true
```

| name | UI | Remark |
|:-----|:--:|--------|
|slack_webhook_url|✖|BaseRule.config|
|slack_proxy|✖→el-input|BaseRule.config|
|slack_username_override|〇||
|slack_channel_override|〇||
|slack_title_link|〇||
|slack_emoji_override|〇||
|slack_icon_url_override|✖→el-input|BaseRule.config|
|slack_msg_color|〇||
|slack_parse_override|✖→el-radio<br>none, full|BaseRule.config。default 'none'|
|slack_text_string|✖→el-input|BaseRule.config|
|slack_alert_fields|✖|BaseRule.config|
|slack_ignore_ssl_errors|✖→el-switch|BaseRule.config|
|slack_timeout|✖→el-input-number|BaseRule.config|
|slack_ca_certs|✖→el-input|BaseRule.config|
|slack_attach_kibana_discover_url|〇||
|slack_kibana_discover_color|〇→el-color-picker||
|slack_kibana_discover_title|〇||

---

- [x] **Mattermost**

Default value. 
mattermost_ignore_ssl_errors is false, 
mattermost_username_override is "elastalert", 
mattermost_msg_color is "danger".

I haven't yet imagined how mattermost_msg_fields will respond

example
```yaml
mattermost_msg_fields:
- title: Stack
  value: "{0} {1}" # interpolate fields mentioned in args
  short: false
  args: ["type", "msg.status_code"] # fields from doc
- title: Name
  value: static field
  short: false
```

| name | UI | Remark |
|:-----|:--:|--------|
|mattermost_webhook_url|✖|BaseRule.config|
|mattermost_proxy|✖→el-input|BaseRule.config|
|mattermost_ignore_ssl_errors|✖→el-switch|BaseRule.config|
|mattermost_username_override|〇||
|mattermost_channel_override|〇||
|mattermost_icon_url_override|✖→el-input|BaseRule.config|
|mattermost_msg_pretext|✖→el-input|BaseRule.config|
|mattermost_msg_color|〇||
|mattermost_msg_fields|✖|BaseRule.config|

---

- [x] **Telegram**

 leave telegram_api_url unset on the screen.

| name | UI | Remark |
|:-----|:--:|--------|
|telegram_bot_token|✖|BaseRule.config|
|telegram_room_id|〇||
|telegram_api_url|✖|default value 'api.telegram.org'|
|telegram_proxy|✖→el-input|BaseRule.config|
|telegram_proxy_login|✖→el-input|BaseRule.config|
|telegram_proxy_pass|✖→el-input|BaseRule.config|

---

- [x] **GoogleChat**

The following items can be set only when format = card

googlechat_header_title
googlechat_header_subtitle
googlechat_header_image
googlechat_footer_kibanalink

| name | UI | Remark |
|:-----|:--:|--------|
|googlechat_webhook_url|〇||
|googlechat_format|〇||
|googlechat_header_title|〇||
|googlechat_header_subtitle|✖→el-input|BaseRule.config|
|googlechat_header_image|✖→el-input|BaseRule.config|
|googlechat_footer_kibanalink|✖→el-input|BaseRule.config|

---

- [x] **VictorOps**

Default value. 
victorops_entity_display_name is “no entity display name”

| name | UI | Remark |
|:-----|:--:|--------|
|victorops_api_key|〇||
|victorops_routing_key|〇||
|victorops_message_type|〇||
|victorops_entity_id|〇||
|victorops_entity_display_name|〇||
|victorops_proxy|✖→el-input|BaseRule.config|

---

- [x] **Gitter**

Default value. The default value for gitter_msg_level is "error"

| name | UI | Remark |
|:-----|:--:|--------|
|gitter_webhook_url|✖→el-input|BaseRule.config|
|gitter_msg_level|〇||
|gitter_proxy|✖→el-input|BaseRule.config|

---

- [x] **Stomp**

| name | UI | Remark |
|:-----|:--:|--------|
|stomp_hostname|〇|default 'localhost'|
|stomp_hostport|〇|default '61613'|
|stomp_login|〇|default 'admin'|
|stomp_password|〇|default 'admin'|
|stomp_destination|〇|default '/queue/ALERT'|
|stomp_ssl|✖→el-switch|default False<br>BaseRule.config|

---

- [x] **HTTP POST**

Default value. http_post_timeout is 10

Corresponding image does not come. May be difficult

| name | UI | Remark |
|:-----|:--:|--------|
|http_post_url|〇||
|http_post_proxy|✖→el-input|BaseRule.config|
|http_post_payload|✖|BaseRule.config|
|http_post_static_payload|✖|BaseRule.config|
|http_post_all_values|✖|BaseRule.config|
|http_post_headers|✖|BaseRule.config|
|http_post_timeout|✖→el-input-number|BaseRule.config|

---

- [x] **Zabbix**

Default value. 
zbx_sender_host is "localhost", 
zbx_sender_port is 10051

| name | UI | Remark |
|:-----|:--:|--------|
|zbx_sender_host|✖→el-input|BaseRule.config|
|zbx_sender_port|✖→el-input-number|BaseRule.config|
|zbx_host|〇||
|zbx_key|〇||

---

- [x] **ServiceNow**

| name | UI | Remark |
|:-----|:--:|--------|
|username|〇||
|password|〇||
|servicenow_rest_url|〇||
|short_description|〇||
|comments|〇||
|assignment_group|〇||
|category|〇||
|subcategory|〇||
|cmdb_ci|〇||
|caller_id|〇||
|servicenow_proxy|✖→el-input|BaseRule.config|

---

- [x] **PagerTree**

| name | UI | Remark |
|:-----|:--:|--------|
|pagertree_integration_url|〇||
|pagertree_proxy|✖→el-input|BaseRule.config|

**Comment by nsano-rururu** [comment]
[Add optional HTTP post options](https://github.com/johnsusek/praeco/issues/267)
[email and teams html format support](https://github.com/johnsusek/praeco/issues/248)
[Alerts email format - support for HTML](https://github.com/johnsusek/praeco/issues/127)
[Add option for email_from_field and email_add_domain](https://github.com/johnsusek/praeco/issues/119)

**Comment by xuanyuanaosheng** [comment]
@nsano-rururu   Please add alertmanager support

**Comment by nsano-rururu** [comment]
@xuanyuanaosheng

elastalert shouldn't support alertmanager, but is there any information I don't know?

**Comment by nsano-rururu** [comment]
@xuanyuanaosheng

Make a feature request to yelp/elastalert.
