### ISSUE TITLE
Can send alerts using Test button and cannot send alerts when enabled.

### ISSUE THREAD

**Issue by ashishkaransingh** [johnsusek/praeco#329]
Hello,

Sending Alerts to ServiceNow.

I can trigger and send alerts using Test button to ServiceNow.
But the same Rule shows error in the Alert log when we Enable the task for auto run.
I can see the /elastalert/elastalert/alerts.py has `class ServiceNowAlerter(Alerter):`

Where else do i need to check, is this Praeco's issue or Elastalert?

The following works:
![image](https://user-images.githubusercontent.com/29729110/110793460-a6cd9f00-829a-11eb-8290-083dae1eeffb.png)

But when I enable the Rule, I see the following error

Not sent | 3/11/2021 6:28:59 PM | Service Now | Error posting to ServiceNow: 500 Server Error: Internal Server Error for url: https://allscriptsatlantis.service-now.com/api/global/em/jsonv2
-- | -- | -- | --

![image](https://user-images.githubusercontent.com/29729110/110793560-c49b0400-829a-11eb-95a4-37828b9a1460.png)

Thanks

**Comment by nsano-rururu** [comment]
I don't know because ServiceNow hasn't been confirmed to work.

**Comment by nsano-rururu** [comment]
Can it be used for free? .. I don't know if there is a charge. Tell me the other way around

**Comment by ashishkaransingh** [comment]
> Can it be used for free? .. I don't know if there is a charge. Tell me the other way around

We have an enterprise license.
Plus it works as said when we test manually we do see incidents and events in Servicenow.

**Comment by nsano-rururu** [comment]
Do you mean that you are using it with docker?

**Comment by ashishkaransingh** [comment]
> Do you mean that you are using it with docker?
Yes, with docker

**Comment by nsano-rururu** [comment]
>We have an enterprise license.
Plus it works as said when we test manually we do see incidents and events in Servicenow.

Saas?

**Comment by ashishkaransingh** [comment]
well our company uses Servicenow for Incident management.
And we are creating alerts for Elasticsearch sourced data.

**Comment by ashishkaransingh** [comment]
Saas - software as a service, sorry i did not follow?

**Comment by ashishkaransingh** [comment]
I am using this:
docker pull praecoapp/elastalert-server

**Comment by nsano-rururu** [comment]
To be honest, I'm not interested in ServiceNow.

**Comment by nsano-rururu** [comment]
I confirmed the transmission with ms teams in Test, but it works. That doesn't seem to be a problem. If servicenow doesn't work, it will be removed from the Praeco settings screen feature at the next release.

**Comment by ashishkaransingh** [comment]
Well I think servicenow is a very nice and cool option there.. give me sometime i will give you an update it works it just i am not able to figure it out yet... please do not remove it!

**Comment by nsano-rururu** [comment]
I will leave it. Also, the difference between the servicenow settings output by Praeco and the rules created by hand with elastalert alone. I'm wondering what happens when I try to run the test with elaetalert alone.

**Comment by ashishkaransingh** [comment]
I was thinking exactly that. But did not know how to run it from inside docker...?

**Comment by ashishkaransingh** [comment]
like this python elastalert/elastalert.py?
Or
elastalert --verbose --rule test-count.yaml --config filename.yaml

**Comment by nsano-rururu** [comment]
Inside the elastalert-server container

```
[CORP\sano@a-ngft53r34ong praeco]$ docker exec -it elastalert sh
/opt/elastalert-server $ ls
config              index.js            package-lock.json   patches             scripts
elastalert_modules  node_modules        package.json        rule_templates      src
/opt/elastalert-server $ pwd
/opt/elastalert-server
/opt/elastalert-server $ cd ..
/opt $ ls
elastalert         elastalert-server  yarn-v1.22.5
/opt $ cd elastalert
/opt/elastalert $ ls
Dockerfile-test           changelog.md              docs                      pass                      rule_templates            setup.py
LICENSE                   config.yaml               elastalert                pytest.ini                rules                     supervisord.conf.example
Makefile                  config.yaml.example       elastalert_modules        requirements-dev.txt      server_data               tests
README.md                 docker-compose.yml        example_rules             requirements.txt          setup.cfg                 tox.ini
/opt/elastalert $ pwd
/opt/elastalert
/opt/elastalert $ python3 -V
Python 3.8.7
/opt/elastalert $ 
````

**Comment by ashishkaransingh** [comment]
ok... sudo docker exec -it containername /bin/sh

**Comment by nsano-rururu** [comment]
ServiceNow開発者インスタンスの作成
https://qiita.com/htshozawa/items/e23a39926b876ccb0a42

I got a ServiceNow developer instance and ran a test from Praeco. There was no problem.

![1](https://user-images.githubusercontent.com/22293449/110816209-7acc1100-82ce-11eb-8bb2-689ac6aef4ff.PNG)
![2](https://user-images.githubusercontent.com/22293449/110816221-7ef82e80-82ce-11eb-84ce-9458a9d20d5a.PNG)
![3](https://user-images.githubusercontent.com/22293449/110816232-81f31f00-82ce-11eb-97ed-77ea7c8020fb.PNG)
![4](https://user-images.githubusercontent.com/22293449/110816253-86b7d300-82ce-11eb-8bab-fa8d89b6a8da.PNG)

**Comment by nsano-rururu** [comment]
"servicenow_proxy" is not set from the Praeco screen, but if you need to set the proxy, you can set it in the next version.

https://elastalert.readthedocs.io/en/latest/ruletypes.html#servicenow

**Comment by ashishkaransingh** [comment]
that's interesting... you re sending it to incident API

**Comment by ashishkaransingh** [comment]
which take a different payload

**Comment by ashishkaransingh** [comment]
The only difference is that I am trying the following payload in /elastalert/elastalert/alerts.py for class 
ServiceNowAlerter(Alerter):

-currently everything is hardcoded
I was sending it to 
https://myinstance.service-now.com/api/global/em/jsonv2


payload = {
                "records": [ {
                    "source": "alerts_Team",
                    "event_class": "Log_Analytics",
                    "node": "node",
                    "metric_name": "get_rulename",
                    "type": "event-count",
                    "resource": "resource",
                    "severity": "3",
                    "description": "desc",
                    "additional_info": "hardcoded_description"
                } ]}

**Comment by ashishkaransingh** [comment]
I was mucking around to see if i can send it to events api by changing the payload.
Outcome: Yes i was able to but only with test button.
Anything you can point me to would be great!

**Comment by ashishkaransingh** [comment]
I tried running the rule directly from elastalert, getting this error

![image](https://user-images.githubusercontent.com/29729110/110818193-0d5eb700-82b3-11eb-9a66-666f33cd590e.png)

**Comment by ashishkaransingh** [comment]
Yesterday I started with Error 500 but there was a point i was able to send alerts "on-schedule" but in Praeco it was showing as "Unknown" for Alert Type.
Therefore i pulled a new image to test.. and today i am back to Error 500

**Comment by nsano-rururu** [comment]
I saved the rules and the alert flew normally. I'm sleepy, so I go to bed.
![5](https://user-images.githubusercontent.com/22293449/110819457-8d941500-82d1-11eb-848c-5ca89383a5a3.PNG)

**Comment by ashishkaransingh** [comment]
Good night

**Comment by nsano-rururu** [comment]
Alert notifications are elastalert, so it's not a praeco issue. Ask the yelp / elastalert issue if you want to modify it or if it doesn't work.

**Comment by ashishkaransingh** [comment]
Yes that's right, i will ask help from yelp wow see even this rhymes.
Thanks a Lot for spending time on this with me.

**Comment by ashishkaransingh** [comment]
Sorry had to reopen cause i tried running

> I will leave it. Also, the difference between the servicenow settings output by Praeco and the rules created by hand with elastalert alone. I'm wondering what happens when I try to run the test with elaetalert alone.

I was able to send alerts directly from elastalert, i could see Alert Log in Praeco with status Sent.

![image](https://user-images.githubusercontent.com/29729110/110848979-b4077f80-82d4-11eb-9e98-b250795ec20c.png)

**Comment by nsano-rururu** [comment]
Is that so. Yes, close.

**Comment by nsano-rururu** [comment]
yelp/elastalert It's no longer maintained, so it's better to use jertel/elastalert, which is forked and maintained.
https://github.com/jertel/elastalert
https://github.com/jertel/elastalert-docker
