### ISSUE TITLE
Index_not_found exception found right after install

### ISSUE THREAD

**Issue by klausagnoletti** [johnsusek/praeco#336]
Hi,

I just installed praeco via docker-compose. And it doesn't work. Also, I am completely new in elastalert and/or praco so I don't really know what this writebak_index is that it's complaining about. Other than that's the default in praeco and that I guess it should have been created. But it doesn't. And also, there's no `elastalert-create-index` script for me to create one manually. And I can't find it anywhere to fox the problem. So I'm stuck. (I also tried changing the writeback_index to elastalert_statuts, just too see what happened. That didn't work either, complaining about a request too big. And that seemed unwise to try and set up a max limit for that).

I am running everything in docker, also the elstic stack. I start everything via docker-compose, based on the instructions for installing. This is the error I get. Underneath I will paste the relevant parts of my docker-compose. I run Elastic 7.11.2.

13:57:20.466Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: NotFoundError(404, 'index_not_found_exception', 'no such index [praeco_elastalert_status]', praeco_elastalert_status, index_or_alias) {'query': {'bool': {'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2021-03-22T13:57:20.459031Z', 'to': '2021-03-24T13:57:20.459055Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1654, in find_recent_pending_alerts
        res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
        return func(*args, params=params, headers=headers, **kwargs)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1657, in search
        return self.transport.perform_request(
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
        raise e
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
        status, headers_response, data = connection.perform_request(
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 204, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
    elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [praeco_elastalert_status]', praeco_elastalert_status, index_or_alias)

docker-compose.yml:
elastalert:
    image: 'praecoapp/elastalert-server'
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    volumes:
      - /mnt/cache/appdata/praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - /mnt/cache/appdata/praeco/config/api.config.json:/opt/elastalert-server/config.json
      - /mnt/cache/appdata/praeco/rules:/opt/elastalert/rules
      - /mnt/cache/appdata/praeco/rule_templates:/opt/elastalert/rule_templates
      - /mnt/cache/cert/elasticsearch.agnoletti.net/:/certs:ro
    extra_hosts:
          - 'elasticsearch:${ELASTICSEARCH_IP}'
    networks:
         macvlan-lan:
               ipv4_address: 10.20.30.193
    ports:
      - "3030:3030"
      - "3333:3333"
  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
    volumes:
      - /mnt/cache/appdata/praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - /mnt/cache/appdata/praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/cache/appdata/praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
         macvlan-lan:
               ipv4_address: 10.20.30.194

Obviously I have changed a few things to fit my enviroment - most notably the network type. But it seems like it's able to connest to Elastic allright.

Can someone help me out?

/klaus

**Comment by nsano-rururu** [comment]
How can I get such a strange error? Are you talented?

**Comment by nsano-rururu** [comment]
This is the setting I'm using
https://github.com/johnsusek/praeco/wiki/docker-compose-sample(telegram)

**Comment by nsano-rururu** [comment]
If there is no problem with the settings, elastalert-server will be created if the index specified in the configuration file does not exist in elasticsrach, and if there is, it will not be created newly. The settings are probably not good.

**Comment by nsano-rururu** [comment]
https://user-images.githubusercontent.com/611996/52892144-90a19300-3155-11e9-8050-cb4a440411a4.png

**Comment by nsano-rururu** [comment]
By the way, if you don't want to use Praeco and ElastAlertServer, but just want to use ElastAlert with Docker, I think the following are more suitable for your needs.
https://github.com/jertel/elastalert-docker

**Comment by nsano-rururu** [comment]
Elasticsearch 7.11.2, kibana 7.11.2, elastalert-server and praeco confirmed in the latest version

Warning is output as ERROR. The elasticsearch-py used by elastalert warns that it is using the setting that will disappear in the next version. Next version = Elasticsearch 8, so I don't care now. In the first place, elastalert will never work with Elasticsearch 8 unless it supports Elasticsearch 8.

```
14:48:32.855Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
14:48:32.857Z  INFO elastalert-server: Router:  Listening for GET request on /config.
14:48:32.862Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
14:48:32.862Z  INFO elastalert-server: ProcessController:  Creating index
14:48:38.131Z  INFO elastalert-server:
    ProcessController:  Elastic Version: 7.11.2
    Reading Elastic 6 index mappings:
    Reading index mapping 'es_mappings/6/silence.json'
    Reading index mapping 'es_mappings/6/elastalert_status.json'
    Reading index mapping 'es_mappings/6/elastalert.json'
    Reading index mapping 'es_mappings/6/past_elastalert.json'
    Reading index mapping 'es_mappings/6/elastalert_error.json'
    New index praeco_elastalert_status created
    Done!
    
14:48:38.132Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: Camel case format name dateOptionalTime is deprecated and will be removed in a future version. Use snake case name date_optional_time instead.
      warnings.warn(message, category=ElasticsearchWarning)
    /home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py:200: ElasticsearchWarning: [types removal] Using include_type_name in put mapping requests is deprecated. The parameter will be removed in the next major version.
      warnings.warn(message, category=ElasticsearchWarning)
    
14:48:38.132Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
14:48:38.133Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
14:48:38.144Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 220)
14:48:38.149Z  INFO elastalert-server: Server:  Server listening on port 3030
14:48:38.151Z  INFO elastalert-server: Server:  Websocket listening on port 3333
14:48:38.153Z  INFO elastalert-server: Server:  Server started
14:48:50.896Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
14:49:21.246Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.

[CORP\sano@a-ngft53r34ong es]$ curl -XGET 'localhost:9200/_cat/indices?v' | grep praeco
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1536  100  1536    0     0   150k      0 --:--:-- --:--:-- --:--:--  150k
yellow open   praeco_elastalert_status_status  nfZFGjzcT-qHaMpBQjrVgw   1   1          4            0     14.7kb         14.7kb
yellow open   praeco_elastalert_status_silence NiFlIPYITtKNM-pMnAahcw   1   1          1            0      4.1kb          4.1kb
yellow open   praeco_elastalert_status_error   MyPWDE5MRBKem-UhnMxmqw   1   1          0            0       208b           208b
yellow open   praeco_elastalert_status_past    TNYPfjhAQKKiKyC2Zfe0Kw   1   1          0            0       208b           208b
yellow open   praeco_elastalert_status         JJZJh7yuRj-9dqIm-XMIRA   1   1          1            0      9.6kb          9.6kb
[CORP\sano@a-ngft53r34ong es]$ 
```

![キャプチャ](https://user-images.githubusercontent.com/22293449/112331530-54f63180-8cfc-11eb-9b50-114f5877d765.PNG)
ms teams
![2](https://user-images.githubusercontent.com/22293449/112331573-5fb0c680-8cfc-11eb-8c6e-e6c52500df7b.PNG)

**Comment by klausagnoletti** [comment]
Hey and thanks for replying so promptly

I have no idea what I did to mess it up so thoroughly :)

As I understand it, Elastalert makes no sense without the UI - atleast not to me.

Thanks for the explanation and for linking to your settings. I'll try it out and let you know how it goes so please wait a few days before closing the issue.

/k

**Comment by nsano-rururu** [comment]
>As I understand it, Elastalert makes no sense without the UI - atleast not to me.

Praeco does not support the settings of all the functions of ElastAlert, so depending on the settings you want to use, you may have to use it without Praeco.

Main unsupported items

- Spike Aggregation
- Percentage Match
- Email html support
- HTTP POST option settings
- PagerDuty
- Ops Genie

Please refer to the link below for the response status of Praeco alerts.
https://github.com/johnsusek/praeco/wiki/ElastAlert-Alerts-support-status

**Comment by nsano-rururu** [comment]
>As I understand it, Elastalert makes no sense without the UI - atleast not to me

Make sure that you can output the settings you want to use before deciding whether to use them. If you can't output it, it's garbage. If you have it, you can add functions and you are not obliged to do so. I never promise to do it.

**Comment by nsano-rururu** [comment]
Close once. Please reopen if there is a problem.

**Comment by klausagnoletti** [comment]
I have followed the instructions in the telegram link above and adapted them to my setup. And the exact same thing happens: It registers that the praeco_elastalert_status index doesn't exist in Elasticsearch. And halts. I doesn't create it like it should.

```12:04:30.466Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:POST https://elasticsearch.agnoletti.net:9200/praeco_elastalert_status/_search?size=1000 [status:404 request:0.007s]
12:04:30.469Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: NotFoundError(404, 'index_not_found_exception', 'no such index [praeco_elastalert_status]', praeco_elastalert_status, index_or_alias) {'query': {'bool': {'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2021-03-30T12:04:30.401801Z', 'to': '2021-04-01T12:04:30.401839Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1654, in find_recent_pending_alerts
        res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
        return func(*args, params=params, headers=headers, **kwargs)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1657, in search
        return self.transport.perform_request(
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
        raise e
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
        status, headers_response, data = connection.perform_request(
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 204, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
    elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [praeco_elastalert_status]', praeco_elastalert_status, index_or_alias)```

So now what?

Thanks :-)

/k

**Comment by nsano-rururu** [comment]
@klausagnoletti 

I do not know.

**Comment by klausagnoletti** [comment]
That makes two of us :-)

/k

**Comment by nsano-rururu** [comment]
The following settings may not work, but I'm not sure.

```
extra_hosts:
- 'elasticsearch:${ELASTICSEARCH_IP}'
```

**Comment by nsano-rururu** [comment]
@klausagnoletti

Please give up using praeco and elastalert-server. I don't think it will work with the settings you set.

**Comment by nsano-rururu** [comment]
@klausagnoletti

Would you like to use the following that simply runs elastalert with docker?

ElastAlert-Docker
https://github.com/jertel/elastalert-docker

**Comment by nsano-rururu** [comment]
@klausagnoletti

It's similar to the error I've looked at in the past, but maybe elasticsearch isn't running? Maybe I can't connect yet?
https://qiita.com/rururu_kenken/items/cc78c61bac4f864a81cd

**Comment by nsano-rururu** [comment]
@klausagnoletti

Is it a liar? If you apply the same settings, ElastAlert should go to create an index after you can connect to Elasticsearch. I hate liars.

**Comment by klausagnoletti** [comment]
Ok, first thing first. This is a snippet of the current docker-compose.yaml. I removed the extra_hosts some time ago to align with your configuration:

```    elastalert:
        build:
            context: ../elastalert-server
            dockerfile: Dockerfile
        image: elastalert-server:3.0.0
        restart: unless-stopped
        environment:
            ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
            ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
            ELASTICSEARCH_HOSTS: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
        labels:
            com.centurylinklabs.watchtower.enable: "false"
        depends_on:
            - elasticsearch
        volumes:
            - /mnt/cache/appdata/praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
            - /mnt/cache/appdata/praeco/config/api.config.json:/opt/elastalert-server/config.json
            - /mnt/cache/appdata/praeco/rules:/opt/elastalert/rules
            - /mnt/cache/appdata/praeco/rule_templates:/opt/elastalert/rule_templates
            - /mnt/cache/cert/elasticsearch.agnoletti.net/:/certs:ro
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
            interval: 30s
            timeout: 15s
            retries: 3
            start_period: 200s
        networks:
            macvlan-lan:
                ipv4_address: 10.20.30.193
        ports:
            - "3030:3030"
            - "3333:3333"

    praeco:
        image: praecoapp/praeco
        ports:
            - 8080:8080
        restart: unless-stopped
        labels:
            com.centurylinklabs.watchtower.enable: "false"
        depends_on:
            - elastalert
#    environment:
#      VUE_APP_BASE_URL: /my-path/
        volumes:
            - /mnt/cache/appdata/praeco/public/praeco.config.json:/var/www/html/praeco.config.json
            - /mnt/cache/appdata/praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
            - /mnt/cache/appdata/praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
            interval: 30s
            timeout: 15s
            retries: 3
            start_period: 200s
        networks:
            macvlan-lan:
                ipv4_address: 10.20.30.194
```

Basically, I just want alerting from my Elastic. It doesn't have to be praeco and elastalert. I am not aware of anything else that works with current versions of the Elastic stack. Are you?

I took a look at the other elastalert when you pointed my attention to it earlier. I haven't tried it though. Would it work with praeco?

The issue you are linking to, does indeed look similar. But Elasticsearch IS running and works fine. It has been running all the time since I've been testing this. It accepts and processess logs from three instances of elastic-agent as we speak. 

And no, this is not an april's fool joke. Unfortunately :-)

Thanks

/k

**Comment by nsano-rururu** [comment]
I see. I haven't confirmed it in that configuration, but in the case of a cluster configuration, I remember seeing ha-proxy or not using it in the issue of elastalert.

**Comment by klausagnoletti** [comment]
Thanks - It's not a cluster configuration - I have one Elasticsearch, one Logstash and one Kibana.

I will try the other elastalert and see how it goes :)

/k

**Comment by nsano-rururu** [comment]
The following are notifications for alerts based on Elasticsearch data.

**Watcher**

https://www.elastic.co/guide/en/kibana/7.8/watcher-ui.html

**Alerting and action settings in Kibana**

[Alerts and Actions](https://www.elastic.co/guide/en/kibana/current/managing-alerts-and-actions.html)
[Managing Alerts](https://www.elastic.co/guide/en/kibana/current/alert-management.html)
[Alert details](https://www.elastic.co/guide/en/kibana/current/alert-details.html)
[Managing Connectors](https://www.elastic.co/guide/en/kibana/current/connector-management.html)

**Open Distro for Elasticsearch**

[Alerting](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/)

**Grafana**

Perform alerting on data in Elasticsearch with Grafana
https://grafana.com/docs/grafana/latest/alerting/
https://grafana.com/docs/grafana/latest/alerting/notifications/

**Comment by nsano-rururu** [comment]
I think Watcher and Alerting and action settings in Kibana are paid

**Comment by nsano-rururu** [comment]
At the point when elastalert cannot connect to elasticsearch normally, it is very likely that the elastalert-docker introduced in the link will not work. It's not a problem with praeco or elastalert-server, but because there is an error that elastalert cannot connect. I want you to understand that.

**Comment by klausagnoletti** [comment]
Yeah, no problem.

**Comment by klausagnoletti** [comment]
I tried the other elastalert and something did happen. Most notably, it created the missing index for me. But didn't work, so I switched back. 

And now that the `praeco_elastalert_status` exists, something else happens:

```
Error:` socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',

  config: {
    url: 'http://elasticsearch:9200',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
....... And a lot more errors which doesn't look relevant..
```

Obviously, the interesting part here is that my entire stack is running SSL and that I have configured elastalert for that. So why does it connect via http - and to the wrong hostname? Is something hardcoded somewhere?

Anyway, to me that looks like the root cause to all my problems. So how do I fix that? 

Thanks!

/

**Comment by nsano-rururu** [comment]
I thought about it with my missing head. You're the default configuration file.

elastalert.yaml
https://github.com/johnsusek/praeco/blob/master/config/elastalert.yaml

elastalert configuration file. There is a place to write connection information of elasticsearch
elastalert is made with python.

```
 The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```
api.config.json
https://github.com/johnsusek/praeco/blob/master/config/api.config.json

elastalert-server configuration file. There is a place to write connection information of elasticsearch.
elastalert-server is made with node.js. Since there is also a process to connect to elasticsearch and acquire information without going through elastalert, connection information of elasticsearch is required.

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```

**Comment by nsano-rururu** [comment]
elastalert.yaml

es_host: elasticsearch
es_port: 9200
#es_username: someusername
#es_password: somepassword

api.config.json

  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,

**Comment by klausagnoletti** [comment]
Thanks for your reply.

As I said, everything has been configured correctly already - which is why I suggest a hardcoded file somewhere.

This is the snippet from docker-compose.yml which mounts the config files:
```
        volumes:
            - /mnt/cache/appdata/praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
            - /mnt/cache/appdata/praeco/config/api.config.json:/opt/elastalert-server/config.json
            - /mnt/cache/appdata/praeco/rules:/opt/elastalert/rules
            - /mnt/cache/appdata/praeco/rule_templates:/opt/elastalert/rule_templates
```
And here's the relevant parts of api.config.json:

```
  "es_host": "elasticsearch.agnoletti.net",
  "es_port": 9200,
  "es_username": "xxxx",
  "es_password": "xxxx",
  "es_ssl": true,
  "es_ca_certs": "/certs/ca.pem", // Path to ca for ElasticSearch (SSL must be enabled)
  "es_client_cert": "/certs/cert.pem", // Path to cert for ElasticSearch (SSL must be enabled)
  "es_client_key": "/certs/key.pem", // Path to key for ElasticSearch (SSL must be enabled)
```
And lastly the relevant parts of elastalert.yaml:
```
es_host: elasticsearch.agnoletti.net
es_port: 9200
use_ssl: True
verify_certs: True
es_username: xxxx
es_password: xxxx
```
So as I see it either I am mapping the wrong files or the connection string is hardcoded or set in another config file somehere.

Do you agree?

Thanks :-)

/k

**Comment by nsano-rururu** [comment]
>Do you agree?

You should look it up yourself because it's not a school

**Comment by klausagnoletti** [comment]
I tried to but couldn't find anything anywhere. Also, I am not a programmer, so I wouldn't be able to understand the code.

Thanks

/k

**Comment by nsano-rururu** [comment]
The ssl file doesn't seem to be mounted so that it can be referenced from each docker container.

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/issues/213

**Comment by nsano-rururu** [comment]
@klausagnoletti 

Regarding ssl connection, we confirmed the operation in the past inquiry, so see the following contents
https://github.com/johnsusek/praeco/issues/319#issuecomment-778284389

**Comment by nsano-rururu** [comment]
>I tried to but couldn't find anything anywhere. Also, I am not a programmer, so I wouldn't be able to understand the code.

So what? .. Don't make excuses. Inexperienced? Right now. What you will experience.

**Comment by klausagnoletti** [comment]
I merely asked the question to get a second opinion from someone who knows the code better than I. I don't understand why that qualifies for a rude answer like that.

/k

**Comment by nsano-rururu** [comment]
I can't do it for you.

**Comment by nsano-rururu** [comment]
Someone who knows the code. Not in. I don't see users answering issues. This OSS is over. If you really want to use it, you have to read it, understand it, and solve it.

**Comment by klausagnoletti** [comment]
So that is a weird reply and didn't solve the problem - or the suspected bug if using this in a SSL-only stack.

**Comment by klausagnoletti** [comment]
Following that logic, I wouldn't be able to use Linux except if I am a highly skilled c-programmer. Doesn't make sense. But thanks for putting time and effort into a very useful OSS project. If you manage to get it to work.

/k

**Comment by nsano-rururu** [comment]
You don't have to be an advanced programmer to use linux. It's not that difficult. I also know people who operate with ssl configuration of praeco and elastalert-server. I wonder what the altitude is. I think you'll get used to it if you use it every day.

**Comment by nsano-rururu** [comment]
>If you manage to get it to work.

Do not use elastalert.

**Comment by nsano-rururu** [comment]
It is no longer maintained.
