### ISSUE TITLE
Failed on creating index ElasticSearch 6.4

### ISSUE THREAD

**Issue by arsalan993** [johnsusek/praeco#342]
Before I share the error below. When I ran the latest version of ElastAlert it ran successfully but unable to get matches and hit. 
Upon running your Docker container with the correct configuration I am getting this error
`07:29:20.245Z  INFO elastalert-server: ProcessController:  Creating index
elastalert_1  | 07:29:21.792Z  INFO elastalert-server:
elastalert_1  |     ProcessController:  Elastic Version: 6.4.2
elastalert_1  |     Reading Elastic 6 index mappings:
elastalert_1  |     Reading index mapping 'es_mappings/6/silence.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_status.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/past_elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_error.json'
elastalert_1  |     
elastalert_1  | 07:29:21.792Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 268, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 264, in main
elastalert_1  |         create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 30, in create_index_mappings
elastalert_1  |         if es_index.exists(ea_index):
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
elastalert_1  |         return func(*args, params=params, headers=headers, **kwargs)
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 332, in exists
elastalert_1  |         return self.transport.perform_request(
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
elastalert_1  |         raise e
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
elastalert_1  |         status, headers_response, data = connection.perform_request(
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 204, in perform_request
elastalert_1  |         self._raise_error(response.status_code, raw_data)
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 322, in _raise_error
elastalert_1  |         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elastalert_1  |     elasticsearch.exceptions.RequestError: RequestError(400, '')
elastalert_1  |     
elastalert_1  | 07:29:21.792Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
elastalert_1  | 07:29:21.793Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
elastalert_1  | 07:29:21.793Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
`

**Comment by nsano-rururu** [comment]
Elasticsearch 6.4.2？

**Comment by nsano-rururu** [comment]
I haven't run it on Elasticsearch 6, so let's check it.

**Comment by arsalan993** [comment]
> Elasticsearch 6.4.2？

yes

**Comment by nsano-rururu** [comment]
@arsalan993 

I understand the cause.
In the current elastalert-server docker image, python's elasticsearch library is installed with elasticsearch> = 7.0.0, <8.0.0. As a result, elasticsearch 6.x is completely stuck.
I confirmed that if I set elasticsearch library of python to elasticsearch == 7.0.0, it works fine with elasticsearch 6.2.4 and alerts are also notified. In the future, we plan to provide docker image tags with "_es6" at the end. For the current version, we will upload the docker image to docker hub, so please be patient.

**Comment by nsano-rururu** [comment]
@arsalan993

Please use the docker image below.

praecoapp/elastalert-server:20200404_es6

**Comment by arsalan993** [comment]
thank you
