### ISSUE TITLE
connect to Elastic search using domain/URL

### ISSUE THREAD

**Issue by arsalan993** [johnsusek/praeco#343]
Under the following command `export PRAECO_ELASTICSEARCH=<your elasticsearch ip>` we are required to put IP of the server where ES is deployed. It worked fine as long as I provide the correct IP but once I insert the domain it is unable to connect. 

Is is possible we can enable to connect via domain/URL of the ES server.

**Comment by nsano-rururu** [comment]
Actually. I've never used that setting.

**Comment by nsano-rururu** [comment]
Settings I'm using (docker-compose, etc.)
https://github.com/johnsusek/praeco/wiki/docker-compose-sample(telegram)

**Comment by arsalan993** [comment]
Can you enable or bring changes such that when we pass url to ES server it should be able to connect to it rather than passing ip

**Comment by nsano-rururu** [comment]
Isn't it good to set the server that uses es_host, es_port, es_username, es_password in the following files?

elastalert settings ・ ・ ・ python program
https://github.com/johnsusek/praeco/blob/master/config/elastalert.yaml

elastalert-server settings ・ ・ ・ API created by node.js
https://github.com/johnsusek/praeco/blob/master/config/api.config.json

**Comment by arsalan993** [comment]
Yes i updated those files with right credentials and used url instead of IP but when i set docker-compose up it still asks for IP in this particular variable PRAECO_ELASTICSEARCH

**Comment by arsalan993** [comment]
`ERROR: for elastalert  Cannot create container for service elastalert: invalid IP address in add-host: ""
ERROR: Encountered errors while bringing up the project.`

**Comment by nsano-rururu** [comment]
I'm busy with work, so I'll solve it myself

**Comment by nsano-rururu** [comment]
Are elasticsearch and elastalert-server different hosts? .. Both are docker? ..

**Comment by nsano-rururu** [comment]
Multi-Host Overlay Networking with Etcd
https://docker-k8s-lab.readthedocs.io/en/latest/docker/docker-etcd.html

I think you should ask questions on docker or docker-compose isssue.

**Comment by arsalan993** [comment]
No Sir They steps that your have mentioned are

1. `export PRAECO_ELASTICSEARCH=<your elasticsearch ip>`
2. updates the ES credentials in `config/elastalert.yaml` and `config/api.config.json`
3. `docker-compose up`

Setting this variable `PRAECO_ELASTICSEARCH`  to the ip of ES server it works file even though i provide ES server URL in config files. 
But as soon as i set the variable `PRAECO_ELASTICSEARCH` to ES server url it get an error that it is invalid `invalid IP address in add-host`. I guess it is unable to resolve this URL. 

And if i dont set this variable i still get same error `invalid IP address in add-host`

**Comment by nsano-rururu** [comment]
Is that so. Goodbye.

**Comment by nsano-rururu** [comment]
I haven't done export PRAECO_ELASTICSEARCH = <your elasticsearch ip>. I do not understand.

**Comment by nsano-rururu** [comment]
Wasted time

**Comment by nsano-rururu** [comment]
It meant that I could erase the following and try it.
`` ```
  extra_hosts:
       --'elasticsearch: $ {PRAECO_ELASTICSEARCH}'
`` ```

**Comment by arsalan993** [comment]
I dont think issue is resolved .

**Comment by nsano-rururu** [comment]
Please solve it yourself

**Comment by nsano-rururu** [comment]
I don't want to get involved

**Comment by nsano-rururu** [comment]
Everything in the readme is there and you are not obliged to answer the question
