### ISSUE TITLE
using query_key value in use_count_query

### ISSUE THREAD

**Issue by babakahmadi** [johnsusek/praeco#344]
when I use `use_count_query` in my rule, I cannot access my `query_key` value in version 1.8.5 for using in alert text argument. In version 1.5.x I could use `key` term in text_argument to access my `query_key` value.
Is there any specific term for access `query_key` when I use `use_count_query`?

**Comment by nsano-rururu** [comment]
Please continue to use the old version without using the new version.

**Comment by nsano-rururu** [comment]
I have no plans to add or modify any features right now.

**Comment by nsano-rururu** [comment]
query_key is now an array instead of a string. It may be the effect

before

query_key: "xxx"

after

```
query_key:
  - "xxx"
```
