### ISSUE TITLE
doc_type problem in options

### ISSUE THREAD

**Issue by babakahmadi** [johnsusek/praeco#346]
for use_count_query or use_term_query, doc type is forcing to select `properties` , while it can be `_type` in elasticsearch index and it can be any kind of string.

<img width="309" alt="praeco" src="https://user-images.githubusercontent.com/10725629/115354794-430a9000-a1cf-11eb-9e11-668ce25e97c8.PNG">

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/2424

**Comment by nsano-rururu** [comment]
doc_type was completely deprecated in ES > 7.x, however when I use use_count_query or use_terms_query in my rules, rule validation fails:

**Comment by nsano-rururu** [comment]
If ES> 7, I feel that it is correct to disable it.

**Comment by nsano-rururu** [comment]
Praeco does not know the version of elasticserach that is connected without modifying elastalert-server.

**Comment by nsano-rururu** [comment]
doc_typeはelasticsearchでありでので、複素しいElasticsearchのその変化で設定あり・表の規制の機能は要

**Comment by nsano-rururu** [comment]
Since doc_type will be abolished in elasticsearch, it is necessary to have a control function that can or cannot be set by the version of elasticsearch that is connected.
