### ISSUE TITLE
Uncaught exception running rule foo: deprecated_search() got an unexpected keyword argument 'headers'

### ISSUE THREAD

**Issue by premierpsp** [johnsusek/praeco#347]
Hi Guys:
When i set my rule, i got this error:

 05:41:57.829Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  ERROR:root:Traceback (most recent call last):
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 1283, in handle_rule_execution
elastalert_1  |         num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 902, in run_rule
elastalert_1  |         if not self.run_query(rule, tmp_endtime, endtime):
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 636, in run_query
elastalert_1  |         data = self.get_hits_aggregation(rule, start, end, index, rule.get('query_key', None))
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 569, in get_hits_aggregation
elastalert_1  |         res = self.thread_data.current_es.deprecated_search(index=index, doc_type=rule.get('doc_type'),
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped
elastalert_1  |         return func(*args, params=params, headers=headers, **kwargs)
elastalert_1  |     TypeError: deprecated_search() got an unexpected keyword argument 'headers'
elastalert_1  |
elastalert_1  |     ERROR:root:Uncaught exception running rule LALA: deprecated_search() got an unexpected keyword argument 'headers'

Here is my rule:
 __praeco_full_path: "foo"
alert:
  - "ms_teams"
alert_subject: "aaa"
alert_text: "aaa"
alert_text_type: "alert_text_only"
doc_type: "_meta"
filter:
  - query:
      query_string:
        query: host.name:"foo"
generate_kibana_discover_url: false
import: "BaseRule.config"
index: "metricbeat-*"
is_enabled: true
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 10
limit_execution: "*/1 * * * *"
match_enhancements: []
max_threshold: 0.8
metric_agg_key: "system.cpu.total.norm.pct"
metric_agg_type: "avg"
min_threshold: 1.1
ms_teams_alert_summary: "ElastAlert Message"
ms_teams_theme_color: "#ff0000"
ms_teams_webhook_url: 
name: "foo"
realert:
  minutes: 5
slack_attach_kibana_discover_url: false
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "metric_aggregation"
use_strftime_index: false

Thank you

**Comment by nsano-rururu** [comment]
If you are using elasticsearch 6.x, please use the docker image below.

praecoapp/elastalert-server:20200404_es6

**Comment by nsano-rururu** [comment]
Is the docker image of elastalert-server up to date?

**Comment by nsano-rururu** [comment]
The docker image for praecoapp / elastalert-server: 20200404_es6 is pip install elasticsearch = 7.0.0.

**Comment by nsano-rururu** [comment]
If you can't solve it by the method you told us, there is no solution at this time. It's a problem on the Elast Alert side. I'm not the maintainer of ElastAlert

**Comment by nsano-rururu** [comment]
doc_type is deprecated in ES7.x and will disappear completely in ES8, but maybe the "doc_type:" _meta "" specification is the problem.

**Comment by nsano-rururu** [comment]
elastalert hasn't been maintained for a long time, so it's definitely not elasticsearch 8.x compatible. I think you should start looking for another tool in the future.

**Comment by premierpsp** [comment]
> Hi @nsano-rururu, i´m using elasticsearch 7.12 and files are up to date.
> 
> I'll try with elasticsearch = 7.0.0

@nsano-rururu Using elasticsearch=7.0.0 it worked like a charm! 

Thank you and long life to thoese great apps

**Comment by nsano-rururu** [comment]
@premierpsp

I also set `praecoapp/elastalert-server:latest` to `elasticsearch==7.0.0`.

**Comment by premierpsp** [comment]
> @premierpsp
> 
> I also set `praecoapp/elastalert-server:latest` to `elasticsearch==7.0.0`.

I’m checking praeco with the version of elasticsearch (7.12). Apparently there is something in the rule structure that elastalert doesn’t like

**Comment by nsano-rururu** [comment]
@premierpsp

Another problem?

**Comment by nsano-rururu** [comment]
I don't know because it's not Esper.
