### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by zemun-png** [johnsusek/praeco#348]
**Hi,
I've this problem in send Alert:**
 Error connecting to SMTP host: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

**My  rules/BaseRule.config:**
----------------------------------------------------------------------------------------------------------
smtp_host: "Mail_Server_IP"
smtp_port: 587
smtp_ssl : true
smtp_auth_file: '/opt/elastalert/smtp/smtp_auth_file.yml'
----------------------------------------------------------------------------------------------------------
**/smtp/smtp_auth_file.yml:**
user: "user@domain.tr"
password: "my_password"

**Comment by nsano-rururu** [comment]
I do not know.
This error occurs if you are not using the correct port number.
Is the target mail server set to use 587?

**Comment by nsano-rururu** [comment]
Is "Mail_Server_IP" a global IP address that can be communicated from the docker host?

**Comment by zemun-png** [comment]
**yes i changed to true port and now i recevied this error:**
 Error connecting to SMTP host: (535, b'5.7.3 Authentication unsuccessful')

**Comment by nsano-rururu** [comment]
I do not know.

**Comment by nsano-rururu** [comment]
Is /opt/elastalert/smtp/smtp_auth_file.yml mounted when the docker container of elastalert-server is started?

For port 587, smtp_ssl: should be false
For port 465, smtp_ssl: should be true
Why is there no from_addr specified? /opt/elastalert/smtp/smtp_auth_file.yml should be the authentication information of the address specified by from_addr.

**Comment by nsano-rururu** [comment]
I can't help when I don't even tell you what I'm using for my mail server.

**Comment by nsano-rururu** [comment]
I have confirmed that there is a problem with port 587 in office 365 and gmail. elastalet problem.

**Comment by zemun-png** [comment]
I am using praeco/elastalert docker to connect elasticsearch.
for send mail i set upper configuration but i am recevied this error and i have telnet for ip and port to mailserver .

**Comment by nsano-rururu** [comment]
As a reminder, isn't it the setting that allows you to connect to the target mail server with the following email address and password?

```
/smtp/smtp_auth_file.yml:
user: "user@domain.tr"
password: "my_password"
```

**Comment by nsano-rururu** [comment]
That's all the information I can provide. Please solve it by yourself.

**Comment by nsano-rururu** [comment]
elastalert alert email is buggy and not recommended
