### ISSUE TITLE
Error while connecting to ES 6.4

### ISSUE THREAD

**Issue by arsalan993** [johnsusek/praeco#355]
I have two ES 6.4 databases. On one of it connects sucessfully while on other one it throws this error

```
elastalert_1  | 08:32:23.613Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 08:32:23.617Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
elastalert_1  | 08:32:23.617Z  INFO elastalert-server: ProcessController:  Creating index
elastalert_1  | 08:32:24.229Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 268, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 250, in main
elastalert_1  |         es = Elasticsearch(
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 206, in __init__
elastalert_1  |         self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 108, in __init__
elastalert_1  |         self.set_connections(hosts)
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 157, in set_connections
elastalert_1  |         connections = list(zip(connections, hosts))
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 154, in _create_connection
elastalert_1  |         return self.connection_class(**kwargs)
elastalert_1  |       File "/home/node/.local/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 46, in __init__
elastalert_1  |         self.base_url = 'http%s://%s:%d%s' % (
elastalert_1  |     TypeError: %d format: a number is required, not str
elastalert_1  |     
elastalert_1  | 08:32:24.229Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
```
Using ES python libraries i am able to connect to both and upload dataset and templates.. issue only comes with i connect via Elastalert via Praeco .. 
for Elastalert i am using the docker image you shared 

```
elastalert:
    image : 'praecoapp/elastalert-server:20200404_es6'
```

**Comment by nsano-rururu** [comment]
Do you mean that there are multiple ESs? .. I don't support it.

**Comment by nsano-rururu** [comment]
I'm thinking of stopping support for ES 6. Because I haven't used it at all.

**Comment by nsano-rururu** [comment]
We do not support unsupported usage

**Comment by nsano-rururu** [comment]
Even though I couldn't connect in the first place, I think the allegations are terrible.

**Comment by arsalan993** [comment]
Definitely there are two seperate deployement of Paeco one for first ES server and other for 2nd ES server.. 
both ES servers are 6.4 .

Sir you are too agressive. I am asked questions respectfully and you take it too personal . Plz relax 
I am just asking if it could be fix at your end..  as i mentioned earlier it run prefect for one server and when i connect to other server it fail and put out the error i shared above

**Comment by nsano-rururu** [comment]
Isn't it strange that it can be fixed without being able to distinguish whether the setting is wrong or a bug? ..

**Comment by nsano-rururu** [comment]
Are you running on the same server? You can't tell without information about docker-compose and docker commands. I'm not a god.

**Comment by nsano-rururu** [comment]
What is a separate connection to another server? .. What kind of operation was done with what kind of setting? I don't know at all. Same docker container? Does that mean? .. Is it a connection to two ESs? What I don't understand at all is the real intention.

**Comment by nsano-rururu** [comment]
With only the current information, it seems that the connection is made in a strange way.

**Comment by arsalan993** [comment]
Ok i will look into it further at my end

Arsalan Ahmed

________________________________

**Comment by nsano-rururu** [comment]
In the first place, elastalert-server does not support multiple elasticsearch connections. So is elastalert. When I searched for elastalert issues, I've seen the answer that HAProxy should be used for ES cluster configurations.

**Comment by arsalan993** [comment]
I am trying at all to connect to multiple ES servers.. i connecting to each server one by one.. it was working smoothly with one while failing with other.. so connection was made separately ..

Arsalan Ahmed
________________________________

**Comment by nsano-rururu** [comment]
There is a pull request in elastalert for connecting multiple ESs, but there is currently no sign of being captured.
[feat: suport for multi es instances #3109](https://github.com/Yelp/elastalert/pull/3109)

**Comment by nsano-rururu** [comment]
Conclusion. ElastAlert and ElastAlertServer only support connecting to one ES. If it is supported, it cannot be supported unless both ElastAlert and ElastAlertServer are supported.

**Comment by nsano-rururu** [comment]
No matter how much I investigated, the implementation is so, so the current situation can not be helped.

**Comment by nsano-rururu** [comment]
By the way, maintenance of elastalert is stopped.
