### ISSUE TITLE
'%' Tokens not showing up

### ISSUE THREAD

**Issue by simonherbert** [johnsusek/praeco#358]
Elasticsearch v7.12.1
Praeco: Current master

When I start typing inside "Subject" or "Body Text" a "%", a popup should show up suggesting field names. (as described [here](https://medium.com/@john_8166/praeco-walkthrough-5aada7e078a9))

This doesn't work. Nothing shows up, sometimes the page scrolls up a bit.

Tested with Chrome and Firefox on Linux. Also tested with some older Elasticsearch versions.
Tested Indexes: Logstash Index and Kibana's built-in sample indexes.

**Comment by nsano-rururu** [comment]
I do not understand you.
