### ISSUE TITLE
Scheduling in alarms

### ISSUE THREAD

**Issue by zemun-png** [johnsusek/praeco#360]
Hi Every One i want scheduling all alarm rules:
for example:
**Rule1**: from 7:00 to 19:00 **above 100** and 19:00 to 7:00 **abow 10.**

**Comment by mayconmfl** [comment]
Why not create more than one rule?

**Comment by nsano-rururu** [comment]
You need to split the rule in two. Other supplements.

**Limit Execution**

Execute the rule only at a specific time. Alerts that occur outside a specific time will be notified at the beginning of the specific time.

**Use Time Window**

You can notify only alerts within or outside the time zone specified in the Usage window.
