### ISSUE TITLE
not able to insert field in body text of the notification

### ISSUE THREAD

**Issue by geraliberti** [johnsusek/praeco#367]
hi there,

when trying to configure the alert body text, i specify the field:

![image](https://user-images.githubusercontent.com/58631145/118296441-4696eb80-b4dd-11eb-8a10-5a20bb04ca61.png)

but when then saving this is what appears (and what is then sent to my destination)

![image](https://user-images.githubusercontent.com/58631145/118296707-8f4ea480-b4dd-11eb-8c17-5bb740679e25.png)

is it possible to fix it easily?

thx
Gerardo

**Comment by nsano-rururu** [comment]
you are stupid?

**Comment by nsano-rururu** [comment]
![キャプチャ](https://user-images.githubusercontent.com/22293449/118342635-13953c00-b55f-11eb-926d-64de7fb3bff4.PNG)

**Comment by geraliberti** [comment]
Maybe, but not some shit idiot nerd like you

Il sab 15 mag 2021, 02:19 Naoyuki Sano ***@***.***> ha
scritto:
