### ISSUE TITLE
The hive full integration

### ISSUE THREAD

**Issue by ryukam** [johnsusek/praeco#368]
Hi all,

We are glad to see that Praeco support now thehive.

Unfortunatly, we are facing an issue because THEHIVE integration is not complete ! Some field are missing when configuring thehive connector, there is not field where insert the @IP:PORT of THEHIVE nor the API key.

Thank you for your help.

Best regards.
Charaf B
SSS

**Comment by nsano-rururu** [comment]
Is it hive_apikey? .
We do so on request. Since it is written in BaseRule.config, it is unnecessary on the screen.

https://github.com/johnsusek/praeco/issues/208#issuecomment-787824805
>I thing As like in telegram and email we need to have provision to add the following part(Which is common to all elast alert rules) of the hive configuration in elastalert/rules/BaseRule.config
>
>hive_connection:
>hive_host: http://localhost
>hive_port: <hive_port>
>hive_apikey: <hive_apikey>
>hive_proxies:
>http: ''
>https: ''

**Comment by nsano-rururu** [comment]
@ryukam

Did you solve?

**Comment by nsano-rururu** [comment]
@ryukam

ping

**Comment by nsano-rururu** [comment]
Thank you for your reply.
