### ISSUE TITLE
Error docker-compose up after upgrade praeco to 1.8.6

### ISSUE THREAD

**Issue by Teodor95** [johnsusek/praeco#370]
Hello, 
i have some problems to launch elastalert-server after i followed the guuide to upgrade praeco. Now i have this error:

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/elastalert/elastalert/test_rule.py", line 460, in <module>
    main()
  File "/opt/elastalert/elastalert/test_rule.py", line 456, in main
    test_instance.run_rule_test()
  File "/opt/elastalert/elastalert/test_rule.py", line 413, in run_rule_test
    rule_yaml = conf['rules_loader'].load_yaml(args.file)
  File "/opt/elastalert/elastalert/loaders.py", line 210, in load_yaml
    if 'filter' in rule and 'filter' in loaded:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by Teodor95** [comment]
TypeError: argument of type 'NoneType' is not iterable

**Comment by nsano-rururu** [comment]
I can't help because I don't know how to reproduce it.

**Comment by nsano-rururu** [comment]
![0](https://user-images.githubusercontent.com/22293449/119155395-1bd50600-ba8e-11eb-893f-efff8153209d.PNG)
![1](https://user-images.githubusercontent.com/22293449/119155407-1e376000-ba8e-11eb-8c09-1512a6917b74.PNG)
![キャプチャ](https://user-images.githubusercontent.com/22293449/119155414-21325080-ba8e-11eb-91a9-95a52af47894.PNG)

**Comment by nsano-rururu** [comment]
It's not a praeco issue. Since it is python, an error occurs in elastalert2.

**Comment by nsano-rururu** [comment]
Which alert did you set? I don't know what the generated rules look like. Because it's not Esper

**Comment by Teodor95** [comment]
Hello, 
Thanks for the reply. We had to restore the old version for critical reasons.
I will try to better understand what happened with elastalert2 on the lab vm.

**Comment by nsano-rururu** [comment]
We do not support older versions.

**Comment by nsano-rururu** [comment]
If you don't give me the information, I don't even know if it's a bug.

**Comment by nsano-rururu** [comment]
What steps did you take? .. Did you update the docker image of elastalert-server? .. Did the rule save again? I could have answered if I knew the information such as the state of the generated rule file, but I did not know if I wanted to solve the problem when I closed it without permission.
https://github.com/johnsusek/praeco/wiki/praeco-&-elastalert-server-docker-image-relations-table
https://github.com/johnsusek/elastalert-server/blob/master/DockerImageLog.md
