### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by abhi-laksh** [johnsusek/praeco#378]
When I am trying to run the container, I am facing the following issue. When I run, 'docker pull praecoapp/elastalert-server'. Please see through it.

elastalert-server: ProcessController:  Creating index
elastalert_1  | 04:21:12.489Z ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
elastalert_1  |         return _run_code(code, main_globals, None,
elastalert_1  |       File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 272, in <module>
elastalert_1  |         main()
elastalert_1  |       File "/opt/elastalert/elastalert/create_index.py", line 248, in main
elastalert_1  |         http_auth = auth(host=host,
elastalert_1  |       File "/opt/elastalert/elastalert/auth.py", line 51, in _call_
elastalert_1  |         return username + ':' + password
elastalert_1  |     TypeError: can only concatenate str (not "int") to str

**Comment by nsano-rururu** [comment]
@abhi-laksh 

Please give me the information of the configuration file.

api.config.json
elastalert.yaml

**Comment by abhi-laksh** [comment]
The issue is solved by setting the configuration file correctly. Thanks for your response. I shall close the issue now.
