### ISSUE TITLE
Praeco Upgrade from 1.1.0 to latest version containers 

### ISSUE THREAD

**Issue by hardikvdesai88** [johnsusek/praeco#380]
## 🐛 Summary

I am trying to upgrade praeco version from 1.1.0 to latest version by using below link.
https://github.com/johnsusek/praeco/releases

Praeco is installed on the Ubuntu server as containers of praeco + elastalert.

CONTAINER ID        IMAGE                         COMMAND                                          PORTS                                            NAMES
3590abddddb2        johnsusek/elastalert-server   "npm start"                              0.0.0.0:3030->3030/tcp, 0.0.0.0:3333->3333/tcp   praeco_elastalert_1
31f3330894cd        johnsusek/praeco              "docker-entrypoint.s…"                    0.0.0.0:8080->8080/tcp                           praeco_webapp_1

While following the below steps to upgrade praeco, logs are generated as follow:

**Steps:-** 
git checkout origin/master docker-compose.yml
docker pull praecoapp/praeco
docker pull praecoapp/elastalert-server
docker-compose up --force-recreate --build

**Logs for upgrade:-**
ubuntu@prod-kibana:~/praeco$ docker-compose up --force-recreate --build
Pulling webapp (johnsusek/praeco:latest)...
latest: Pulling from johnsusek/praeco
81fc19181915: Pull complete
ee49ee6a23d1: Pull complete
828510924538: Pull complete
a8f58c4fcca0: Pull complete
33699d7df21e: Pull complete
923705ffa8f8: Pull complete
86e685ca393b: Extracting [==============>                                    ]  86e685ca393b: Pull complete
a21f66286520: Pull complete
d771fbf3a138: Pull complete
a094d0c61754: Pull complete
b52466bede1b: Pull complete
353ebf6d3efd: Pull complete
5f3be26c7df9: Pull complete
bc46a975c730: Pull complete
581bea0cf67f: Pull complete
714b83251f34: Pull complete
515bc70843a9: Pull complete
e2a0e5f2feb9: Pull complete
Digest: sha256:b16c508d0c32210548656e078a6dea0d76bec79ffe7daa72c001d3cce85193e7
Status: Downloaded newer image for johnsusek/praeco:latest
Pulling elastalert (johnsusek/elastalert-server:latest)...
latest: Pulling from johnsusek/elastalert-server
cbdbe7a5bc2a: Pull complete
fb0e3739aee1: Pull complete
738de7869598: Pull complete
91b3f1ee5578: Pull complete
681c614eb546: Pull complete
509d0b17decf: Pull complete
027ecb24c074: Pull complete
2157f44e62e1: Pull complete
43fd7b40a946: Pull complete
a1844fca3465: Pull complete
1328328509df: Pull complete
543fcbfe67ef: Pull complete
64e81437487f: Pull complete
af5f1434e7f9: Pull complete
7ee06124275e: Pull complete
da57943abc56: Pull complete
73dfdd0cb47a: Pull complete
Digest: sha256:a056d9b58f7031c60626bd15f1a6d3f92506ba5cbb75c19f4b0bee123900ce90
Status: Downloaded newer image for johnsusek/elastalert-server:latest
Recreating praeco_webapp_1 ... 
Recreating praeco_webapp_1
Recreating praeco_elastalert_1 ... 
Recreating praeco_webapp_1 ... done
Attaching to praeco_elastalert_1, praeco_webapp_1
elastalert_1  | 
elastalert_1  | > @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
elastalert_1  | > sh ./scripts/start.sh
elastalert_1  | 
elastalert_1  | Browserslist: caniuse-lite is outdated. Please run:
elastalert_1  | npx browserslist@latest --update-db
elastalert_1  | 11:42:29.993Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
elastalert_1  | 11:42:29.993Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
elastalert_1  | 11:42:29.994Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
elastalert_1  | 11:42:30.028Z  INFO elastalert-server: Router:  Listening for GET request on /.
elastalert_1  | 11:42:30.028Z  INFO elastalert-server: Router:  Listening for GET request on /status.
elastalert_1  | 11:42:30.029Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
elastalert_1  | 11:42:30.029Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
elastalert_1  | 11:42:30.030Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
elastalert_1  | 11:42:30.031Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
elastalert_1  | 11:42:30.031Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
elastalert_1  | 11:42:30.032Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
elastalert_1  | 11:42:30.032Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
elastalert_1  | 11:42:30.032Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
elastalert_1  | 11:42:30.032Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
elastalert_1  | 11:42:30.033Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
elastalert_1  | 11:42:30.043Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for POST request on /test.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for POST request on /config.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for POST request on /download.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
elastalert_1  | 11:42:30.044Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
elastalert_1  | 11:42:30.045Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1  | 11:42:30.052Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
elastalert_1  | 11:42:30.052Z  INFO elastalert-server: ProcessController:  Creating index
elastalert_1  | 11:42:30.401Z  INFO elastalert-server:
elastalert_1  |     ProcessController:  Elastic Version: 7.6.1
elastalert_1  |     Reading Elastic 6 index mappings:
elastalert_1  |     Reading index mapping 'es_mappings/6/silence.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_status.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/past_elastalert.json'
elastalert_1  |     Reading index mapping 'es_mappings/6/elastalert_error.json'
elastalert_1  |     Index praeco_elastalert_status already exists. Skipping index creation.
elastalert_1  |     
elastalert_1  | 11:42:30.401Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
elastalert_1  | 11:42:30.402Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
elastalert_1  | 11:42:30.410Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
elastalert_1  | 11:42:30.413Z  INFO elastalert-server: Server:  Server listening on port 3030
elastalert_1  | 11:42:30.415Z  INFO elastalert-server: Server:  Websocket listening on port 3333
elastalert_1  | 11:42:30.416Z  INFO elastalert-server: Server:  Server started
elastalert_1  | 11:43:13.608Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 11:43:13.613Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules/:id'.
elastalert_1  | 11:43:13.940Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:13.941Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:13.947Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1  | 11:43:14.160Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert_1  | 11:43:27.479Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 11:43:27.481Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules/:id'.
elastalert_1  | 11:43:27.484Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:27.484Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:27.488Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert_1  | 11:43:27.489Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1  | 11:43:36.059Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 11:43:36.098Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:36.099Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:43:36.109Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert_1  | 11:43:36.126Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1  | 11:44:31.738Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules/:id'.
elastalert_1  | 11:44:35.998Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 11:44:36.001Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules/:id'.
elastalert_1  | 11:44:36.003Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:44:36.004Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 11:44:36.007Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.
elastalert_1  | 11:44:36.219Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert_1  | 12:10:21.808Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
elastalert_1  | 12:10:21.810Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules/:id'.
elastalert_1  | 12:10:22.178Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 12:10:22.180Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
elastalert_1  | 12:10:22.186Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert_1  | 12:10:22.188Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/rules'.

Plz help me with upgrading praeco. TIA...

**Comment by hardikvdesai88** [comment]
@johnsusek please help on this above question.

**Comment by nsano-rururu** [comment]
@hardikvdesai88

I think elastalert-server has started normally. I don't know what I'm having trouble with. please tell me.

**Comment by nsano-rururu** [comment]
We will release 1.8.7 soon.

**Comment by nsano-rururu** [comment]
@hardikvdesai88

I don't know what you are in. For example, the predecessor disappeared and he suddenly took over. Are you still a newcomer? Does that mean you can't read the log?

**Comment by hardikvdesai88** [comment]
@nsano-rururu I am new with praeco. I started upgrade process of praeco and also pasted the logs here. After these logs also, my praeco was running on old version and it is not upgraded. I have tried to stop and start container but still it is not getting newer versions. I have followed the same steps mentioned in the release docs. 
Can you suggest some way to upgrade praeco successfully?

**Comment by nsano-rururu** [comment]
@hardikvdesai88 

I'm new to praeco but I don't understand why it's an upgrade. Is it a lie for the first time?

**Comment by nsano-rururu** [comment]
I don't want to be involved with liars

**Comment by nsano-rururu** [comment]
It's a lie because I'm dropping the docker image. Liars are impossible. sorry.

**Comment by nsano-rururu** [comment]
Did you check out in 1.1.0 and deliberately do it with the old docker-compose.yml? Harassment? That's right. Since the docker image name has changed since then

**Comment by johnsusek** [comment]
@nsano-rururu SANOsan - https://ja.wikipedia.org/wiki/ハンロンの剃刀

@hardikvdesai88 Sorry this didn't work. Since praeco has changed so much since then, it's best to backup your rules from your 1.1.0 installation, install the latest from scratch, then copy your rules to the new installation.

**Comment by nsano-rururu** [comment]
@johnsusek

In that case, johnsusek's answer as a guide to upgrade to a specific version rather than the latest version from 1.1.0 to 1.8.4 is also incorrect. If you don't edit docker-compose.yml, you'll end up with the newest docker image, 1.8.7. Consider preparing docker-compose.yml to upgrade to a specific version as follows.

example)
docker-compose-praeco1_7_0.yml
docker-compose-praeco1_8_0.yml
docker-compose-praeco1_8_4.yml
docker-compose-praeco1_8_7.yml

**Comment by nsano-rururu** [comment]
@johnsusek

We will also review how to write release notes from 1.1.0 onwards.

**Comment by hardikvdesai88** [comment]
thanks all for the help. I will try and install the latest release and then update the rules thereafter if possible.
hopefully that will work.

**Comment by nsano-rururu** [comment]
If you are considering a tool for alert notification based on Elasticsearch data, we recommend that you try various things, including paid and free ones.

**Watcher**

https://www.elastic.co/guide/en/kibana/current/watcher-ui.html

**Alerting and action settings in Kibana**

https://www.elastic.co/guide/en/kibana/current/alert-action-settings-kb.html#action-settings

**Open Distro for Elasticsearch**

https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/

**Grafana**

https://grafana.com/docs/grafana/latest/alerting/

**sentinl**

https://github.com/sentinl/sentinl
