### ISSUE TITLE
Test Button not working properly

### ISSUE THREAD

**Issue by simonezambonim** [johnsusek/praeco#381]
## 🐛 Summary

Recently the test button stopped working properly. 
By properly, I mean, it starts showing "Starting test run", and once it is supposed to start quering, it just stops and shows nothing. 

It happens for all rules that are currently working (sending alerts) for any time range I may set.

- Docker image and tag names for praeco and elastalert
Example
praecoapp/praeco:1.8.7
praecoapp/elastalert-server:20210609

## 👀 Steps

1. Write a simple rule, like this one:
```
 __praeco_full_path: "api/any-error"
__praeco_query_builder: "{\"query\":{\"logicalOperator\":\"all\",\"children\":[{\"type\":\"query-builder-rule\",\"query\":{\"rule\":\"eventType\",\"selectedOperator\":\"contains\",\"selectedOperand\":\"eventType\",\"value\":\"*error*\"}}]}}"
alert:
  - "googlechat"
alert_subject: "prod API error"
alert_text: "User Id: {}\nError: {}\nURL: {}\nEvent Type: {}\n"
alert_text_args:
  - "userId"
  - " errorStatus"
  - "error.config.url"
  - "eventType"
alert_text_type: "exclude_fields"
filter:
  - query:
      query_string:
        query: "eventType:*error*"
generate_kibana_discover_url: false
googlechat_footer_kibanalink: "https://kibana.com.br/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(eventType,userId),index:'56e7fa50-11eb-818e-8d10c9225471',interval:auto,query:(language:kuery,query:''),sort:!(timestamp_insert,desc))"
googlechat_format: "card"
googlechat_header_title: "Error  API"
googlechat_webhook_url: "https://chat.googleapis.com/v1/spaces/AAAAZ-A_re0/messages?key="
import: "../BaseRule.config"
index: "log-json-api-prod-*"
is_enabled: true
kibana_discover_app_url: "https://kibana.com.br/app/kibana#/discover?"
kibana_discover_columns:
  - "eventType"
  - "userId"
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_index_pattern_id: "56e7fa50-c56e-11eb-818e-8d10c9225471"
kibana_discover_to_timedelta:
  minutes: 10
kibana_discover_version: "7.2"
match_enhancements: []
name: "any-error"
realert:
  minutes: 15
slack_attach_kibana_discover_url: false
timestamp_field: "timestamp_insert"
timestamp_type: "iso"
type: "any"
use_strftime_index: false
 
```

2. Try testing

It won't work!

## 🆗 Expected

![image](https://user-images.githubusercontent.com/63263866/123318252-64586700-d505-11eb-997c-d7110a86e56d.png)

**Comment by nsano-rururu** [comment]
I didn't use googlechat, so I tried the test on slack and it worked fine.

**Comment by nsano-rururu** [comment]
The alert does not fly when debug is set to true in api.config.json of ElastAlert Server. Is debug false?

**Comment by nsano-rururu** [comment]
Is the content of BaseRule.config empty? In that case, it is reported that there is a problem in the actual operation. Please describe something as follows. It seems to be a problem from the beginning of implementation.

```
slack_webhook_url: ""
```

**Comment by nsano-rururu** [comment]
After that, is there something like an error in the docker log of elastalert-server when running the test?

**Comment by nsano-rururu** [comment]
Isn't the rule you contacted not a test but a rule execution?

**Comment by nsano-rururu** [comment]
Is it an error if I change googlechat_format from card to basic?

**Comment by nsano-rururu** [comment]
If googlechat doesn't work, disable googlechat settings in the next version of praeco.

**Comment by simonezambonim** [comment]
> The alert does not fly when debug is set to true in api.config.json of ElastAlert Server. Is debug false?

Yes, the debug in  `api.config.json` is set to False

> Is the content of BaseRule.config empty?

No, it's not empty

> After that, is there something like an error in the docker log of elastalert-server when running the test?

No, no errors are shown in elastalert-server logs

> Isn't the rule you contacted not a test but a rule execution?

Indeed, it is. However my problem is not in the rule, I used it as example, since I'm sure it works. But I've tried creating a new rule and testing, and yet it doesn't work.

> Is it an error if I change googlechat_format from card to basic?

No, you can change it.. card makes the rule prettier to display.

> If googlechat doesn't work, disable googlechat settings in the next version of praeco.

GoogleChat works! Ther's no problem in recievint alerts in this tool. The problem to be solved is strict to the test button, sending real alerts or not.

**Comment by nsano-rururu** [comment]
If there is nothing in the log of elastalert-server, it probably means that there is no log even if you run elastalert2 alone.
I tried to implement google chat of elastalert2, but I didn't do anything special, I just posted it in request, so it feels like slack or msteams. 
https://github.com/jertel/elastalert2/blob/master/elastalert/alerters/googlechat.py

If the alerts are flying and the test doesn't work, it could be a test rule implementation issue.
https://github.com/jertel/elastalert2/blob/master/elastalert/test_rule.py

Is it possible to have elastalert2 try to run the test rule alone and it doesn't work?
https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#testing-your-rule

If it doesn't work, it's a problem on the elastalert2 side, so you may have to deal with it on the elastalert2 side.
https://github.com/jertel/elastalert2/discussions

**Comment by simonezambonim** [comment]
@nsano-rururu Thank you very much!

It seems the problem was related to  the security authentication step we had added  and a change in the port. So for the rule execution it worked fine, but not for the test.

I'm sorry for the confusion. I appreciated your help!
