### ISSUE TITLE
Add parameter "scan_entire_timeframe"

### ISSUE THREAD

**Issue by cachmc** [johnsusek/praeco#385]
Hey!
Thanks for this project.

Elastalert has a "scan_entire_timeframe" parameter. I want to use it but cannot find it in praeco.
In the future, I plan to create many rules with this parameter and expect problems with their support.

Could you add "scan_entire_timeframe" to praeco?

https://elastalert2.readthedocs.io/en/latest/ruletypes.html#scan-entire-timeframe

**Comment by nsano-rururu** [comment]
@cachmc

Should I set the true value of scan_entire_timeframe? .. Or should it be set only for specific Rule types? .. I don't know at all. teach me please.

**Comment by nsano-rururu** [comment]
@cachmc 

scan_entire_timeframe seems to have a bug. Praeco does not support this as it is an issue on the Erastarat side. Please request to [elastalert2](https://github.com/jertel/elastalert2).

use rule timeframe when scan_entire_timeframe is set
https://github.com/Yelp/elastalert/pull/3141

**Comment by nsano-rururu** [comment]
Do not start until you receive the answers to your screen UI questions.

**Comment by nsano-rururu** [comment]
I didn't feel enthusiasm, so I closed it.

**Comment by nsano-rururu** [comment]
Included at 1.8.9 release.
