### ISSUE TITLE
Allow (or document?) how to set the PGID / PUID of the user running the praeco webapp

### ISSUE THREAD

**Issue by beirtipol** [johnsusek/praeco#387]
## 🎉 Goal

Allow setting the PGID / PUID of the user in the praeco container

## 💪 Motivation

Allow the config paths to be mounted in the container but have control over the file permissions

**Comment by nsano-rururu** [comment]
There are no plans to support it. We are waiting for your pull request.

**Comment by beirtipol** [comment]
Do you have any suggestions for how to manage the creation of rules from the web ui? 

If I figure out how we can manage it I'll raise a PR

**Comment by beirtipol** [comment]
Thank you for your insightful reply. I'm not trying to manage access permissions from Praeco. I'm looking for a way to configure the running container such that files created by the container have specific user:group permissions so that I do not need root access to view the rule yaml files from outside the container.

**Comment by nsano-rururu** [comment]
Modifying the Dockerfile for elastalert-server rather than praeco?

**Comment by nsano-rururu** [comment]
https://docs.linuxserver.io/general/understanding-puid-and-pgid
https://qiita.com/kubotak/items/b029be4412fdb2e80053

**Comment by nsano-rururu** [comment]
@beirtipol 

What happened after that?
