### ISSUE TITLE
Praeco for Amazon OpenSearch Service

### ISSUE THREAD

**Issue by GeetikaGopi** [johnsusek/praeco#390]
How can I setup praeco for AWS Elasticsearch?  I set the ES host, port to 443, set SSL to true and added the credentials in elasalert config file.

But I get the following error:

ERROR: for elastalert  Cannot create container for service elastalert: invalid IP address in add-host: "xyz.es.amazonaws.com"

**Comment by nsano-rururu** [comment]
We are planning to raise the version of Elasticsearch so that it will refuse to connect to the Elasticsearch compatible service "Amazon Elasticsearch Service" provided by AWS, but currently it is not the latest version of the client library, so it should be possible to connect. ..

**Comment by nsano-rururu** [comment]
IP address What do you mean?

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco#how-do-i-connect-to-elasticsearch-using-ssl

**Comment by nsano-rururu** [comment]
Why not write the host name directly in es_host?

**Comment by nsano-rururu** [comment]
Do you need hostname mapping?

**Comment by nsano-rururu** [comment]
Deleted the following description in docker-compose.yml?

```yaml
    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'
```

**Comment by nsano-rururu** [comment]
By the way, I have never used AWS Elasticsearch, so I have never confirmed the operation.

**Comment by nsano-rururu** [comment]
The current implementation of elastalert-server may not work.

**Comment by nsano-rururu** [comment]
The following libraries and settings need to be added to the elastalert-server side, so this is not supported.
https://www.npmjs.com/package/aws-elasticsearch-connector

**Comment by nsano-rururu** [comment]
The answer is that elastalert2 supports it, but elastalert-server does not. Please use elastalert2 alone.
https://github.com/jertel/elastalert2

**Comment by nsano-rururu** [comment]
@elastic/elasticsearch@7.13 (and aws-elasticsearch-connector@9.0.3)

**Comment by nsano-rururu** [comment]
elastalert2 connects by specifying the region and profile when connecting to Amazon Elasticsearch service. After that, environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION, AWS_DEFAULT_PROFILE) are supported, so the same support is required.

**Comment by nsano-rururu** [comment]
https://github.com/opensearch-project/opensearch-js

**Comment by nsano-rururu** [comment]
I decided not to support it. Do not use praeco.
