### ISSUE TITLE
Writeback index on different elasticsearch instance then query target instance

### ISSUE THREAD

**Issue by Mastadamus** [johnsusek/praeco#397]
Im trying to understand if this is possible and the documentation and other sources I've looked at are leaving me a bit muddled. Is it possible to specify a different elasticsearch instance to do the metadata writeback indices to then the one i want to query? example.  Praeco writes it metadata to a local elasticsearch instance, but its running all its rule queries against an elasticsearch in the cloud. Is this possible? If so, How? any help would be appreciated.

**Comment by nsano-rururu** [comment]
Question if elasticsearch works on elastalert-server, praeco and another server (EC2 on AWS)? .. I think it will work. It does not support HA of elasticsearch. Because elastalert2 is also supported. I think you can use haproxy, but I haven't tried it.

The following services are not supported. Because elastalert-server does not support it.

- Elastic Cloud Cloud
- Amazon OpenSearch Service (formerly Amazon Elasticsearch Service)

In addition, elastalert2 alone supports Amazon OpenSearch Service (formerly Amazon Elasticsearch Service).

**Comment by nsano-rururu** [comment]
I'm not sure what elasticsearch is in the cloud, but you can specify only one elasticsearch. You cannot specify more than one.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/2526#issuecomment-551070814
> simple solution is to install a lightweight load balancer (like nginx or haproxy) and redirect your requests to your elasticsearch nodes. Just be sure your index settings are correctly spreading replicas of your shards accross your nodes because if the LB query a elastic node but doesn't contain all the data you needs, you will not see everything if the datas are spreads between the nodes

https://github.com/Yelp/elastalert/issues/1402#issuecomment-339786817
>No, you don't need to install it multiple places, nor do you need to declare all the node names. All you need is direct connectivity to a SINGLE node.

https://github.com/Yelp/elastalert/issues/1364#issuecomment-332835117
>Please use haproxy in front of elasticsearch . This helps to accomplish ha mode for elastalert.

https://github.com/Yelp/elastalert/issues/614#issuecomment-230896756
>I recommend haproxy. It's super simple to set up a reverse proxy for Elasticsearch to do load balancing.

**Comment by nsano-rururu** [comment]
praeco / elastalert-server does not support all the functions of elastalert2, so if the function you want to support does not support, please use elastalert2 alone.
https://github.com/jertel/elastalert2

**Comment by nsano-rururu** [comment]
Mulit-elasticsearch instances

Not Support
