### ISSUE TITLE
Praeco install error

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#404]
Hello 

praeco/npm install

error command 

9743 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v16.11.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
9743 verbose stack     at ChildProcess.emit (node:events:390:28)
9743 verbose stack     at maybeClose (node:internal/child_process:1064:16)
9743 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
9744 verbose pkgid node-sass@5.0.0
9745 verbose cwd /opt/praeco
9746 verbose Linux 5.4.0-89-generic
9747 verbose argv "/root/.nvm/versions/node/v16.11.1/bin/node" "/root/.nvm/versions/node/v16.11.1/bin/npm" "install"
9748 verbose node v16.11.1
9749 verbose npm  v8.0.0
9750 error code 1
9751 error path /opt/praeco/node_modules/node-sass
9752 error command failed

**Comment by ozgursuder** [comment]
npm audit fix --force

npm ERR! code ETARGET
npm ERR! notarget No matching version found for zrender@6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:

**Comment by nsano-rururu** [comment]
Downgraded node version from 16 to 14
