### ISSUE TITLE
alert to debug

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#407]
Hello
i use preaco v 1.8.9 
they have not alert options debug mode 
it help can you

**Comment by nsano-rururu** [comment]
OSS has no obligation to meet the needs of its users.

**Comment by nsano-rururu** [comment]
You shouldn't use Praeco. elastalert2 should be used alone.

**Comment by nsano-rururu** [comment]
Please make a pull request. Review and import if there is no problem.
