### ISSUE TITLE
praeco install npm error

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#408]
Hello there

I am getting an error like this during the installation phase.

Do you have any solution suggestions for this?

thank you for your support

/praeco# npm audit fix --force
npm ERR! code ETARGET
npm ERR! notarget No matching version found for echarts@6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by nsano-rururu** [comment]
Please. Do not use praeco.

**Comment by nsano-rururu** [comment]
Why don't you read the README so hard?

**Comment by nsano-rururu** [comment]
Stalkers are not users.

**Comment by nsano-rururu** [comment]
I don't have time to bite because I'm not free.

**Comment by nsano-rururu** [comment]
Don't run npm audit fix --force. Are you stupid? It is not a command to execute casually because it may not pass the build. Really stupid.
