### ISSUE TITLE
Doing Complex queries using elastalert/praeco. Is it possible?

### ISSUE THREAD

**Issue by machillef** [johnsusek/praeco#414]
Hello all.

Lately I have been testing praeco as a tool for automating alerts using Elasticsearch as a central log server.
However, some of the alerts I would like to perform are more complex than simple string queries.
Let me give you an example. 
I have an index called test-index with Source/Destination IP pairs as the fields(among other irrelevant fields):
```
Doc1:
sourceIP: ipA
destIP: ipE

Doc2:
sourceIP: ipB
destIP: ipD

Doc3:
sourceIP: ipC
destIP: ipE
```

I would like to run a complex query, for example find all results where the destination IP is the same, and if the total count is more than 10 send an alert. In my example index, the query would return Doc1 and Doc3, but would not fire an alert.
As you can guess, since the IP(both source and destination) are dynamic I can't use something like "if destIP = "192.168.0.1" or something similar. It would have to be generic.

Is this something that I could do using Praeco/Elastalert or because dives into more complex queries I can not?

In any case, thank you very much for all the work you have done.

**Comment by nsano-rururu** [comment]
I maintain praeco, but I don't use praeco or elastalert2. I think you should ask about elastalert2 in the discussion of elastalert2.
https://github.com/jertel/elastalert2/discussions
