### ISSUE TITLE
Praeco can't create or duplicate rules (old ones were created on another instance)

### ISSUE THREAD

**Issue by NailBash** [johnsusek/praeco#419]
## 🐛 Describe the bug

- Docker image and tag names for praeco and elastalert
Example)
praecoapp/praeco:1.8.9
praecoapp/elastalert-server:20210704

- Screen capture of praeco operation
![изображение](https://user-images.githubusercontent.com/29750691/147040122-c405df64-d119-4de7-8574-531be3422f29.png)

- Please provide if there is an error in elastalert-server.
```
elastalert_1  | 05:24:11.531Z ERROR elastalert-server:
elastalert_1  |     Routes:  Request for '/rules/:id' failed with error:
elastalert_1  |
elastalert_1  |      [Error: EACCES: permission denied, open '/opt/elastalert/rules/DNS/dns_001_ptr (1).yaml'] {
elastalert_1  |       errno: -13,
elastalert_1  |       code: 'EACCES',
elastalert_1  |       syscall: 'open',
elastalert_1  |       path: '/opt/elastalert/rules/DNS/dns_001_ptr (1).yaml'
elastalert_1  |     }
```
I tried to:
```
chmod -R 777 rules
```
but it doesn't help.

**Comment by nsano-rururu** [comment]
The latest versions of praeco and elastalert-server did not reproduce the issue. Support for this matter will end.
