### ISSUE TITLE
There is no such version. Don't lie too much. Liars are not supported.

### ISSUE THREAD

**Issue by NailBash** [johnsusek/praeco#422]
```
There is no such version. Don't lie too much
Liars are not supported.
```

![image](https://user-images.githubusercontent.com/29750691/147355922-52fe3ec5-3dba-4bbb-aed1-983be485af8c.png)

 Hey, nsano-rururu, are you idiot?
 https://github.com/johnsusek/praeco/wiki/praeco-&-elastalert-server-docker-image-relations-table

**Comment by nsano-rururu** [comment]
You're an idiot
