### ISSUE TITLE
getting "t.filter is not a function"  and  API error Error: Request failed with status code 404

### ISSUE THREAD

**Issue by wazier2022** [johnsusek/praeco#437]
API error Error: Request failed with status code 404 relates to:
http://localhost:8080/api/config gives Cannot GET /config

## 🐛 Describe the bug

- Docker image and tag names for praeco and elastalert
praecoapp/praeco:1.8.6
karql/elastalert2-server:latest

- Screen capture of praeco operation
![image](https://user-images.githubusercontent.com/98813717/152526354-11e4a0d6-d1d7-44c3-bd9e-5a7aafe920c0.png)

- Rules generated by praeco
able to save the rules but unable to se them because of the filter error
![image](https://user-images.githubusercontent.com/98813717/152526915-c4b2f2ca-a7ec-4676-be50-b0ca546d9fb9.png)
![image](https://user-images.githubusercontent.com/98813717/152527123-267adb96-9016-4478-b2a7-65c19ec7596d.png)
does show up in alestalert plugin for kibana
![image](https://user-images.githubusercontent.com/98813717/152527475-9e0b9817-82b2-42a2-8505-957eb41e8983.png)

- Please provide if there is an error in elastalert-server.

**Comment by nsano-rururu** [comment]
karql / elastalert2-server does not implement the function corresponding to praeco.
