### ISSUE TITLE
jertel/elastalert2 problems

### ISSUE THREAD

**Issue by wazier2022** [johnsusek/praeco#438]
This issue is still there when using ghcr.io/jertel/elastalert2/elastalert2:latest

https://github.com/johnsusek/praeco/issues/437

**Comment by wazier2022** [comment]
may have used wrong jertel/elastalert2

**Comment by wazier2022** [comment]
getting same error with jertel/elastalert2:latest

![image](https://user-images.githubusercontent.com/98813717/152588113-9f13b24a-44fb-4233-b8fe-0868d28f238c.png)

**Comment by wazier2022** [comment]
if i use praecoapp/elastalert-server:latest then i get no errors

**Comment by wazier2022** [comment]
how can I install on a stand alone server praecoapp/elastalert-server, where to find the bin packages etc....

**Comment by wazier2022** [comment]
is there any need to contact this url https://api.github.com/repos/ServerCentral/praeco/releases;

**Comment by wazier2022** [comment]
its in the default.conf.
Can we point it to a local json file?

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco#manualdev-installation

**Comment by nsano-rururu** [comment]
>its in the default.conf.
>Can we point it to a local json file?

？？

**Comment by nsano-rururu** [comment]
>is there any need to contact this url https://api.github.com/repos/ServerCentral/praeco/releases;

Old repository. No one answers when I post
