### ISSUE TITLE
The json.message is truncated by blank

### ISSUE THREAD

**Issue by liya2017** [johnsusek/praeco#460]
## 🐛 Summary

(Question summary)
The json.message is truncated by blank

- Screen capture of praeco operation
 the alert like below picture
<img width="537" alt="image" src="https://user-images.githubusercontent.com/32123500/168518464-391ec07f-14c8-4365-92fd-15f432a88bef.png">

and the full message like below:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/32123500/168518531-2701c357-2288-43fa-a5de-98dac8818c19.png">

- this is my rules setting
 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/32123500/168518661-8d2a243f-c1e3-4fc6-98bf-d95d86c3f504.png">

## 👀 Operating environment

- docker-composer 
- elasticsearch version:7.6.2
- latest

## 📎 Images (optional)

(Image when a bug occurs)

**Comment by nsano-rururu** [comment]
Since it is processed by elastalert2, nothing is done by praeco.
https://github.com/jertel/elastalert2/blob/master/elastalert/alerters/telegram.py#L33
