### ISSUE TITLE
Is it possible to use custom Elastalert RulesLoader with Praeco/Elastalert-server?

### ISSUE THREAD

**Issue by anderser** [johnsusek/praeco#464]
## 🐛 Summary

We are creating a custom `RulesLoader` (ref https://elastalert2.readthedocs.io/en/latest/recipes/adding_loaders.html) for storing rules in S3. But would adding such rules loader to Elastalert work with Praeco/Elastalert server?

As far as I can see from the code, Elastalert server uses/writes to yaml-files on disk only, is that correct?

**Comment by nsano-rururu** [comment]
I have never tried it. Doesn't it work? .. If you have time to write a question, why not give it a try?
