### ISSUE TITLE
Deprecation warnings on ElasticSearch 7.13.3

### ISSUE THREAD

**Issue by vaisov** [johnsusek/praeco#465]
## 🐛 Describe the bug

- Docker image and tag names for praeco and elastalert
Example)
praecoapp/elastalert-server
praecoapp/praeco

- Please provide if there is an error in elastalert-server.
```
praeco-elastalert-1  | 11:32:57.661Z ERROR elastalert-server:
praeco-elastalert-1  |     ProcessController:  /home/node/.local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Camel case format name dateOptionalTime is deprecated and will be removed in a future version. Use snake case name date_optional_time instead.
praeco-elastalert-1  |       warnings.warn(message, category=ElasticsearchDeprecationWarning)
praeco-elastalert-1  |     /home/node/.local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: [types removal] Using include_type_name in put mapping requests is deprecated. The parameter will be removed in the next major version.
praeco-elastalert-1  |       warnings.warn(message, category=ElasticsearchDeprecationWarning)
```

## 👀 Steps to reproduce

1. git clone git@github.com:johnsusek/praeco.git
2. mkdir -p rules rule_templates
3. chmod -R 777 rules rule_templates
4. echo "slack_webhook_url: ''"  | sudo tee -a rules/BaseRule.config >/dev/null
5. export PRAECO_ELASTICSEARCH=<your elasticsearch ip>
6. docker-compose up

## 🆗 Expected behavior

No error/warning in docker compose logs

**Comment by nsano-rururu** [comment]
Not a bug. specification

**Comment by nsano-rururu** [comment]
Warning issued by elasticsearch-py. It will be obsolete in the next version, but it is a warning, so there is no problem in operation. I pointed out to the maintainers in the review of the pull request for elasticsearch8 in elastalert2. There is nothing that elastalert-server can handle.

**Comment by nsano-rururu** [comment]
It's strange to say it's a bug without reading the error message or checking it in action.
