### ISSUE TITLE
praeco start error ubuntu

### ISSUE THREAD

**Issue by ozgursuder** [johnsusek/praeco#480]
npm run serve

> praeco@1.8.11 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'disableHostCheck'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'disableHostCheck'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (/opt/praeco/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115:11)
    at new Server (/opt/praeco/node_modules/webpack-dev-server/lib/Server.js:231:5)
    at serve (/opt/praeco/node_modules/@vue/cli-service/lib/commands/serve.js:194:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by nsano-rururu** [comment]
I don't understand why you lie like that.
