### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'search')

### ISSUE THREAD

**Issue by zrayburn** [johnsusek/praeco#482]
## 🐛 Summary

After following install instructions it appears as though the Axios Proxy on localhost:3030 is unable to serve requests due to a type error. I'm not sure if this is due to a misconfiguration on my side or a bug.

Reproduction:
`git clone https://github.com/johnsusek/praeco.git`
follow quickstart instructions
Add SSL config and elastic IP, username, password
`docker compose up -d`

Navigate to 127.0.0.1:8080/
Loads for a minute then gives error: "AxiosError: Request failed with status code 504"
![image](https://user-images.githubusercontent.com/13396977/187739275-59e4b621-c413-4af4-bfe6-30063f479e5b.png)

Resultant in the `docker compose logs`:
praeco-elastalert-1  | URIError: URI malformed
praeco-elastalert-1  |     at decodeURIComponent (<anonymous>)
praeco-elastalert-1  |     at Url.parse (node:url:351:19)
praeco-elastalert-1  |     at Object.urlParse [as parse] (node:url:155:13)
praeco-elastalert-1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:133:22)
praeco-elastalert-1  |     at new Promise (<anonymous>)
praeco-elastalert-1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:49:10)
praeco-elastalert-1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:58:10)
praeco-elastalert-1  |     at Axios.request (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:109:15)
praeco-elastalert-1  |     at Axios.<computed> [as get] (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:131:17)
praeco-elastalert-1  |     at Function.wrap [as get] (/opt/elastalert-server/node_modules/axios/lib/helpers/bind.js:9:15)
praeco-elastalert-1  | URIError: URI malformed
praeco-elastalert-1  |     at decodeURIComponent (<anonymous>)
praeco-elastalert-1  |     at Url.parse (node:url:351:19)
praeco-elastalert-1  |     at Object.urlParse [as parse] (node:url:155:13)
praeco-elastalert-1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:133:22)
praeco-elastalert-1  |     at new Promise (<anonymous>)
praeco-elastalert-1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:49:10)
praeco-elastalert-1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:58:10)
praeco-elastalert-1  |     at Axios.request (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:109:15)
praeco-elastalert-1  |     at Axios.<computed> [as get] (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:131:17)
praeco-elastalert-1  |     at Function.wrap [as get] (/opt/elastalert-server/node_modules/axios/lib/helpers/bind.js:9:15)
praeco-elastalert-1  | **TypeError: Cannot read properties of undefined (reading 'search')**
praeco-elastalert-1  |     at metadataElastalertHandler (/opt/elastalert-server/src/handlers/metadata/get.js:154:14)
praeco-elastalert-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
praeco-elastalert-1  | 17:03:14.327Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
praeco-elastalert-1  | 17:03:14.348Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.
praeco-elastalert-1  | 17:03:14.349Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/config'.

A minute later webapp log reports:
praeco-webapp-1      | 2022/08/31 17:04:14 [error] 8#8: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: , request: "GET /api/metadata/elastalert?noagg=1 HTTP/1.1", upstream: "http://172.25.0.3:3030/metadata/elastalert?noagg=1", host: "localhost:8080", referrer: "http://localhost:8080/"

A similar result appears when trying to create a rule. Except it is the indices which do not load:
URIError: URI malformed
praeco-elastalert-1  |     at decodeURIComponent (<anonymous>)
praeco-elastalert-1  |     at Url.parse (node:url:351:19)
praeco-elastalert-1  |     at Object.urlParse [as parse] (node:url:155:13)
praeco-elastalert-1  |     at dispatchHttpRequest (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:133:22)
praeco-elastalert-1  |     at new Promise (<anonymous>)
praeco-elastalert-1  |     at httpAdapter (/opt/elastalert-server/node_modules/axios/lib/adapters/http.js:49:10)
praeco-elastalert-1  |     at dispatchRequest (/opt/elastalert-server/node_modules/axios/lib/core/dispatchRequest.js:58:10)
praeco-elastalert-1  |     at Axios.request (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:109:15)
praeco-elastalert-1  |     at Axios.<computed> [as get] (/opt/elastalert-server/node_modules/axios/lib/core/Axios.js:131:17)
praeco-elastalert-1  |     at Function.wrap [as get] (/opt/elastalert-server/node_modules/axios/lib/helpers/bind.js:9:15)
praeco-elastalert-1  | **TypeError: Cannot read properties of undefined (reading 'cat')**
praeco-elastalert-1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:24:14)
praeco-elastalert-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

I'm not sure if this is a bug or a configuration error on my praeco instance or elasticsearch server.

## 👀 Operating environment

- Docker installation of praeco, seperate install of elasticsearch
- elasticsearch version 7.16.3
- praeco version 1.8.11
- praecoapp/elastalert-server   latest    f21964d96e52   4 weeks ago     1.4GB

**Comment by nsano-rururu** [comment]
An error message will appear if elasticsearch is not yet reachable. Specifications.

**Comment by nsano-rururu** [comment]
If elasticsearch is running, double check the configuration file information, elasticsearch permissions, etc.

**Comment by zrayburn** [comment]
Thanks for the response. Elasticsearch is definitely running and available, as elastalert server creates the indexes at startup successfully.

api.config.json:
```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": true,
  "es_debug": true,
  "debug": true,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "elastalert",
  "es_password": "",
  "es_ssl": true,
  "ea_verify_certs": false,
  "es_ca_certs": "/opt/elastalert/ssl/elastic-stack-ca.p12",
  "es_client_cert": "/opt/elastalert/ssl/cert.crt",
  "es_client_key": "/opt/elastalert/ssl/private.key",
  "writeback_index": "praeco_elastalert_status"
}
```

elastalert.yaml (all other values default):
```
# Connect with TLS to elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: elastalert
es_password:
es_ca_certs: /opt/elastalert/ssl/elastic-stack-ca.p12
es_client_cert: /opt/elastalert/ssl/cert.crt
es_client_key: /opt/elastalert/ssl/private.key

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True
```

My config files are very close to base install, I'm not sure what issue could have been created. I am less sure about the elasticsearch configuration. My elasticsearch permissions are as follows:

elastalert(elastalert_writer);
elastalert_writer = cluster privileges: monitor
index permissions:
praeco* = all
logs* = read

**Comment by nsano-rururu** [comment]
I understand that the basic installation method has its drawbacks. elasticsearch must be started and connectable. Praeco or elastalert2 running in the background immediately tries to connect to elasticsearch.
Although it does not support ssl, I set it to start at the same time with the following settings, but when it becomes possible to connect, elastalert-server runs and elastalert2 creates an index in the background, and connects if there is an index. I am checking as far as I can.
https://github.com/nsano-rururu/elastalert-server_praeco_docker-compose_sample

**Comment by nsano-rururu** [comment]
By the way, I was not originally a maintainer of praeco. I took over the development from around August 2020, but I usually don't use praeco at all. By the way, I am one of the maintainers of elastalert2.

**Comment by zrayburn** [comment]
Well I appreciate any information you can provide me about why the error happened! Thanks for supporting the project.

**Comment by nsano-rururu** [comment]
I have a question. Is it a proxy environment?

**Comment by nsano-rururu** [comment]
I'm not sure why the error occurred. Unable to reproduce in my environment. It's hard to say without environmental information. because he is not god
