### ISSUE TITLE
praeco start error

### ISSUE THREAD

**Issue by Meddeb-bilel** [johnsusek/praeco#483]
root@ElastAlert:/etc/praeco# npm run serve

> praeco@1.8.11 serve
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'disableHostCheck'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'disableHostCheck'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
    at validate (/etc/praeco/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115:11)
    at new Server (/etc/praeco/node_modules/webpack-dev-server/lib/Server.js:231:5)
    at serve (/etc/praeco/node_modules/@vue/cli-service/lib/commands/serve.js:194:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by nsano-rururu** [comment]
Did you set the node version to 16.15.0 with this procedure?
https://github.com/johnsusek/praeco#setting-up-praeco

**Comment by nsano-rururu** [comment]
By any chance do you have webpack 5.x installed?
Webpack 5 is not supported yet.

**Comment by nsano-rururu** [comment]
If you modify vue.config.js as follows, the error will be resolved, but there seems to be another problem, so it is unlikely that you will be able to support webpack5 immediately.

disableHostCheck: true,
　↓
allowedHosts: ['all'],
