### ISSUE TITLE
Secure ElastAlert-API

### ISSUE THREAD

**Issue by Meddeb-bilel** [johnsusek/praeco#484]
Hello,

I Have installed elastalert + API-server using the manual installation

[https://github.com/johnsusek/praeco#manualdev-installation](url)

And It works good (as you can see in the image), using postman I can GET all rules, and I can create a rule.

![Rest-API](https://user-images.githubusercontent.com/96694103/188447127-d22d5d79-985b-48a5-81ba-adce05d8369a.png)

Problem:

I want to secure the communication between the client and ElastAlert-server

What can I do to Configuring SSL, TLS, and HTTPS ?

**Comment by nsano-rururu** [comment]
You can do it by setting elasticsearch to ssl, elastalert2 and elasitcsearch ssl connection, and elastalert-server ssl settings.
Below is an example I tried with docker.
https://github.com/johnsusek/praeco/issues/345#issuecomment-822827568

**Comment by nsano-rururu** [comment]
Should I set ssl with nginx on the web server?
https://github.com/johnsusek/praeco/tree/master/nginx_config

**Comment by Meddeb-bilel** [comment]
Hello Sir,
I think, you are talking about the connection between a client and praeco (3- In the images) 
I talk about the connection to Elastalert-API ( postman --> ElastAlert API | praeco --> ElastAlert API) (2- In Image)
![arch2](https://user-images.githubusercontent.com/96694103/188481992-698ac32f-2dbc-4015-8dcd-b89429e17ab8.png)

in other words:
I Need to use https in **proxy_pass**  ==> **proxy_pass https://elastalert:3030/**
![praeco-](https://user-images.githubusercontent.com/96694103/188482379-cedbc7dd-435a-4488-b8ec-cb91f1ce9ce2.png)

**Comment by nsano-rururu** [comment]
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/

**Comment by Meddeb-bilel** [comment]
SIR
This to secure communication between client and praeco not between praeco and elastalert-api 
I want to secure the connection via port 3030

**Comment by nsano-rururu** [comment]
I have no further information.
