### ISSUE TITLE
The value key "http_post_static_payload" is not sending the value defined in the rule as a variable.

### ISSUE THREAD

**Issue by Sinistr0** [johnsusek/praeco#487]
I'm trying to send the description of the rule along with the alert, but when trying to put the configuration that is able to accomplish this, I found the following problem:
I added in Baserule.config the line
```
http_post_static_payload:
 description: %(description)
```

however it returns an error in the execution of the alert. I would like to know if it is possible to put the value of the description of the rule in this way written in Baserule.config or is it not possible at the moment.
I also tried with:
`description : {{description}}`
and returns mapping error in python.
and if I put it in quotes it sends it as a string

**Comment by nsano-rururu** [comment]
Does elastalert2 support that way of writing?

**Comment by nsano-rururu** [comment]
If you want to use all elastalert2 features, you should not use praeco and elastalert-server.

**Comment by nsano-rururu** [comment]
Due to health issues, bug fixes and feature additions are unlikely for the time being
