### ISSUE TITLE
Praeco unable to read certificate folder

### ISSUE THREAD

**Issue by JumpyWizard404** [johnsusek/praeco#490]
Good afternoon i was able to sucessfully configure Praeco to connecto to elasticsearch with ssl, however when trying to create a rule / load indices the error that it cannot find the certificate in the location keeps showing up
praeco-elastalert-1  | Error: ENOENT: no such file or directory, open '/etc/elasticsearch/certs/http_ca.crt'
praeco-elastalert-1  |     at Object.openSync (node:fs:585:3)
praeco-elastalert-1  |     at Object.readFileSync (node:fs:453:35)
praeco-elastalert-1  |     at getClientVersion (/opt/elastalert-server/src/common/elasticsearch_client.js:68:23)
praeco-elastalert-1  |     at indicesHandler (/opt/elastalert-server/src/handlers/indices/get.js:9:30)
praeco-elastalert-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
praeco-elastalert-1  |   errno: -2,
praeco-elastalert-1  |   syscall: 'open',
praeco-elastalert-1  |   code: 'ENOENT',
praeco-elastalert-1  |   path: '/etc/elasticsearch/certs/http_ca.crt'

Not sure if this might be somehow related to the fact that these are self signed certs which is why certificate verification has been turned off

**Comment by nsano-rururu** [comment]
config file or elasticsearch version. I don't know the environment such as docker, so I can't answer. I'm sleepy, so I'm going to sleep.

**Comment by JumpyWizard404** [comment]
managed to resolve the issue by removing the paths to certificate files.
