### ISSUE TITLE
Can't access indices on the "create a new rule" webpage

### ISSUE THREAD

**Issue by joseraeiro** [johnsusek/praeco#498]
Hello, I'm trying to install Praeco on separate machine from my OpenSearch (Wazuh indexer) installation. I've edited the config/api.config.json and config/elastalert.yaml files to have the password and username of "kibanaserver" from the Wazuh installation. 

I've exported the variable PRAECO_ELASTICSEARCH using: export PRAECO_ELASTICSEARCH="172.16.20.10" and I've ran docker-compose up.

I'm able to access to Web GUI at http://172.16.20.21:8080 but when clicking on the "create a new rule" webpage, it shows that the indices are loading but when finishing loading I'm unable to see any indices (nor am I able to access the wazuh-alerts-* index).

I'm also presented with the following error window (on the GUI)

![2022-10-25 12_52_21-praeco — Mozilla Firefox](https://user-images.githubusercontent.com/8979838/197768239-8dc31619-90b2-4339-854b-fb2c08ed80da.png)

Please take a look at the output of the docker-compose up command:

[docker-compose_up_praeco.log](https://github.com/johnsusek/praeco/files/9860084/docker-compose_up_praeco.log)

What am I doing wrong?

**Comment by nsano-rururu** [comment]
I don't have time to fix it now, so please don't use it.

**Comment by nsano-rururu** [comment]
https://github.com/Karql/elastalert2-server
https://github.com/Karql/elastalert-kibana-plugin
