### ISSUE TITLE
html email alert edition fails ?

### ISSUE THREAD

**Issue by ulysse31** [johnsusek/praeco#500]
When using praeco web interface, making a test alert with email alerting via the web interface goes well, until you try to fill out the "Body text" with html :
- if you type by hand the html code, the Body preview gets filled with html code, if you click "test" after that, the test works, but saving the rule fails to store the html code into the YAML config (maybe because of the multi-line html hand-writing I did ?)
- if you copy paste the html code from any source to the body text field => html seems to get interpreted inside the edition field "body text", which is "nice", but the "Body preview" is blank, testing the rule fails, saving it also generates an empty alert_text (alert_text: "") in config => I tried to copy/paste html in multi-line and/or all in one line ... same result.

Of course, the same rule works if the content is NOT html but simply text ...
Did I missed something to get html email alerting working ? is it a bug ?
I tried different web browsers (edge/chrome/firefox) the results were always the same.

BTW: I am setting email_format: html inside BaseRule.config ... not sure if its related ...

Thanks a lot

**Comment by nsano-rururu** [comment]
email_format: html is currently not supported by Praeco. There are no plans to support it. Pull requests are welcome.

**Comment by ulysse31** [comment]
Oh ... So ... html email alerting is not supported at all ?
No simple way to "counter" this lack ?
isn't it possible to have a "Body text" field as a simple text field (no preview, simply text, can even be only one line ^^') ?
Technically, if we do not interpret the content, and simply store into the "alert_text" field its content ... it should not create any issue ? Am I wrong ?

**Comment by nsano-rururu** [comment]
Use only elastalert-server without using praeco

**Comment by nsano-rururu** [comment]
Or use a combination of
https://github.com/Karql/elastalert2-server
https://github.com/Karql/elastalert-kibana-plugin
