### ISSUE TITLE
non docker install

### ISSUE THREAD

**Issue by rful011** [johnsusek/praeco#508]
## 🐛 Summary
I have no experience with docker -- are there any instructions for installing without using docker?

I am just setting up elastalert2 and this looks like just what we need to manage it.  

One other thing: It isn't clear to me if praeco includes elastalert2 or not.

## 👀 Operating environment

- Direct installation 
- elasticsearch version 7.17
- version of praeco. latest
- elastalert-server docker image tag name not allplicable

## 📎 Images (optional)

(Image when a bug occurs)

**Comment by nsano-rururu** [comment]
First of all, praeco does not support all the features of elastalert2.
If you want to use all the features you should not use praeco.
If you want to use all the functions, it is recommended to use elastalert2 alone.

As a Python package
https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#as-a-python-package

**Comment by nsano-rururu** [comment]
Manual/Dev installation
https://github.com/johnsusek/praeco#manualdev-installation

**Comment by nsano-rururu** [comment]
I remember that elastalert2 had a function that did not work properly if it was installed directly and if the version was lower than python 3.9. In that case, you have no choice but to use docker. If you've never used docker, give it a try. It's not good to eat or not.

**Comment by rful011** [comment]
Thanks for the extremely fast response :)

in that case I will get elastaler2 set up and see what functions we actually need -- the go back to looking at praeco later.

**Comment by nsano-rururu** [comment]
Praeco ElastAlert 2 Alerts support status
https://github.com/johnsusek/praeco/wiki/ElastAlert-2-Alerts-support-status

**Comment by nsano-rururu** [comment]
praeco does not support rule generation for "Spike Aggregation" rule type and "Percentage Match" rule type.

**Comment by nsano-rururu** [comment]
By the way, praeco does not support direct modification of rules.
yaml generation of rules by setting from web screen of praeco.

**Comment by nsano-rururu** [comment]
When editing with the web editor of ElastAlert2 rules from Kibana,
Please consider using the following elastalert2-server and elastalert-kibana-plugin instead of praeco.
https://github.com/Karql/elastalert2-server
https://github.com/Karql/elastalert-kibana-plugin
