### ISSUE TITLE
Internal Error/ TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by MostafaAsaad** [johnsusek/praeco#514]
I got this issue after enable jira on praeco the rule is running normally but the UI still expose TypeError: Cannot read properties of undefined (reading 'children').

![image](https://user-images.githubusercontent.com/36057753/218583959-fafc31d7-7e16-449d-ac80-9f9c9ca6a9c2.png)

**Comment by nsano-rururu** [comment]
I don't know the operation, so I can't investigate

**Comment by MostafaAsaad** [comment]
i just enable the feature and got this error.

**Comment by nsano-rururu** [comment]
Now remove the jira feature

**Comment by MostafaAsaad** [comment]
if i remove it i don't get any errors,  but i want to use jira any recommendations..

**Comment by nsano-rururu** [comment]
so i will delete it. function

**Comment by nsano-rururu** [comment]
There's no point in having a feature that doesn't work, right? so delete

**Comment by MostafaAsaad** [comment]
Its working but in praeco ui i got the above error message.

**Comment by nsano-rururu** [comment]
Delete the jira settings added in 1.8.12 from the screen. Make it the state of 1.8.11. Supported in 1.8.13

**Comment by nsano-rururu** [comment]
Please use the previous version once

**Comment by nsano-rururu** [comment]
It is a policy that there is no need to help people who do not answer what kind of settings they got an error.
