### ISSUE TITLE
Opensearch 2.6 support

### ISSUE THREAD

**Issue by CyberAbwehr** [johnsusek/praeco#516]
## 🐛 Summary

Is opensearch 2.6 supported ?

## 👀 Operating environment

- open search 2.6
- praeco latest 
- elastalert2 latest 

regards

**Comment by CyberAbwehr** [comment]
THX 🤩😉

Naoyuki Sano ***@***.***> schrieb am Fr. 17. März 2023 um
10:35:

**Comment by CyberAbwehr** [comment]
### DOCKER IMAGES ###

opensearchproject/opensearch-dashboards                        2.6.0
opensearchproject/opensearch                                   2.6.0
praecoapp/elastalert-server                                    latest
praecoapp/praeco                                               latest
opensearchproject/logstash-oss-with-opensearch-output-plugin   8.4.0

### INDEX CREATED ###

> @bitsensor/elastalert@0.0.14 start
> sh ./scripts/start.sh

15:05:17.458Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
15:05:17.473Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
15:05:17.503Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
15:05:17.510Z  INFO elastalert-server: Router:  Listening for GET request on /.
15:05:17.511Z  INFO elastalert-server: Router:  Listening for GET request on /status.
15:05:17.512Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
15:05:17.513Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
15:05:17.515Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id*.
15:05:17.516Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id*.
15:05:17.517Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id*.
15:05:17.518Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
15:05:17.518Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id*.
15:05:17.519Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id*.
15:05:17.520Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id*.
15:05:17.521Z  INFO elastalert-server: Router:  Listening for PUT request on /folders/:type/:path*.
15:05:17.522Z  INFO elastalert-server: Router:  Listening for DELETE request on /folders/:type/:path*.
15:05:17.522Z  INFO elastalert-server: Router:  Listening for POST request on /test.
15:05:17.523Z  INFO elastalert-server: Router:  Listening for POST request on /silence/:path*.
15:05:17.524Z  INFO elastalert-server: Router:  Listening for GET request on /config.
15:05:17.524Z  INFO elastalert-server: Router:  Listening for POST request on /config.
15:05:17.525Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert.
15:05:17.526Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_status.
15:05:17.526Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/silence.
15:05:17.526Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/elastalert_error.
15:05:17.527Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/past_elastalert.
15:05:17.527Z  INFO elastalert-server: Router:  Listening for GET request on /indices.
15:05:17.527Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
15:05:17.527Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
15:05:17.527Z  INFO elastalert-server: Router:  Listening for GET request on /config.
15:05:17.550Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
15:05:17.551Z  INFO elastalert-server: ProcessController:  Creating index
15:05:25.624Z  INFO elastalert-server:
    ProcessController:  Reading Elastic 8 index mappings:
    Reading index mapping 'es_mappings/8/silence.json'
    Reading index mapping 'es_mappings/8/elastalert_status.json'
    Reading index mapping 'es_mappings/8/elastalert.json'
    Reading index mapping 'es_mappings/8/past_elastalert.json'
    Reading index mapping 'es_mappings/8/elastalert_error.json'
    New index praeco_elastalert_status created
    Done!

### api.config.json ###

{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "dataPath": {
    "relative": true,
    "path": "/server_data"
  },
  "es_host": "192.168.1.42",
  "es_port": 9200,
  "es_username": "admin",
  "es_password": "admin",
  "opensearch2_flg": true,
  "es_ssl": true,
  "es_verify_certs": false,
  "writeback_index": "praeco_elastalert_status"
}

### elastalert.yaml ###

# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: 192.168.1.42

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert 2 will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert 2 will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
es_username: admin
es_password: admin

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True

### docker-compose.yml PRAECO ###

version: '3.7'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
    ports:
      - 8080:8080
#    environment:
#      VUE_APP_BASE_URL: /my-path/
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
 
### PRAECO ERRORS ###

1. Open praeco in the browser

Elasticsearch error

2. Add Rule

API error
Error fetching indices

Get mapping failed. Make sure the index exists
Could not fetch mappings.

**Comment by CyberAbwehr** [comment]
The praeco is very useful for users that are not so aware of yaml files.

**Comment by nsano-rururu** [comment]
@CyberAbwehr 

If you know how to create an environment for open search 2.6 with docker, you can investigate.

**Comment by CyberAbwehr** [comment]
I have a full open search 2.6 docker environment running. The question is how can I investigate/debug?

**Comment by nsano-rururu** [comment]
I don't want access to your environment. I'm trying to create an opensearch environment in my local environment and investigate.

**Comment by nsano-rururu** [comment]
It closes because the environment cannot be created.
