### ISSUE TITLE
1.8.13 not works well with praecoapp/elastalert-server:20230430

### ISSUE THREAD

**Issue by JaredTan95** [johnsusek/praeco#524]
## 🐛 Describe the bug
Creating rules not works

- Docker image and tag names for praeco and elastalert
Example)
praecoapp/praeco:1.8.13
praecoapp/elastalert-server:20230430

- Screen capture of praeco operation

- Rules generated by praeco

- Please provide if there is an error in elastalert-server.

## 👀 Steps to reproduce

(Bug reproduction procedure)

Please write as much as you can remember the detailed procedure. This is because I want to check if it can be reproduced in the same way.

1. Do action
2. Do another action
3. Wrong Behavior !!

## 🆗 Expected behavior

(State required to be Closed)

**Comment by nsano-rururu** [comment]
There was no problem. you're a liar
