### ISSUE TITLE
How to restore rules from backup

### ISSUE THREAD

**Issue by baileygm** [johnsusek/praeco#529]
## 🐛 Summary

We're testing Preaco as an alternative to our existing elastalert2 system and its looking excellent in many ways

In case of a host failure we may wish to restore rule files from a backup and have them re-read by the system and visible in the Praeco web UI

It seems that currently any manual modifications to the elastalert rules files are not visible in the UI so I suspect that simply restoring files to the rules folder in a new, empty Praeco system would not work

Is there a way to get Praeco to read manually created rule files or re-read manually edited files ? 

## 👀 Operating environment

- docker
- elasticsearch version 8.6.0
- version of praeco : praecoapp/praeco:1.8.13
- elastalert-server docker image tag name: praecoapp/elastalert-server:20230430

**Comment by baileygm** [comment]
> Support for manual modification of rule files

I didn't understand you answer - has this been added to future plans or is there an existing solution already ?

**Comment by nsano-rururu** [comment]
This is a typo. sorry.
Supported for now
