### ISSUE TITLE
Use Time Window - drop if

### ISSUE THREAD

**Issue by IlliciteS** [johnsusek/praeco#531]
Hello,

We've been using Praceo for a while but we have some troubles to understand the meaning of that feature.

What do you mean by drop if?
It could mean two opposite things, for me, as a non native English speaker: trigger or cancel, which is pretty problematic.
![image](https://github.com/johnsusek/praeco/assets/66977001/73505b06-9bee-41f4-9625-5a98556fd9e0)

For instance, in that case, the alarm will trigger only if we are inside the 1pm - 0h00, right?
Thanks for any explanations.

**Comment by nsano-rururu** [comment]
English is not my native language either.

**Comment by nsano-rururu** [comment]
A pull request if you'd prefer a better word

**Comment by IlliciteS** [comment]
Sorry, I'm a bit late bit what does it still mean?
Pull request = does it trigger the alarm inside a range or does it cancel it?

**Comment by IlliciteS** [comment]
I tried. I git clone, I did the changes, and try tio push my new branch so that I can do a pull request but I am not allowed to push the new branch.

**Comment by nsano-rururu** [comment]
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
