### ISSUE TITLE
praeco 1.8.16 web interface doesn't start

### ISSUE THREAD

**Issue by poffyna** [johnsusek/praeco#563]
## 🐛 Describe the bug

- Docker image and tag names for praeco and elastalert
praecoapp/praeco:1.8.16
praecoapp/elastalert-server:20230819

I tried to switch from (working) praeco 1.8.15 to 1.8.16 (latest).
With the new version, the web UI remains empty.
In the browser console, I found following error message:

later.js:1  Uncaught ReferenceError: later is not defined
    at 85006 (later.js:1:1)
    at l (bootstrap:19:32)
    at 30226 (index.js:8:1)
    at l (bootstrap:19:32)
    at 47468 (prettycron.js:26:15)
    at l (bootstrap:19:32)
    at 6283 (app.9583612a.js:1:694003)
    at l (bootstrap:19:32)
    at startup:4:87
    at l.O (chunk loaded:25:12)

## 👀 Steps to reproduce
I did the 'upgrade' steps:
docker-compose down 
docker rmi praecoapp/praeco:latest
docker rmi praecoapp/elastalert-server:latest
docker pull praecoapp/praeco:latest
docker pull praecoapp/elastalert-server:latest
docker-compose up --force-recreate --build

Then accessed the praeco web ui like before - but it returned empty page.

Reverting to praecoapp/praeco:1.8.15 made the tool operational again.

**Comment by nsano-rururu** [comment]
Fixed it to work properly.
The contents of the docker image have also been replaced.

praecoapp/praeco:latest
praecoapp/praeco:1.8.16

**Comment by poffyna** [comment]
The new images work fine for me.
Thanks for quick resolution.
