### ISSUE TITLE
We get a "closed" alert when the parameter is again below the threshold

### ISSUE THREAD

**Issue by Arun-Ghosh** [johnsusek/praeco#577]
## 🎉 Goal

Currently whenever parameter is above threshold we get an alert (We can think this as alert in "Open" condition) . Which is working superb 🎉.  But it would be better if we get a "Closed" alert when the parameter is again below the threshold.

## 💪 Motivation

1. We have to continuously check the UI to check whether the parameter are below the threshold.
2. When there are multiple alerts tracking will be much more easier.

## 📖 Reference (optional)

Its similar like we get in Grafana 😊

**Comment by nsano-rururu** [comment]
@Arun-Ghosh 
Looks like elastalert2's request. If so, I think it would be better to write your request in the repository below.
https://github.com/jertel/elastalert2
