### ISSUE TITLE
Can not select a Timeframe in any other option than "count".

### ISSUE THREAD

**Issue by SamuelBizon** [johnsusek/praeco#588]
Image versions:
praecoapp/praeco:1.8.16
praecoapp/elastalert-server:20231017

When choosing "count" option:
![image](https://github.com/johnsusek/praeco/assets/71435476/79bf5915-b8b0-42cb-9f8d-bd3deb960349)
you can choose the timeframe "for the last" x minutes.

However, if you choose anything other than "count", for example "average", you can not choose the timeframe:
![image](https://github.com/johnsusek/praeco/assets/71435476/25f475fa-4d0b-44e9-9ba0-f2c3031c914c)

Also, notice that "is above" is showing double.

**Comment by SamuelBizon** [comment]
Also in the first rule, in the yaml file it makes a field:
timeframe:
    minutes: 25
But in the second one it doesnt make any timeframe field.

**Comment by nsano-rururu** [comment]
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#rule-types

**Comment by nsano-rururu** [comment]
If yaml is not generated according to the specifications, we will consider fixing it, but Praeco is only a function to generate yaml to be used with elastalert2 with a GUI, and yaml operation is not supported.
As for the behavior of the generated yaml, you should probably ask in the elastalert2 discussion.
The rule type name displayed on the screen and the name of elastalert2 are different, so I would like to make them consistent in the future.
I didn't create it from scratch, but inherited it from somewhere in the middle, so I currently don't understand all the implementation specifications.
The double display is a bug, but since I don't do it for work, I can't promise when it will be fixed.
https://github.com/jertel/elastalert2/discussions

**Comment by nsano-rururu** [comment]
https://elastalert2.readthedocs.io/en/latest/recipes/faq.html

**Comment by nsano-rururu** [comment]
If you read the documentation, you should understand that the timeframe setting is not a setting used by all rule types. Why not start by researching it yourself?

**Comment by SamuelBizon** [comment]
I understood that the **buffer_time** serves similar function in Metric Aggregation ("average" selected) as **timeframe** in Frequency ("count" selected). Wouldnt it make sense to also have the "for the last x" for this ruletype as well but change the buffer_time instead ?
![image](https://github.com/johnsusek/praeco/assets/71435476/386bbd5c-2bfc-4e0a-bd59-29b57cfa17d7)
![image](https://github.com/johnsusek/praeco/assets/71435476/fa1fd217-beb6-4d5e-be0a-003ffc86ee4f)
Sorry I might have missunderstood.

One more bug I have found: When creating a rule and choosing certain amount of minutes in the "for the x"  option while "count" selected and then changing "count" to "average", the "for the x" option still stays there:
![image](https://github.com/johnsusek/praeco/assets/71435476/0b8a9a70-4f56-411a-9d65-de5a33db2530)
This caused me a little bit of confusion and I thought it is supposed to be there, you just cant edit it.

**Comment by nsano-rururu** [comment]
I think the related source code is the following three. I think the first file is the screen display file.
https://github.com/johnsusek/praeco/blob/master/src/components/config/ConfigCondition.vue
https://github.com/johnsusek/praeco/blob/master/src/store/config/index.js
https://github.com/johnsusek/praeco/blob/master/src/store/config/match.js

**Comment by nsano-rururu** [comment]
showForTheLast

https://github.com/johnsusek/praeco/blob/master/src/components/config/ConfigCondition.vue#L619

Display conditions for showForTheLast

https://github.com/johnsusek/praeco/blob/master/src/components/config/ConfigCondition.vue#L940

**Comment by nsano-rururu** [comment]
The following condition 941 is incorrect. It seems that it will be displayed if you modify the following so that it is true.
https://github.com/johnsusek/praeco/blob/master/src/components/config/ConfigCondition.vue#L941

**Comment by nsano-rururu** [comment]
The correct move is for buffer_time to be configurable in metric_aggregation.
The elastalert2 sample yaml also looks like this.
https://github.com/jertel/elastalert2/blob/master/examples/rules/example_single_metric_agg.yaml

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/blob/master/src/components/config/ConfigCondition.vue#L448
current
```
        <span v-if="spikeOrThreshold === 'is' || metricAggType !== 'count'" class="pop-trigger">
          <span>IS</span>
          <span v-if="numEvents || maxThreshold">
            ABOVE {{ metricAggType === 'count' ? numEvents : maxThreshold }}
          </span>
          <span v-if="(numEvents && threshold) || (maxThreshold && minThreshold)">
            &amp;
          </span>
          <span v-if="threshold || minThreshold">
            BELOW {{ metricAggType === 'count' ? threshold : minThreshold }}
          </span>
        </span>

        <span v-if="spikeOrThreshold === 'is' || metricAggType !== 'count'" class="pop-trigger">
          <span>IS</span>
          <span v-if="numEvents || maxThreshold">
            ABOVE {{ metricAggType === 'count' ? numEvents : maxThreshold }}
          </span>
          <span v-if="(numEvents && threshold) || (maxThreshold && minThreshold)">
            &amp;
          </span>
          <span v-if="threshold || minThreshold">
            BELOW {{ metricAggType === 'count' ? threshold : minThreshold }}
          </span>
        </span>
```
after
```
        <span v-if="spikeOrThreshold === 'is' || metricAggType !== 'count'" class="pop-trigger">
          <span>IS</span>
          <span v-if="numEvents || maxThreshold">
            ABOVE {{ metricAggType === 'count' ? numEvents : maxThreshold }}
          </span>
          <span v-if="(numEvents && threshold) || (maxThreshold && minThreshold)">
            &amp;
          </span>
          <span v-if="threshold || minThreshold">
            BELOW {{ metricAggType === 'count' ? threshold : minThreshold }}
          </span>
        </span>
```

**Comment by nsano-rururu** [comment]
@SamuelBizon 

The fixes have been identified and will be included in the next update, 1.8.17.

**Comment by SamuelBizon** [comment]
Awesome. Thank you so much.

**Comment by nsano-rururu** [comment]
https://github.com/johnsusek/praeco/commit/d17601bde95c4c7f4e119ff627bf66d60a9acc18

**Comment by nsano-rururu** [comment]
1.8.17 released. Contains corrections.
Docker image has also been released
