### ISSUE TITLE
Does ElastAlert support --start and --end options?

### ISSUE THREAD

**Issue by litsegaard** [johnsusek/praeco#625]
I'm running the latest docker image of ElastAlert as a service in docker compose and need to be able to specify a new default timeframe. ElastAlert2 supports the command line arguments --start and --end to allow this. Is this supported by ElastAlert? I've tried the following in my docker compose file but they don't seem to be picked up:

```
    command:
      - "--start"
      - "2023-12-08T14:05:12.661Z"
      - "--end"
      - "2023-12-12T15:00:37.908Z"
```
Am I missing something else here in order for this to work? Many thanks in advance.

**Comment by nsano-rururu** [comment]
Please use the official one.
https://hub.docker.com/r/jertel/elastalert2
https://github.com/jertel/elastalert2/pkgs/container/elastalert2%2Felastalert2

**Comment by litsegaard** [comment]
Ok, is the Praeco version of ElastAlert API compatible with ElastAlert2 meaning we'd be able to use Praeco with ElastAlert2 as backend?

**Comment by nsano-rururu** [comment]
You shouldn't use praeco to do what you want. The official docker image should have been published on elastalert2. We recommend operating the elastalert2 docker image alone.

**Comment by nsano-rururu** [comment]
https://hub.docker.com/r/jertel/elastalert2

**Comment by nsano-rururu** [comment]
praeco does not plan to add any functionality for the time being. Because Vue3 support is given top priority

**Comment by litsegaard** [comment]
No problem - I found that we may specify --start and --end in the api config json as "start": "<starttime>" and "end:" "<endtime>". However, I fully appreciate what you say - for our use case I concur with your suggestion to invoke the ElastAlert2 docker container with command line directives. Thanks for your support!

**Comment by nsano-rururu** [comment]
I didn't know that elastalert-server supports start and end.
