### ISSUE TITLE
Improvement:  make it easier to place cursor when composing email body

### ISSUE THREAD

**Issue by andrewmeyer** [johnsusek/praeco#64]
When composing the email body of an alert, it is difficult to place the cursor inside of the email when tags are being used.  This is likely because we are using "contenteditable" instead of a "textarea"

If possible, try to find a way to make cursor placement easier for users.  I had some difficulty editing the contents of my test email once I placed the relevant alert information into it.

**Comment by johnsusek** [comment]
Think this was browser handling contenteditable area poorly. Closing for now, please re-submit a bug if this is happening still
