### ISSUE TITLE
Create a Red Health Status for indices

### ISSUE THREAD

**Issue by redaER7** [johnsusek/praeco#641]
Hi Everyone,

I am running praeco 1.8.19 and would like to create an alert that scans all indices if there's an index with Red/Yellow health Status.

Is this achievable within the current release? if Yes, how can I create such alert ?

Thank you for your help

**Comment by nsano-rururu** [comment]
To create an alert, I recommend listening to the elastalert2 discussion on how to write YAML.
https://github.com/jertel/elastalert2/discussions
