### ISSUE TITLE
Not able to make connection to elasticseach

### ISSUE THREAD

**Issue by ishukeshri2712** [johnsusek/praeco#644]
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='xxxx', port=9200): Max retries exceeded with url: /praeco_elastalert_status/_search?size=1000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x783760c94a90>: Failed to establish a new connection: [Errno 111] Connection refused'))) caused by: ConnectionError(HTTPConnectionPool(host='xxxx', port=9200): Max retries exceeded with url: /praeco_elastalert_status/_search?size=1000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x783760c94a90>: Failed to establish a new connection: [Errno 111] Connection refused')))

**Comment by nsano-rururu** [comment]
es_conn_timeout
![image](https://github.com/johnsusek/praeco/assets/22293449/98a365cc-10cc-41f1-a856-95ce49f71f4d)

**Comment by nsano-rururu** [comment]
It takes time to start elastcsearch. If you are configuring everything with Docker, or if you are creating a docker-compose with the assumption that they will run simultaneously, you need to make sure that elasticsearch can be connected, and then set up a mechanism to connect elastarert2.
Below is a sample that I use to check the operation.
https://github.com/nsano-rururu/elastalert-server_praeco_docker-compose_sample

**Comment by nsano-rururu** [comment]
It takes time to start elasticsearch. In my local environment, it takes about 5 minutes for elasticsearch to start.

**Comment by nsano-rururu** [comment]
I think the situation will be different depending on the server's performance (cpu, memory, disk, etc.)...

**Comment by ishukeshri2712** [comment]
This issue is solved elasticsearch was not exposed to 0.0.0.0 that is the reason container not able to connect to ES running in VM
