### ISSUE TITLE
Can Praeco used for alerting for an elasticsearch Cluster?

### ISSUE THREAD

**Issue by ishukeshri2712** [johnsusek/praeco#645]
Can Praeco used for elasticsearch cluster?

**Comment by nsano-rururu** [comment]
No

**Comment by ishukeshri2712** [comment]
So you are saying it is for only one node elasticsearch cluster?

**Comment by nsano-rururu** [comment]
Yes

**Comment by nsano-rururu** [comment]
At least elastalert-server is not supported. elastalert2 may have supported it. Please see the documentation.
https://elastalert2.readthedocs.io/en/latest/index.html#

**Comment by nsano-rururu** [comment]
look
https://github.com/jertel/elastalert2/pull/548

**Comment by nsano-rururu** [comment]
https://github.com/jertel/elastalert2/discussions/401

**Comment by ishukeshri2712** [comment]
It use’s elastalert2 right?

**Comment by nsano-rururu** [comment]
You are using the correct one. elastalert-server does not support all the features of elstalert2.

**Comment by nsano-rururu** [comment]
Elastalert2 has a publicly available Docker image, so if you want to use all of its features, you should not use praeco.
https://github.com/jertel/elastalert2

**Comment by nsano-rururu** [comment]
praeco, elastalert-server are not official tools.

**Comment by ishukeshri2712** [comment]
I have required in my company where I have an elasticsearch  cluster and I want to send alerts on the basis of certain events in this elasticsearch cluster is it possible through praeco?

**Comment by nsano-rururu** [comment]
Bugs found during the development of praeco and elastalert-server are fed back to elastalert2. I have also submitted a pull request for elastalert2.

**Comment by nsano-rururu** [comment]
elasetalert-server and praeco are set to only have one es_host connection. If the one connection destination remains the same and the active and standby servers are switched due to synchronization in the background, I think praeco/elastalert-server should be able to handle it. I haven't tried it, so it's just a guess.

**Comment by ishukeshri2712** [comment]
Ok thank you I could have used elastalert2 but in my company the requirement is that we should add alerting rules through UI only not going to server so I m using this tool
