### ISSUE TITLE
Does praeco provide any authentication for accessing the UI on the basis of roles?

### ISSUE THREAD

**Issue by ishukeshri2712** [johnsusek/praeco#648]
Does praeco provide any authentication for accessing the UI on the basis of roles?

**Comment by nsano-rururu** [comment]
no

**Comment by nsano-rururu** [comment]
I don't have time to use OSS right now. I can't add any new features.

**Comment by thatsk** [comment]
https://dexidp.io/ can we add this as part of auth

**Comment by thatsk** [comment]
feedback

**Comment by nsano-rururu** [comment]
New feature development has ended
