### ISSUE TITLE
AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by ishukeshri2712** [johnsusek/praeco#650]
I m running praeco in two instances where my two praeco servers are running and it is attached to a single load balancer when i m trying to create rule, rule is getting created but i m getting this AxiosError: Request failed with status code 404 error what could be the reason?

**Comment by nsano-rururu** [comment]
Not Support

**Comment by nsano-rururu** [comment]
Currently, there are no bug fixes or new features.

**Comment by nsano-rururu** [comment]
I suggest you look for another oss, it's a waste of time.
