### ISSUE TITLE
praeco as daemon process

### ISSUE THREAD

**Issue by ishukeshri2712** [johnsusek/praeco#656]
can praeco be run as a daemon proceess?

**Comment by nsano-rururu** [comment]
It's a vue2 web application. It's not possible. It's not what you're looking for.

**Comment by nsano-rururu** [comment]
I think it's better to use elastalert2 on its own.
The official Docker image is also available.

**Comment by nsano-rururu** [comment]
It's a waste of time. I feel like praeco can't do what you want.
